-- Query ID: 01c39a49-0212-6e7d-24dd-07031944ea27
-- Database: FBG_ANALYTICS_DEV
-- Schema: JORDAN_PLUCHAR
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T22:33:14.759000+00:00
-- Elapsed: 3273ms
-- Environment: FBG

SELECT 
    DATE_TRUNC('MONTH', DATE)::DATE AS MONTH,
    SUM(MARKET_DEDUCTIONS) AS MARKET_DEDUCTIONS,
    SUM(OC_MARKET_DEDUCTIONS) AS OC_MARKET_DEDUCTIONS,
    SUM(OSB_TAX) AS OSB_TAX,
    SUM(OC_TAX) AS OC_TAX,
    SUM(OSB_ETAX) AS OSB_ETAX,
    SUM(OC_ETAX) AS OC_ETAX,
    SUM(GAMING_TAXES_PMTS_GEO) AS GAMING_TAXES_PMTS_GEO,
    SUM(SPORTS_DATA_VIZ_FEES) AS SPORTS_DATA_VIZ_FEES,
    SUM(ICASINO_CONTENT) AS ICASINO_CONTENT,
    SUM(FANCASH_ECOMM_USED) AS FANCASH_ECOMM_USED,
    SUM(TICKET_COST) AS TICKET_COST,
    SUM(GIFT_COST) AS GIFT_COST,
    SUM(OSB_CASH_BONUS) AS OSB_CASH_BONUS,
    SUM(OC_CASH_BONUS) AS OC_CASH_BONUS,
    SUM(OSB_FINANCE_BOOST_SPEND) AS OSB_BOOST_SPEND,
    SUM(OSB_EXPECTED_DEDUCTION) AS OSB_EXPECTED_DEDUCTION,
    SUM(EMARKET_DEDUCTIONS) AS EMARKET_DEDUCTIONS,
    SUM(ONE_CREDITS_OSB) AS ONE_CREDITS_OSB,
    SUM(ONE_CREDITS_OC) AS ONE_CREDITS_OC
FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.CUSTOMER_VARIABLE_PROFIT
WHERE STATE = 'CT'
  AND DATE BETWEEN '2025-12-01' AND '2026-03-31'
GROUP BY DATE_TRUNC('MONTH', DATE)
ORDER BY MONTH
