-- Query ID: 01c39a49-0212-67a8-24dd-07031944cbeb
-- Database: FBG_ANALYTICS_DEV
-- Schema: JORDAN_PLUCHAR
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T22:33:00.929000+00:00
-- Elapsed: 3422ms
-- Environment: FBG

SELECT 
    DATE_TRUNC('MONTH', DATE)::DATE AS MONTH,

    -- Handle
    SUM(OSB_FINANCE_TOTAL_HANDLE + OC_FINANCE_TOTAL_HANDLE) / 1000000 AS HANDLE_M,

    -- Total Gross Payouts (Handle - GGR = Payouts)
    SUM((OSB_FINANCE_TOTAL_HANDLE + OC_FINANCE_TOTAL_HANDLE) - (OSB_FINANCE_GGR + OC_FINANCE_GGR)) / 1000000 AS TOTAL_GROSS_PAYOUTS_M,

    -- Total Online Revenue (GGR)
    SUM(OSB_FINANCE_GGR + OC_FINANCE_GGR) / 1000000 AS TOTAL_ONLINE_REVENUE_M,

    -- Federal Excise Tax
    SUM(FED_EXCISE_TAX) / 1000000 AS FED_EXCISE_TAX_M,

    -- Sports Wagering Tax Bonus Deduction (bonus/promo deductions from tax basis)
    SUM(MARKET_DEDUCTIONS + OC_MARKET_DEDUCTIONS) / 1000000 AS TAX_BONUS_DEDUCTION_M,

    -- Sports Wagering Tax Basis (GGR - bonus deductions = taxable basis)
    SUM((OSB_FINANCE_GGR + OC_FINANCE_GGR) - (MARKET_DEDUCTIONS + OC_MARKET_DEDUCTIONS)) / 1000000 AS TAX_BASIS_M,

    -- Sports Wagering Tax
    SUM(OSB_TAX + OC_TAX) / 1000000 AS SPORTS_WAGERING_TAX_M,

    -- Additional Player Incentives (acquisition + retention bonuses)
    SUM(OSB_ACQUISITION_BONUS + OSB_RETENTION_BONUS + OC_ACQUISITION_BONUS + OC_RETENTION_BONUS) / 1000000 AS ADDL_PLAYER_INCENTIVES_M,

    -- Player-Related Costs (payment fees + geolocation)
    SUM(OSB_PAYMENT_FEES + OC_PAYMENT_FEES + GC_RATE) / 1000000 AS PLAYER_RELATED_COSTS_M,

    -- Operating Online Expenses (sports data/viz + icasino content)
    SUM(SPORTS_DATA_VIZ_FEES + ICASINO_CONTENT) / 1000000 AS OPERATING_ONLINE_EXPENSES_M,

    -- Marketing Costs (fancash ecomm + ticket + gift costs)
    SUM(FANCASH_ECOMM_USED + TICKET_COST + GIFT_COST) / 1000000 AS MARKETING_COSTS_M,

    -- Contribution Share Basis (market access fee)
    SUM(OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE) / 1000000 AS CONTRIBUTION_SHARE_M

FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.CUSTOMER_VARIABLE_PROFIT
WHERE STATE = 'CT'
  AND DATE BETWEEN '2025-12-01' AND '2026-03-31'
GROUP BY DATE_TRUNC('MONTH', DATE)
ORDER BY MONTH
