-- Query ID: 01c39a44-0212-67a8-24dd-07031944270b
-- Database: FBG_ANALYTICS_DEV
-- Schema: JORDAN_PLUCHAR
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T22:28:24.922000+00:00
-- Elapsed: 1089ms
-- Environment: FBG

SELECT 
    SUM(CASE WHEN STATE = 'CT' THEN OSB_FINANCE_GGR + OC_FINANCE_GGR ELSE 0 END) / 1000000 AS CT_GGR_M,
    SUM(CASE WHEN STATE = 'CT' THEN OSB_FINANCE_GGR + OC_FINANCE_GGR ELSE 0 END) * 0.10 / 1000000 AS CT_MKTG_DEDUCTION_M,
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) / 1000000 AS CT_CURRENT_MA_M,
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.90 / 1000000 AS CT_ADJUSTED_MA_M,
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.10 / 1000000 AS CT_MA_REDUCTION_M,
    SUM(OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE) / 1000000 AS TOTAL_CURRENT_MA_M,
    (SUM(CASE WHEN STATE != 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END)
     + SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.90
    ) / 1000000 AS TOTAL_ADJUSTED_MA_M,
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.10 / 1000000 AS TOTAL_MA_REDUCTION_M
FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.CUSTOMER_VARIABLE_PROFIT
WHERE DATE BETWEEN '2026-01-01' AND CURRENT_DATE()
