-- Query ID: 01c39a3b-0212-6e7d-24dd-07031942735b
-- Database: FBG_ANALYTICS_DEV
-- Schema: JORDAN_PLUCHAR
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T22:19:34.677000+00:00
-- Elapsed: 1927ms
-- Environment: FBG

SELECT 
    -- Total all-state market access fees
    SUM(OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE) / 1000000 AS TOTAL_ALL_STATE_MA_FEE_M,
    
    -- CT portion
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) / 1000000 AS CT_MA_FEE_M,
    
    -- CT adjusted (apply same rate to 90% of GGR)
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.90 / 1000000 AS CT_ADJUSTED_MA_FEE_M,
    
    -- Non-CT portion (unchanged)
    SUM(CASE WHEN STATE != 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) / 1000000 AS NON_CT_MA_FEE_M,
    
    -- Total adjusted (non-CT unchanged + CT adjusted)
    (SUM(CASE WHEN STATE != 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END)
     + SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.90
    ) / 1000000 AS TOTAL_ADJUSTED_MA_FEE_M,
    
    -- Reduction
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.10 / 1000000 AS REDUCTION_M
FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.CUSTOMER_VARIABLE_PROFIT
WHERE DATE BETWEEN '2025-03-01' AND '2025-03-31'
