-- Query ID: 01c39a49-0212-67a9-24dd-0703194551eb
-- Database: FBG_ANALYTICS_DEV
-- Schema: JORDAN_PLUCHAR
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T22:33:44.886000+00:00
-- Elapsed: 1741ms
-- Environment: FBG

SELECT 
    DATE_TRUNC('MONTH', DATE)::DATE AS MONTH,

    -- Handle
    ROUND(SUM(OSB_FINANCE_TOTAL_HANDLE + OC_FINANCE_TOTAL_HANDLE) / 1000000, 2) AS HANDLE,

    -- Total Gross Payouts (Handle - GGR)
    ROUND(SUM((OSB_FINANCE_TOTAL_HANDLE + OC_FINANCE_TOTAL_HANDLE) - (OSB_FINANCE_GGR + OC_FINANCE_GGR)) / 1000000, 2) AS GROSS_PAYOUTS,

    -- Total Online Revenue (GGR)
    ROUND(SUM(OSB_FINANCE_GGR + OC_FINANCE_GGR) / 1000000, 2) AS ONLINE_REVENUE,

    -- Federal Excise Tax
    ROUND(SUM(FED_EXCISE_TAX) / 1000000, 3) AS FED_EXCISE_TAX,

    -- Sports Wagering Tax Bonus Deduction (MARKET_DEDUCTIONS = promo/bonus deduction from GGR for tax purposes)
    ROUND(SUM(MARKET_DEDUCTIONS) / 1000000, 3) AS TAX_BONUS_DEDUCTION,

    -- Sports Wagering Tax Basis (GGR - bonus deductions)
    ROUND(SUM(OSB_FINANCE_GGR + OC_FINANCE_GGR - MARKET_DEDUCTIONS) / 1000000, 2) AS TAX_BASIS,

    -- Sports Wagering Tax
    ROUND(SUM(OSB_TAX + COALESCE(OC_TAX, 0)) / 1000000, 3) AS WAGERING_TAX,

    -- Additional Player Incentives (acquisition + retention bonuses beyond what's in NGR)
    ROUND(SUM(COALESCE(OSB_ACQUISITION_BONUS, 0) + COALESCE(OSB_RETENTION_BONUS, 0) 
            + COALESCE(OC_ACQUISITION_BONUS, 0) + COALESCE(OC_RETENTION_BONUS, 0)) / 1000000, 3) AS PLAYER_INCENTIVES,

    -- Player-Related Costs (payment fees + geolocation)
    ROUND(SUM(OSB_PAYMENT_FEES + COALESCE(OC_PAYMENT_FEES, 0) + GC_RATE) / 1000000, 3) AS PLAYER_RELATED_COSTS,

    -- Operating Online Expenses (sports data/viz fees + icasino content)
    ROUND(SUM(SPORTS_DATA_VIZ_FEES + COALESCE(ICASINO_CONTENT, 0)) / 1000000, 3) AS OPERATING_EXPENSES,

    -- Marketing Costs (fancash ecomm + ticket + gift + one credits)
    ROUND(SUM(COALESCE(FANCASH_ECOMM_USED, 0) + COALESCE(TICKET_COST, 0) + COALESCE(GIFT_COST, 0)
            + COALESCE(ONE_CREDITS_OSB, 0) + COALESCE(ONE_CREDITS_OC, 0)) / 1000000, 3) AS MARKETING_COSTS,

    -- Contribution Share Basis (market access fee)
    ROUND(SUM(OSB_MARKET_ACCESS_FEE + COALESCE(OC_MARKET_ACCESS_FEE, 0)) / 1000000, 3) AS CONTRIBUTION_SHARE

FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.CUSTOMER_VARIABLE_PROFIT
WHERE STATE = 'CT'
  AND DATE BETWEEN '2025-12-01' AND '2026-03-31'
GROUP BY DATE_TRUNC('MONTH', DATE)
ORDER BY MONTH
