-- Query ID: 01c39a51-0212-6dbe-24dd-07031946cc6b
-- Database: FBG_ANALYTICS_DEV
-- Schema: JACOB_KAZE
-- Warehouse: BI_L_WH
-- Executed: 2026-04-09T22:41:05.100000+00:00
-- Elapsed: 922ms
-- Environment: FBG

CREATE TABLE IF NOT EXISTS FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.ATL_MEDIA_SPEND (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CAMPAIGN_NAME VARCHAR(500) NOT NULL,
    CHANNEL VARCHAR(100) NOT NULL,
    PLATFORM VARCHAR(200),
    SPEND_AMOUNT NUMBER(18,2) NOT NULL,
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    CONVERSIONS NUMBER,
    SPEND_DATE DATE NOT NULL,
    REGION VARCHAR(100),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
