-- Query ID: 01c39a44-0212-6e7d-24dd-0703194441f3
-- Database: FBG_ANALYTICS_DEV
-- Schema: JORDAN_PLUCHAR
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T22:28:13.025000+00:00
-- Elapsed: 2847ms
-- Environment: FBG

SELECT 
    DATE_TRUNC('MONTH', DATE)::DATE AS MONTH,
    
    -- CT GGR
    SUM(CASE WHEN STATE = 'CT' THEN OSB_FINANCE_GGR + OC_FINANCE_GGR ELSE 0 END) / 1000000 AS CT_GGR_M,
    
    -- CT Marketing Deduction (10% of GGR)
    SUM(CASE WHEN STATE = 'CT' THEN OSB_FINANCE_GGR + OC_FINANCE_GGR ELSE 0 END) * 0.10 / 1000000 AS CT_MKTG_DEDUCTION_M,
    
    -- CT Current MA Fee
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) / 1000000 AS CT_CURRENT_MA_M,
    
    -- CT Adjusted MA Fee (apply same rate to 90% GGR)
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.90 / 1000000 AS CT_ADJUSTED_MA_M,
    
    -- CT Reduction
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.10 / 1000000 AS CT_MA_REDUCTION_M,
    
    -- Total All-State Current MA Fee
    SUM(OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE) / 1000000 AS TOTAL_CURRENT_MA_M,
    
    -- Total All-State Adjusted MA Fee
    (SUM(CASE WHEN STATE != 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END)
     + SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.90
    ) / 1000000 AS TOTAL_ADJUSTED_MA_M,
    
    -- Total Reduction
    SUM(CASE WHEN STATE = 'CT' THEN OSB_MARKET_ACCESS_FEE + OC_MARKET_ACCESS_FEE ELSE 0 END) * 0.10 / 1000000 AS TOTAL_MA_REDUCTION_M

FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.CUSTOMER_VARIABLE_PROFIT
WHERE DATE BETWEEN '2026-01-01' AND CURRENT_DATE()
GROUP BY DATE_TRUNC('MONTH', DATE)
ORDER BY MONTH
