-- Query ID: 01c39a49-0212-67a8-24dd-070319454197
-- Database: FBG_ANALYTICS_DEV
-- Schema: JORDAN_PLUCHAR
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T22:33:28.175000+00:00
-- Elapsed: 2366ms
-- Environment: FBG

SELECT 
    DATE_TRUNC('MONTH', DATE)::DATE AS MONTH,
    -- Bonus deductible flag for CT
    MAX(BONUS_DEDUCTIBLE) AS BONUS_DEDUCTIBLE_FLAG,
    MAX(GAMING_TAXES_DEDUCTIBLE) AS GAMING_TAXES_DEDUCTIBLE_FLAG,
    MAX(PAYMENTS_GEOLOC_KYC_DEDUCTIBLE) AS PMTS_GEO_DEDUCTIBLE_FLAG,

    -- GGR vs NGR breakdown
    SUM(OSB_FINANCE_GGR) AS OSB_GGR,
    SUM(OC_FINANCE_GGR) AS OC_GGR,
    SUM(OSB_FINANCE_NGR) AS OSB_NGR,
    SUM(OC_FINANCE_NGR) AS OC_NGR,
    
    -- Bonus handle (proxy for bonus deductions)
    SUM(OSB_FINANCE_BONUS_HANDLE) AS OSB_BONUS_HANDLE,
    SUM(OC_FINANCE_BONUS_HANDLE) AS OC_BONUS_HANDLE,
    
    -- Boost spend (promo cost)
    SUM(OSB_FINANCE_BOOST_SPEND) AS OSB_BOOST_SPEND,
    SUM(OSB_FINANCE_EBOOST_SPEND) AS OSB_EBOOST_SPEND,
    
    -- Commercial NGR
    SUM(OSB_COMMERCIAL_NGR) AS OSB_COMMERCIAL_NGR,
    SUM(OC_COMMERCIAL_NGR) AS OC_COMMERCIAL_NGR

FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.CUSTOMER_VARIABLE_PROFIT
WHERE STATE = 'CT'
  AND DATE BETWEEN '2025-12-01' AND '2026-03-31'
GROUP BY DATE_TRUNC('MONTH', DATE)
ORDER BY MONTH
