-- Query ID: 01c39a0c-0112-6b51-0000-e307218b766a
-- Database: unknown
-- Schema: unknown
-- Warehouse: FDE_FES_ANALYST_XL_WH
-- Executed: 2026-04-09T21:32:14.314000+00:00
-- Elapsed: 235ms
-- Environment: FES

SELECT SYSTEM$VALIDATE_QUERY('WITH base AS (
    SELECT
        CLIENT_CUSTOMER_ID AS FANGRAPH_ID,
        TRIM(AUDIENCE_NAME) AS AUDIENCE_NAME
    FROM GROWTHLOOP.FLYWHEEL_SYSTEM.SNAPSHOTTING_LATEST_SNAPSHOTS
    WHERE TRIM(AUDIENCE_NAME) IN (
        ''FAN_League_NHL_T2'',
        ''FAN_League_NFL_T2'',
        ''FAN_League_MLB_T2'',
        ''FAN_League_NBA_T2'',
        ''FAN_League_NCAA_T2'',
        ''FAN_League_CombatSports_T1'',
        ''FAN_AllFans_T1''
    )
),
with_demos AS (
    SELECT
        b.FANGRAPH_ID,
        b.AUDIENCE_NAME,
        CASE
            WHEN aa.AGE BETWEEN 18 AND 20 THEN ''18-20''
            WHEN aa.AGE BETWEEN 21 AND 30 THEN ''21-30''
            WHEN aa.AGE BETWEEN 31 AND 40 THEN ''31-40''
            WHEN aa.AGE BETWEEN 41 AND 50 THEN ''41-50''
            WHEN aa.AGE BETWEEN 51 AND 60 THEN ''51-60''
            WHEN aa.AGE BETWEEN 61 AND 70 THEN ''61-70''
            WHEN aa.AGE BETWEEN 71 AND 80 THEN ''71-80''
            WHEN aa.AGE > 80 THEN ''80+''
        END AS AGE_BUCKET,
        fg.FANGRAPH_GENDER AS GENDER,
        aa.INCOME_HH
    FROM base b
    LEFT JOIN FANGRAPH.AAIA.AAIA_ID_LKP lkp
        ON lkp.FANGRAPH_ID = b.FANGRAPH_ID
    LEFT JOIN FANGRAPH.AAIA.AUDIENCE_ACUITY aa
        ON aa.ID = lkp.AAIA_ID
    LEFT JOIN FANGRAPH.ADMIN.FANGRAPH fg
        ON fg.FANGRAPH_ID = b.FANGRAPH_ID
),
total_audience AS (
    SELECT AUDIENCE_NAME, ''TOTAL AUDIENCE'' AS CATEGORY, ''ALL'' AS BREAKDOWN, COUNT(DISTINCT FANGRAPH_ID) AS FANGRAPH_ID_COUNT
    FROM base
    GROUP BY AUDIENCE_NAME
),
age_breakdown AS (
    SELECT AUDIENCE_NAME, ''AGE'' AS CATEGORY, AGE_BUCKET AS BREAKDOWN, COUNT(DISTINCT FANGRAPH_ID) AS FANGRAPH_ID_COUNT
    FROM with_demos
    WHERE AGE_BUCKET IS NOT NULL
    GROUP BY AUDIENCE_NAME, AGE_BUCKET
),
gender_breakdown AS (
    SELECT AUDIENCE_NAME, ''GENDER'' AS CATEGORY, GENDER AS BREAKDOWN, COUNT(DISTINCT FANGRAPH_ID) AS FANGRAPH_ID_COUNT
    FROM with_demos
    WHERE GENDER IN (''MALE'', ''FEMALE'')
    GROUP BY AUDIENCE_NAME, GENDER
),
income_breakdown AS (
    SELECT AUDIENCE_NAME, ''INCOME'' AS CATEGORY, INCOME_HH AS BREAKDOWN, COUNT(DISTINCT FANGRAPH_ID) AS FANGRAPH_ID_COUNT
    FROM with_demos
    WHERE INCOME_HH IS NOT NULL AND INCOME_HH != ''O. $250K +''
    GROUP BY AUDIENCE_NAME, INCOME_HH
)
SELECT * FROM total_audience
UNION ALL
SELECT * FROM age_breakdown
UNION ALL
SELECT * FROM gender_breakdown
UNION ALL
SELECT * FROM income_breakdown
LIMIT 1')
