-- Query ID: 01c39a14-0112-6be5-0000-e307218bb566
-- Database: unknown
-- Schema: unknown
-- Warehouse: FDE_FES_ANALYST_XL_WH
-- Executed: 2026-04-09T21:40:13.913000+00:00
-- Elapsed: 262143ms
-- Environment: FES

SELECT
    b.FANGRAPH_ID,
    b.AUDIENCE_NAME,
    b.SNAPSHOTTED_AT,
    fg.FANGRAPH_GENDER AS GENDER,
    aa.AGE,
    CASE
        WHEN aa.AGE BETWEEN 18 AND 20 THEN '18-20'
        WHEN aa.AGE BETWEEN 21 AND 30 THEN '21-30'
        WHEN aa.AGE BETWEEN 31 AND 40 THEN '31-40'
        WHEN aa.AGE BETWEEN 41 AND 50 THEN '41-50'
        WHEN aa.AGE BETWEEN 51 AND 60 THEN '51-60'
        WHEN aa.AGE BETWEEN 61 AND 70 THEN '61-70'
        WHEN aa.AGE BETWEEN 71 AND 80 THEN '71-80'
        WHEN aa.AGE > 80 THEN '80+'
    END AS AGE_BUCKET,
    aa.INCOME_HH,
    CASE WHEN aa.AGE BETWEEN 18 AND 20 THEN 1 ELSE 0 END AS IS_AGE_18_20,
    CASE WHEN aa.AGE BETWEEN 21 AND 30 THEN 1 ELSE 0 END AS IS_AGE_21_30,
    CASE WHEN aa.AGE BETWEEN 31 AND 40 THEN 1 ELSE 0 END AS IS_AGE_31_40,
    CASE WHEN aa.AGE BETWEEN 41 AND 50 THEN 1 ELSE 0 END AS IS_AGE_41_50,
    CASE WHEN aa.AGE BETWEEN 51 AND 60 THEN 1 ELSE 0 END AS IS_AGE_51_60,
    CASE WHEN aa.AGE BETWEEN 61 AND 70 THEN 1 ELSE 0 END AS IS_AGE_61_70,
    CASE WHEN aa.AGE BETWEEN 71 AND 80 THEN 1 ELSE 0 END AS IS_AGE_71_80,
    CASE WHEN aa.AGE > 80 THEN 1 ELSE 0 END AS IS_AGE_80_PLUS,
    CASE WHEN fg.FANGRAPH_GENDER = 'MALE' THEN 1 ELSE 0 END AS IS_MALE,
    CASE WHEN fg.FANGRAPH_GENDER = 'FEMALE' THEN 1 ELSE 0 END AS IS_FEMALE,
    CASE WHEN aa.INCOME_HH IS NOT NULL AND aa.INCOME_HH != 'O. $250K +' THEN 1 ELSE 0 END AS HAS_INCOME_DATA
FROM (
    SELECT
        CLIENT_CUSTOMER_ID AS FANGRAPH_ID,
        TRIM(AUDIENCE_NAME) AS AUDIENCE_NAME,
        SNAPSHOTTED_AT
    FROM GROWTHLOOP.FLYWHEEL_SYSTEM.SNAPSHOTTING_LATEST_SNAPSHOTS
) b
LEFT JOIN FANGRAPH.AAIA.AAIA_ID_LKP lkp
    ON lkp.FANGRAPH_ID = b.FANGRAPH_ID
LEFT JOIN FANGRAPH.AAIA.AUDIENCE_ACUITY aa
    ON aa.ID = lkp.AAIA_ID
LEFT JOIN FANGRAPH.ADMIN.FANGRAPH fg
    ON fg.FANGRAPH_ID = b.FANGRAPH_ID;
