-- Query ID: 01c39a0a-0112-6029-0000-e307218b843e
-- Database: unknown
-- Schema: unknown
-- Warehouse: FDE_FES_ANALYST_XL_WH
-- Executed: 2026-04-09T21:30:59.901000+00:00
-- Elapsed: 1572ms
-- Environment: FES

SELECT AUDIENCE_NAME, COUNT(*) AS cnt, MIN(SNAPSHOTTED_AT) AS min_snap, MAX(SNAPSHOTTED_AT) AS max_snap
FROM GROWTHLOOP.FLYWHEEL_SYSTEM.SNAPSHOTTING_LATEST_SNAPSHOTS
WHERE AUDIENCE_NAME IN (
  'FAN_League_NHL_T2',
  'FAN_League_NFL_T2',
  'FAN_League_MLB_T2',
  'FAN_League_NBA_T2',
  'FAN_League_NCAA_T2',
  'FAN_League_CombatSports_T1',
  'FAN_AllFans_T1'
)
GROUP BY AUDIENCE_NAME
ORDER BY AUDIENCE_NAME
