-- Query ID: 01c399e5-0112-6029-0000-e307218a53ae
-- Database: FDE_DEV
-- Schema: FDE_STAGE
-- Warehouse: FDE_DEVELOPER_XL_WH
-- Executed: 2026-04-09T20:53:35.276000+00:00
-- Elapsed: 1142ms
-- Environment: FES

create or replace  temporary view fangraph_dev.admin.fangraph_snapshots__dbt_tmp
  
    
    
(
  
    "FANGRAPH_ID" COMMENT $$$$, 
  
    "FANGRAPH_FIRST_NAME" COMMENT $$$$, 
  
    "FANGRAPH_LAST_NAME" COMMENT $$$$, 
  
    "FANGRAPH_GENDER" COMMENT $$$$, 
  
    "FANGRAPH_EMAIL" COMMENT $$$$, 
  
    "FANGRAPH_ADDRESS_1" COMMENT $$$$, 
  
    "FANGRAPH_ADDRESS_2" COMMENT $$$$, 
  
    "FANGRAPH_CITY" COMMENT $$$$, 
  
    "FANGRAPH_STATE" COMMENT $$$$, 
  
    "FANGRAPH_ZIP" COMMENT $$$$, 
  
    "FANGRAPH_COUNTRY" COMMENT $$$$, 
  
    "FANGRAPH_PHONE" COMMENT $$$$, 
  
    "FANATICS_EMPLOYEE_FLAG" COMMENT $$$$, 
  
    "FBG_EMPLOYEE_FLAG" COMMENT $$$$, 
  
    "FANGRAPH_PHONE_DNC" COMMENT $$$$, 
  
    "FANGRAPH_ACCOUNT_ACCESS_AVAILABLE" COMMENT $$$$, 
  
    "FANGRAPH_OPTED_INTO_EMAIL_MARKETING" COMMENT $$$$, 
  
    "FANGRAPH_DOB" COMMENT $$$$, 
  
    "FANGRAPH_AGE_RANGE" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_LEAGUE" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_NFL" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_NCAA" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_NBA" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_NHL" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_MLB" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_NFL_TEAMS" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_NCAA_TEAMS" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_NBA_TEAMS" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_NHL_TEAMS" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_MLB_TEAMS" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_TEAM" COMMENT $$$$, 
  
    "FANGRAPH_PREFERENCE_PLAYER" COMMENT $$$$, 
  
    "FANGRAPH_LAST_UPDATED_TIMESTAMP" COMMENT $$$$, 
  
    "FANGRAPH_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "TLC_FIRST_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "EMAIL_COUNT" COMMENT $$$$, 
  
    "FAN_KEYS" COMMENT $$$$, 
  
    "FAN_KEYS_CNT" COMMENT $$$$, 
  
    "ACCOUNT_IDS" COMMENT $$$$, 
  
    "ACCOUNT_IDS_CNT" COMMENT $$$$, 
  
    "FANID_PRIVATE_FAN_IDS" COMMENT $$$$, 
  
    "FANID_PRIVATE_FAN_IDS_CNT" COMMENT $$$$, 
  
    "COMMERCE_TENANT_FAN_IDS" COMMENT $$$$, 
  
    "COMMERCE_TENANT_FAN_IDS_CNT" COMMENT $$$$, 
  
    "FBG_TENANT_FAN_IDS" COMMENT $$$$, 
  
    "FBG_TENANT_FAN_IDS_CNT" COMMENT $$$$, 
  
    "LIVE_TENANT_FAN_IDS" COMMENT $$$$, 
  
    "LIVE_TENANT_FAN_IDS_CNT" COMMENT $$$$, 
  
    "FANAPP_TENANT_FAN_IDS" COMMENT $$$$, 
  
    "FANAPP_TENANT_FAN_IDS_CNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_USER_IDS" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_USER_IDS_CNT" COMMENT $$$$, 
  
    "TOPPS_USER_PROFILE_KEYS" COMMENT $$$$, 
  
    "TOPPS_USER_PROFILE_KEYS_CNT" COMMENT $$$$, 
  
    "TOPPS_COM_CUSTOMER_ID" COMMENT $$$$, 
  
    "COMMERCE_FAN_INDICATOR" COMMENT $$$$, 
  
    "FBG_FAN_INDICATOR" COMMENT $$$$, 
  
    "LIVE_FAN_INDICATOR" COMMENT $$$$, 
  
    "FANAPP_FAN_INDICATOR" COMMENT $$$$, 
  
    "TOPPS_COM_FAN_INDICATOR" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_FAN_INDICATOR" COMMENT $$$$, 
  
    "EVENTS_FAN_INDICATOR" COMMENT $$$$, 
  
    "COLLECT_FAN_INDICATOR" COMMENT $$$$, 
  
    "COMMERCE_CUSTOMER_INDICATOR" COMMENT $$$$, 
  
    "FBG_CUSTOMER_INDICATOR" COMMENT $$$$, 
  
    "LIVE_CUSTOMER_INDICATOR" COMMENT $$$$, 
  
    "FANAPP_CUSTOMER_INDICATOR" COMMENT $$$$, 
  
    "TOPPS_COM_CUSTOMER_INDICATOR" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_CUSTOMER_INDICATOR" COMMENT $$$$, 
  
    "EVENTS_CUSTOMER_INDICATOR" COMMENT $$$$, 
  
    "COLLECT_CUSTOMER_INDICATOR" COMMENT $$$$, 
  
    "FAN_KEY_CREATED_TIMESTAMP" COMMENT $$$$, 
  
    "COMMERCE_INTERNAL_SURROGATE_KEY" COMMENT $$$$, 
  
    "COMMERCE_ACCOUNT_DIRECTORY_ID" COMMENT $$$$, 
  
    "COMMERCE_ACCOUNT_TYPE" COMMENT $$$$, 
  
    "COMMERCE_HASHED_EMAIL" COMMENT $$$$, 
  
    "COMMERCE_FIRST_NAME" COMMENT $$$$, 
  
    "COMMERCE_LAST_NAME" COMMENT $$$$, 
  
    "COMMERCE_ACCOUNT_EMAIL" COMMENT $$$$, 
  
    "COMMERCE_MOBILE_NUMBER" COMMENT $$$$, 
  
    "COMMERCE_BILLING_ADDRESS_ID" COMMENT $$$$, 
  
    "COMMERCE_BILLING_STREET_ADDRESS1" COMMENT $$$$, 
  
    "COMMERCE_BILLING_STREET_ADDRESS2" COMMENT $$$$, 
  
    "COMMERCE_BILLING_CITY" COMMENT $$$$, 
  
    "COMMERCE_BILLING_STATE" COMMENT $$$$, 
  
    "COMMERCE_BILLING_COUNTRY" COMMENT $$$$, 
  
    "COMMERCE_BILLING_ZIP_CODE" COMMENT $$$$, 
  
    "COMMERCE_BILLING_ZIP_CODE_EXTENSION" COMMENT $$$$, 
  
    "COMMERCE_SHIPPING_ADDRESS_ID" COMMENT $$$$, 
  
    "COMMERCE_SHIPPING_STREET_ADDRESS1" COMMENT $$$$, 
  
    "COMMERCE_SHIPPING_STREET_ADDRESS2" COMMENT $$$$, 
  
    "COMMERCE_SHIPPING_CITY" COMMENT $$$$, 
  
    "COMMERCE_SHIPPING_STATE" COMMENT $$$$, 
  
    "COMMERCE_SHIPPING_COUNTRY" COMMENT $$$$, 
  
    "COMMERCE_SHIPPING_ZIP_CODE" COMMENT $$$$, 
  
    "COMMERCE_SHIPPING_ZIP_CODE_EXTENSION" COMMENT $$$$, 
  
    "FANID_FIRST_TENANT_ID" COMMENT $$$$, 
  
    "FANID_FIRST_TENANT_CREATED_TIMESTAMP" COMMENT $$$$, 
  
    "FANID_LAST_TENANT_MODIFIED_TIMESTAMP" COMMENT $$$$, 
  
    "FANID_TENANT_COUNT" COMMENT $$$$, 
  
    "COMMERCE_USER_ACCOUNT_ID" COMMENT $$$$, 
  
    "COMMERCE_SURROGATE_ACCOUNT_KEY" COMMENT $$$$, 
  
    "FANATICS_ONE_TRANSACTION_TIMESTAMP" COMMENT $$$$, 
  
    "FANATICS_ONE_CURRENT_BALANCE" COMMENT $$$$, 
  
    "FANATICS_ONE_CURRENT_TIER_ENTRY_TIMESTAMP" COMMENT $$$$, 
  
    "FANATICS_ONE_CURRENT_TIER" COMMENT $$$$, 
  
    "FANATICS_ONE_EARN_TIER" COMMENT $$$$, 
  
    "FANATICS_ONE_NEXT_EARN_TIER" COMMENT $$$$, 
  
    "FANATICS_ONE_AMOUNT_TO_NEXT_EARN_TIER" COMMENT $$$$, 
  
    "COMMERCE_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "COMMERCE_ACCOUNT_LAST_MODIFIED_TIMESTAMP" COMMENT $$$$, 
  
    "COMMERCE_LAST_UPDATED_TIMESTAMP" COMMENT $$$$, 
  
    "COMMERCE_SITE_COUNT" COMMENT $$$$, 
  
    "COMMERCE_NOT_MAILABLE_SITE_COUNT" COMMENT $$$$, 
  
    "COMMERCE_MAILABLE_SITE_COUNT" COMMENT $$$$, 
  
    "COMMERCE_MAILABLE_FLAG" COMMENT $$$$, 
  
    "COMMERCE_MAILABLE_FLAG_OPT_OUT_DATE" COMMENT $$$$, 
  
    "COMMERCE_SUPER_SITE_RESTRICTION" COMMENT $$$$, 
  
    "COMMERCE_ORDER_COUNT" COMMENT $$$$, 
  
    "COMMERCE_ORDER_AMOUNT_TOTAL" COMMENT $$$$, 
  
    "COMMERCE_DISCOUNT_TOTAL" COMMENT $$$$, 
  
    "COMMERCE_FANCASH_TOTAL" COMMENT $$$$, 
  
    "COMMERCE_FIRST_ORDER_TIMESTAMP" COMMENT $$$$, 
  
    "COMMERCE_LAST_ORDER_TIMESTAMP" COMMENT $$$$, 
  
    "COMMERCE_NFL_REGULATION" COMMENT $$$$, 
  
    "COMMERCE_NFL_ONLY" COMMENT $$$$, 
  
    "COMMERCE_FAN_SEGMENT" COMMENT $$$$, 
  
    "COMMERCE_PRODUCT_LEAGUE" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_NFL" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_NCAA" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_NBA" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_NHL" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_MLB" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_NFL_TEAMS" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_NCAA_TEAMS" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_NBA_TEAMS" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_NHL_TEAMS" COMMENT $$$$, 
  
    "COMMERCE_PREFERENCE_MLB_TEAMS" COMMENT $$$$, 
  
    "COMMERCE_PRODUCT_PLAYER_NAME" COMMENT $$$$, 
  
    "COMMERCE_PRODUCT_PLAYER_DESCRIPTION" COMMENT $$$$, 
  
    "COMMERCE_PRODUCT_TEAM" COMMENT $$$$, 
  
    "FANAPP_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "FANAPP_FIRST_LOGIN_TIMESTAMP" COMMENT $$$$, 
  
    "FANAPP_LAST_LOGIN_TIMESTAMP" COMMENT $$$$, 
  
    "FANAPP_SESSION_LAST_TIMESTAMP" COMMENT $$$$, 
  
    "FANAPP_F5JACKPOT_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_F5JACKPOT_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_F5JACKPOT_GAMES_WON" COMMENT $$$$, 
  
    "FANAPP_F5JACKPOT_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FANAPP_FANATICS5_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_FANATICS5_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_FANATICS5_GAMES_WON" COMMENT $$$$, 
  
    "FANAPP_FANATICS5_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FANAPP_PERFECT9_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_PERFECT9_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_PERFECT9_GAMES_WON" COMMENT $$$$, 
  
    "FANAPP_PERFECT9_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FANAPP_PERFECT9V2_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_PERFECT9V2_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_PERFECT9V2_GAMES_WON" COMMENT $$$$, 
  
    "FANAPP_PERFECT9V2_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FANAPP_QUADGOALS_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_QUADGOALS_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_QUADGOALS_GAMES_WON" COMMENT $$$$, 
  
    "FANAPP_QUADGOALS_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FANAPP_TIERED_PICKEM_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_TIERED_PICKEM_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_TIERED_PICKEM_GAMES_WON" COMMENT $$$$, 
  
    "FANAPP_TIERED_PICKEM_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FANAPP_SPINTOWIN_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_SPINTOWIN_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_SPINTOWIN_TIMES_WON" COMMENT $$$$, 
  
    "FANAPP_SPINTOWIN_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FANAPP_SURVIVOR_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_SURVIVOR_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_SURVIVOR_GAMES_WON" COMMENT $$$$, 
  
    "FANAPP_SURVIVOR_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FANAPP_COMMERCE_ORDER_COUNT" COMMENT $$$$, 
  
    "FANAPP_COMMERCE_ORDER_AMOUNT_TOTAL" COMMENT $$$$, 
  
    "FANAPP_COMMERCE_DISCOUNT_TOTAL" COMMENT $$$$, 
  
    "FANAPP_COMMERCE_FANCASH_TOTAL" COMMENT $$$$, 
  
    "FANAPP_COMMERCE_FIRST_ORDER_TIMESTAMP" COMMENT $$$$, 
  
    "FANAPP_COMMERCE_LAST_ORDER_TIMESTAMP" COMMENT $$$$, 
  
    "FANAPP_GAMES_TIMES_PLAYED" COMMENT $$$$, 
  
    "FANAPP_GAMES_EVER_WON" COMMENT $$$$, 
  
    "FANAPP_GAMES_TIMES_WON" COMMENT $$$$, 
  
    "FANAPP_GAMES_LAST_PLAYED_DATE" COMMENT $$$$, 
  
    "FBG_ACCOUNT_ID" COMMENT $$$$, 
  
    "FBG_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_LAST_MODIFIED_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_ACCOUNT_DELETED" COMMENT $$$$, 
  
    "FBG_STATUS" COMMENT $$$$, 
  
    "FBG_NAME" COMMENT $$$$, 
  
    "FBG_FIRST_NAME" COMMENT $$$$, 
  
    "FBG_LAST_NAME" COMMENT $$$$, 
  
    "FBG_EMAIL" COMMENT $$$$, 
  
    "FBG_ADDRESS1" COMMENT $$$$, 
  
    "FBG_ADDRESS2" COMMENT $$$$, 
  
    "FBG_TOWN" COMMENT $$$$, 
  
    "FBG_STATE" COMMENT $$$$, 
  
    "FBG_ZIP_CODE" COMMENT $$$$, 
  
    "FBG_COUNTRY" COMMENT $$$$, 
  
    "FBG_COUNTRY_CODE" COMMENT $$$$, 
  
    "FBG_BET_LIMIT" COMMENT $$$$, 
  
    "FBG_LIVE_BET_LIMIT" COMMENT $$$$, 
  
    "FBG_CURRENT_JURISDICTIONS_ID" COMMENT $$$$, 
  
    "FBG_JURISDICTION_NAME" COMMENT $$$$, 
  
    "FBG_HIGH_LEVEL_SEGMENT" COMMENT $$$$, 
  
    "FBG_SEGMENT" COMMENT $$$$, 
  
    "FBG_IS_PB_USER" COMMENT $$$$, 
  
    "FBG_IS_DATA_SHARING" COMMENT $$$$, 
  
    "FBG_KYC_COMPLETED_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_EXCLUSION" COMMENT $$$$, 
  
    "FBG_VIP_ID" COMMENT $$$$, 
  
    "FBG_VIP_TIERS" COMMENT $$$$, 
  
    "FBG_VIP_TIER_MODIFIED_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_UNSUBSCRIBED_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_FIRST_LOGIN_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_LAST_LOGIN_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_TRANSACTION_TOTAL" COMMENT $$$$, 
  
    "FBG_TOTAL_TRANSACTION_COUNT" COMMENT $$$$, 
  
    "FBG_FIRST_TRANSACTION_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_LAST_TRANSACTION_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_CASINO_MIN_BET_AMOUNT" COMMENT $$$$, 
  
    "FBG_CASINO_MAX_BET_AMOUNT" COMMENT $$$$, 
  
    "FBG_CASINO_NUMBER_BETS_PLACED" COMMENT $$$$, 
  
    "FBG_CASINO_FIRST_BET_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_CASINO_LAST_BET_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_ONLINE_SPORTSBOOK_MIN_BET_AMOUNT" COMMENT $$$$, 
  
    "FBG_ONLINE_SPORTSBOOK_MAX_BET_AMOUNT" COMMENT $$$$, 
  
    "FBG_ONLINE_SPORTSBOOK_NUMBER_BETS_PLACED" COMMENT $$$$, 
  
    "FBG_ONLINE_SPORTSBOOK_FIRST_BET_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_ONLINE_SPORTSBOOK_LAST_BET_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_RETAIL_SPORTSBOOK_MIN_BET_AMOUNT" COMMENT $$$$, 
  
    "FBG_RETAIL_SPORTSBOOK_MAX_BET_AMOUNT" COMMENT $$$$, 
  
    "FBG_RETAIL_SPORTSBOOK_NUMBER_BETS_PLACED" COMMENT $$$$, 
  
    "FBG_RETAIL_SPORTSBOOK_FIRST_BET_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_RETAIL_SPORTSBOOK_LAST_BET_TIMESTAMP" COMMENT $$$$, 
  
    "FBG_PREFERENCE_NFL" COMMENT $$$$, 
  
    "FBG_PREFERENCE_NCAA" COMMENT $$$$, 
  
    "FBG_PREFERENCE_NBA" COMMENT $$$$, 
  
    "FBG_PREFERENCE_NHL" COMMENT $$$$, 
  
    "FBG_PREFERENCE_MLB" COMMENT $$$$, 
  
    "FBG_PREFERENCE_NFL_TEAMS" COMMENT $$$$, 
  
    "FBG_PREFERENCE_NCAA_TEAMS" COMMENT $$$$, 
  
    "FBG_PREFERENCE_NBA_TEAMS" COMMENT $$$$, 
  
    "FBG_PREFERENCE_NHL_TEAMS" COMMENT $$$$, 
  
    "FBG_PREFERENCE_MLB_TEAMS" COMMENT $$$$, 
  
    "FBG_XSELL_VIEWS" COMMENT $$$$, 
  
    "FBG_XSELL_CLICKS" COMMENT $$$$, 
  
    "LIVE_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "LIVE_TRANSACTION_COUNT" COMMENT $$$$, 
  
    "LIVE_FIRST_ORDER_TIMESTAMP" COMMENT $$$$, 
  
    "LIVE_LAST_ORDER_TIMESTAMP" COMMENT $$$$, 
  
    "LIVE_TOTAL_REVENUE" COMMENT $$$$, 
  
    "LIVE_TOTAL_GMS" COMMENT $$$$, 
  
    "LIVE_TOTAL_TAX" COMMENT $$$$, 
  
    "LIVE_TOTAL_SHIPPING" COMMENT $$$$, 
  
    "LIVE_GIVEAWAY_COUNT" COMMENT $$$$, 
  
    "LIVE_REFUND_COUNT" COMMENT $$$$, 
  
    "LIVE_TOTAL_SPOTS_PURCHASED" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_EMAIL" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_LAST_ACTIVITY_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_LAST_ACTIVITY_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_LAST_ACTIVITY_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_LAST_ACTIVITY_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_LAST_ACTIVITY_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_USERNAME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_EMAIL_OPT_IN" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_SPEND_COHORT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_SPEND_COHORT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_SPEND_COHORT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_SPEND_COHORT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_SPEND_COHORT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_SPEND_AMOUNT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_SPEND_AMOUNT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_SPEND_AMOUNT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_SPEND_AMOUNT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_SPEND_AMOUNT_LIFETIME" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_COINS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_COINS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_COINS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_COINS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_COINS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_GEMS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_GEMS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_GEMS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_GEMS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_GEMS_BALANCE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_CITY" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STATE" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_COUNTRY" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_PURCHASES_USD" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_PURCHASES_USD" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_PURCHASES_USD" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_PURCHASES_USD" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_PURCHASES_USD" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_PURCHASES_USD_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_PURCHASES_USD_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_PURCHASES_USD_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_PURCHASES_USD_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_PURCHASES_USD_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_PURCHASES_PREMIUM_GEM" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_PURCHASES_PREMIUM_GEM" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_PURCHASES_PREMIUM_GEM" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_PURCHASES_PREMIUM_GEM" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_PURCHASES_PREMIUM_GEM" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_PURCHASES_PREMIUM_GEM_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_PURCHASES_PREMIUM_GEM_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_PURCHASES_PREMIUM_GEM_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_PURCHASES_PREMIUM_GEM_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_PURCHASES_PREMIUM_GEM_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_FREEMIUM_SOFT_COIN" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_FREEMIUM_SOFT_COIN" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_FREEMIUM_SOFT_COIN" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_FREEMIUM_SOFT_COIN" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_FREEMIUM_SOFT_COIN" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_STARWARS_FREEMIUM_SOFT_COIN_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_MARVEL_FREEMIUM_SOFT_COIN_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_DISNEY_FREEMIUM_SOFT_COIN_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_WWE_FREEMIUM_SOFT_COIN_COUNT" COMMENT $$$$, 
  
    "TOPPS_DIGITAL_BASEBALL_FREEMIUM_SOFT_COIN_COUNT" COMMENT $$$$, 
  
    "TOPPS_COM_EMAIL" COMMENT $$$$, 
  
    "TOPPS_COM_LEGACY_CUSTOMER_IDS" COMMENT $$$$, 
  
    "TOPPS_COM_CREATED_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_COM_UPDATED_TIMESTAMP" COMMENT $$$$, 
  
    "TOPPS_COM_FIRST_NAME" COMMENT $$$$, 
  
    "TOPPS_COM_LAST_NAME" COMMENT $$$$, 
  
    "TOPPS_COM_DOB" COMMENT $$$$, 
  
    "TOPPS_COM_PHONE" COMMENT $$$$, 
  
    "TOPPS_COM_BILLING_ADDRESS1" COMMENT $$$$, 
  
    "TOPPS_COM_BILLING_ADDRESS2" COMMENT $$$$, 
  
    "TOPPS_COM_BILLING_CITY" COMMENT $$$$, 
  
    "TOPPS_COM_BILLING_ZIP" COMMENT $$$$, 
  
    "TOPPS_COM_BILLING_REGION" COMMENT $$$$, 
  
    "TOPPS_COM_BILLING_COUNTRY" COMMENT $$$$, 
  
    "TOPPS_COM_ORDER_FIRST_DATE" COMMENT $$$$, 
  
    "TOPPS_COM_ORDER_LAST_DATE" COMMENT $$$$, 
  
    "TOPPS_COM_GMV_TOTAL" COMMENT $$$$, 
  
    "TOPPS_COM_SHIPPING_TOTAL" COMMENT $$$$, 
  
    "TOPPS_COM_GROSS_TOTAL" COMMENT $$$$, 
  
    "TOPPS_COM_NET_TOTAL" COMMENT $$$$, 
  
    "EVENTS_CUSTOMER_ID" COMMENT $$$$, 
  
    "EVENTS_EMAIL" COMMENT $$$$, 
  
    "EVENTS_PHONE" COMMENT $$$$, 
  
    "EVENTS_FIRST_NAME" COMMENT $$$$, 
  
    "EVENTS_LAST_NAME" COMMENT $$$$, 
  
    "EVENTS_ADDRESS_1" COMMENT $$$$, 
  
    "EVENTS_ADDRESS_2" COMMENT $$$$, 
  
    "EVENTS_CITY" COMMENT $$$$, 
  
    "EVENTS_STATE" COMMENT $$$$, 
  
    "EVENTS_ZIP" COMMENT $$$$, 
  
    "EVENTS_COUNTRY" COMMENT $$$$, 
  
    "EVENTS_MARKETING_OPT_IN" COMMENT $$$$, 
  
    "EVENTS_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "EVENTS_ORDER_COUNT" COMMENT $$$$, 
  
    "EVENTS_ORDER_AMOUNT_TOTAL" COMMENT $$$$, 
  
    "EVENTS_TOTAL_TICKETS_PURCHASED" COMMENT $$$$, 
  
    "EVENTS_TOTAL_EVENTS_ATTENDED" COMMENT $$$$, 
  
    "EVENTS_FANFEST_ATTENDEE" COMMENT $$$$, 
  
    "EVENTS_WWE_ATTENDEE" COMMENT $$$$, 
  
    "COLLECT_TENANT_FAN_ID" COMMENT $$$$, 
  
    "COLLECT_USER_ID" COMMENT $$$$, 
  
    "COLLECT_FIRST_NAME" COMMENT $$$$, 
  
    "COLLECT_LAST_NAME" COMMENT $$$$, 
  
    "COLLECT_STATE" COMMENT $$$$, 
  
    "COLLECT_COUNTRY" COMMENT $$$$, 
  
    "COLLECT_EMAIL" COMMENT $$$$, 
  
    "COLLECT_PHONE" COMMENT $$$$, 
  
    "COLLECT_IS_FROZEN" COMMENT $$$$, 
  
    "COLLECT_ACCOUNT_CREATION_TIMESTAMP" COMMENT $$$$, 
  
    "COLLECT_LAST_ACTIVE_TIMESTAMP" COMMENT $$$$, 
  
    "COLLECT_EMAIL_OPT_IN" COMMENT $$$$, 
  
    "COLLECT_SMS_OPT_IN" COMMENT $$$$, 
  
    "COLLECT_PUSH_OPT_IN" COMMENT $$$$, 
  
    "COLLECT_FIRST_BID_TIMESTAMP" COMMENT $$$$, 
  
    "COLLECT_FIRST_PURCHASED_TIMESTAMP" COMMENT $$$$, 
  
    "COLLECT_FIRST_LISTED_AT_TIMESTAMP" COMMENT $$$$, 
  
    "COLLECT_LAST_LISTED_AT_TIMESTAMP" COMMENT $$$$, 
  
    "COLLECT_FIRST_SOLD_AT_TIMESTAMP" COMMENT $$$$, 
  
    "COLLECT_LAST_SOLD_AT_TIMESTAMP" COMMENT $$$$, 
  
    "COLLECT_TOTAL_LISTINGS" COMMENT $$$$, 
  
    "COLLECT_TOTAL_SALES" COMMENT $$$$, 
  
    "COLLECT_TOTAL_PAID" COMMENT $$$$, 
  
    "COLLECT_TOTAL_GMV_SOLD" COMMENT $$$$, 
  
    "COLLECT_TOTAL_REVENUE_SOLD" COMMENT $$$$, 
  
    "COLLECT_REVENUE_LIFETIME" COMMENT $$$$, 
  
    "COLLECT_GMV_LIFETIME" COMMENT $$$$, 
  
    "COLLECT_ORDERS_LIFETIME" COMMENT $$$$, 
  
    "COLLECT_ITEMS_PURCHASED_LIFETIME" COMMENT $$$$, 
  
    "COLLECT_VAULT_TOTAL_SUBMISSIONS" COMMENT $$$$, 
  
    "COLLECT_TOTAL_NUMBER_OF_ITEMS_IN_VAULT" COMMENT $$$$, 
  
    "COLLECT_TOTAL_VALUE_OF_ITEMS_IN_VAULT" COMMENT $$$$, 
  
    "AAIA_ID" COMMENT $$$$, 
  
    "AAIA_HOUSEHOLD_ID" COMMENT $$$$, 
  
    "AAIA_FIRST_NAME" COMMENT $$$$, 
  
    "AAIA_LAST_NAME" COMMENT $$$$, 
  
    "AAIA_EMAIL" COMMENT $$$$, 
  
    "AAIA_PHONE" COMMENT $$$$, 
  
    "AAIA_ADDRESS" COMMENT $$$$, 
  
    "AAIA_ADDR_STREET" COMMENT $$$$, 
  
    "AAIA_CITY" COMMENT $$$$, 
  
    "AAIA_STATE" COMMENT $$$$, 
  
    "AAIA_ZIP" COMMENT $$$$, 
  
    "AAIA_AUTO_RACING_AFFINITY" COMMENT $$$$, 
  
    "AAIA_BASEBALL_AFFINITY" COMMENT $$$$, 
  
    "AAIA_BASKETBALL_AFFINITY" COMMENT $$$$, 
  
    "AAIA_FOOTBALL_AFFINITY" COMMENT $$$$, 
  
    "AAIA_GAMBLING_AFFINITY" COMMENT $$$$, 
  
    "AAIA_GAMES_AFFINITY" COMMENT $$$$, 
  
    "AAIA_GOLF_AFFINITY" COMMENT $$$$, 
  
    "AAIA_GOLF" COMMENT $$$$, 
  
    "AAIA_HOCKEY_AFFINITY" COMMENT $$$$, 
  
    "AAIA_HOCKEY" COMMENT $$$$, 
  
    "AAIA_TENNIS_AFFINITY" COMMENT $$$$, 
  
    "AAIA_TENNIS" COMMENT $$$$, 
  
    "AAIA_SOCCER_AFFINITY" COMMENT $$$$, 
  
    "AAIA_SOCCER" COMMENT $$$$, 
  
    "AAIA_AGE" COMMENT $$$$, 
  
    "AAIA_GENDER" COMMENT $$$$, 
  
    "AAIA_INCOME_HH" COMMENT $$$$, 
  
    "AAIA_INCOME_LEVELS" COMMENT $$$$, 
  
    "AAIA_INCOME_MIDPTS_HH" COMMENT $$$$, 
  
    "AAIA_INVESTMENT_TYPE" COMMENT $$$$, 
  
    "AAIA_MEDIAN_INCOME" COMMENT $$$$, 
  
    "AAIA_NET_WORTH_HH" COMMENT $$$$, 
  
    "AAIA_NET_WORTH_MIDPT_HH" COMMENT $$$$, 
  
    "AAIA_OWNS_INVESTMENTS" COMMENT $$$$, 
  
    "AAIA_OWNS_STOCKS_AND_BONDS" COMMENT $$$$, 
  
    "AAIA_PREMIUM_CARD" COMMENT $$$$, 
  
    "AAIA_PREMIUM_INCOME_HH" COMMENT $$$$, 
  
    "AAIA_PREMIUM_INCOME_MIDPT_HH" COMMENT $$$$, 
  
    "AAIA_BASEBALL" COMMENT $$$$, 
  
    "AAIA_BASKETBALL" COMMENT $$$$, 
  
    "AAIA_FOOTBALL" COMMENT $$$$, 
  
    "AAIA_GAMBLING" COMMENT $$$$, 
  
    "AAIA_READING_SPORTS" COMMENT $$$$, 
  
    "AAIA_COLLECTIBLES_PURCHASES_TOTAL_CO" COMMENT $$$$, 
  
    "AAIA_SPORTS_PURCHASES_TOTAL_CO" COMMENT $$$$, 
  
    "SALESFORCE_LEAD_ID_FBG" COMMENT $$$$, 
  
    "SALESFORCE_CONTACT_ID_FBG" COMMENT $$$$, 
  
    "SALESFORCE_IS_DELETED_LEAD_FBG" COMMENT $$$$, 
  
    "SALESFORCE_IS_DELETED_ACCOUNT_FBG" COMMENT $$$$, 
  
    "SALESFORCE_CONTACT_ID_VIP" COMMENT $$$$, 
  
    "SALESFORCE_CONTACT_ID_VIP_TYPE" COMMENT $$$$, 
  
    "SALESFORCE_MEMBER_ID_VIP" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_NFL" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_NCAA" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_NBA" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_NHL" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_MLB" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_NFL_TEAMS" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_NCAA_TEAMS" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_NBA_TEAMS" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_NHL_TEAMS" COMMENT $$$$, 
  
    "SALESFORCE_PREFERENCE_MLB_TEAMS" COMMENT $$$$, 
  
    "FANAPP_CHALLENGE_COMPONENT_VIEWS" COMMENT $$$$, 
  
    "FANAPP_NFL_CAROUSEL_CLICKED_ALL_TIME" COMMENT $$$$, 
  
    "FANAPP_NFL_CAROUSEL_CLICKED_L30_DAYS" COMMENT $$$$, 
  
    "FANAPP_MLB_CAROUSEL_CLICKED_ALL_TIME" COMMENT $$$$, 
  
    "FANAPP_MLB_CAROUSEL_CLICKED_L30_DAYS" COMMENT $$$$, 
  
    "FANAPP_NCAA_CAROUSEL_CLICKED_ALL_TIME" COMMENT $$$$, 
  
    "FANAPP_NCAA_CAROUSEL_CLICKED_L30_DAYS" COMMENT $$$$, 
  
    "FANAPP_NBA_CAROUSEL_CLICKED_ALL_TIME" COMMENT $$$$, 
  
    "FANAPP_NBA_CAROUSEL_CLICKED_L30_DAYS" COMMENT $$$$, 
  
    "FANAPP_NHL_CAROUSEL_CLICKED_ALL_TIME" COMMENT $$$$, 
  
    "FANAPP_NHL_CAROUSEL_CLICKED_L30_DAYS" COMMENT $$$$, 
  
    "FANAPP_WWE_CAROUSEL_CLICKED_ALL_TIME" COMMENT $$$$, 
  
    "FANAPP_WWE_CAROUSEL_CLICKED_L30_DAYS" COMMENT $$$$, 
  
    "FANAPP_SOCCER_CAROUSEL_CLICKED_ALL_TIME" COMMENT $$$$, 
  
    "FANAPP_SOCCER_CAROUSEL_CLICKED_L30_DAYS" COMMENT $$$$, 
  
    "SNAPSHOT_TS" COMMENT $$$$
  
)

   as (
    SELECT
    *,
    current_timestamp AS snapshot_ts
FROM fangraph_dev.admin.fangraph
  )
/* {"app": "dbt", "dbt_snowflake_query_tags_version": "2.5.0", "dbt_version": "1.8.7", "project_name": "fes_data", "target_name": "dev", "target_database": "FDE_DEV", "target_schema": "FDE_STAGE", "invocation_id": "4da07dc3-e2f1-44d1-a315-46ab6ea0b58f", "run_started_at": "2026-04-09T20:49:10.366178+00:00", "full_refresh": false, "which": "run", "node_name": "fangraph_snapshots", "node_alias": "fangraph_snapshots", "node_package_name": "fes_data", "node_original_file_path": "models/fangraph/fangraph/fangraph_snapshots.sql", "node_database": "fangraph_dev", "node_schema": "admin", "node_id": "model.fes_data.fangraph_snapshots", "node_resource_type": "model", "node_meta": {}, "node_tags": ["fangraph"], "invocation_command": "dbt run -m fangraph", "node_refs": [], "materialized": "incremental", "raw_code_hash": "62e17f0406b30af34fb805fd97cac954"} */;
