-- Query ID: 01c399f1-0112-65b6-0000-e307218a3a8a
-- Database: FDE_DEV
-- Schema: FDE_STAGE
-- Warehouse: FDE_DEVELOPER_XL_WH
-- Executed: 2026-04-09T21:05:16.947000+00:00
-- Elapsed: 10312ms
-- Environment: FES

merge into fangraph_dev.private_fan_id.pfi_fanatics_one_attributes as DBT_INTERNAL_DEST
        using fangraph_dev.private_fan_id.pfi_fanatics_one_attributes__dbt_tmp as DBT_INTERNAL_SOURCE
        on (
                DBT_INTERNAL_SOURCE.private_fan_id = DBT_INTERNAL_DEST.private_fan_id
            )

    
    when matched then update set
        "PRIVATE_FAN_ID" = DBT_INTERNAL_SOURCE."PRIVATE_FAN_ID","USER_LAST_TXN_TS_UTC" = DBT_INTERNAL_SOURCE."USER_LAST_TXN_TS_UTC","LOYALTY_TIER" = DBT_INTERNAL_SOURCE."LOYALTY_TIER","POINTS_TIER" = DBT_INTERNAL_SOURCE."POINTS_TIER","POINTS_TIER_RANK" = DBT_INTERNAL_SOURCE."POINTS_TIER_RANK","AMOUNTS_TO_NEXT_POINTS_TIER" = DBT_INTERNAL_SOURCE."AMOUNTS_TO_NEXT_POINTS_TIER","STATUS_MATCH_ACTIVE" = DBT_INTERNAL_SOURCE."STATUS_MATCH_ACTIVE","CURRENT_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."CURRENT_YEAR_TIER_POINTS","POINTS_TIER_NUMBER" = DBT_INTERNAL_SOURCE."POINTS_TIER_NUMBER","PRIOR_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."PRIOR_YEAR_TIER_POINTS","ROLLOVER_TP" = DBT_INTERNAL_SOURCE."ROLLOVER_TP","OSB_CURRENT_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."OSB_CURRENT_YEAR_TIER_POINTS","OC_CURRENT_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."OC_CURRENT_YEAR_TIER_POINTS","COMMERCE_CURRENT_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."COMMERCE_CURRENT_YEAR_TIER_POINTS","FBG_GOODWILL_CURRENT_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."FBG_GOODWILL_CURRENT_YEAR_TIER_POINTS","TLC_CURRENT_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."TLC_CURRENT_YEAR_TIER_POINTS","FBG_CURRENT_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."FBG_CURRENT_YEAR_TIER_POINTS","OTHER_CURRENT_YEAR_TIER_POINTS" = DBT_INTERNAL_SOURCE."OTHER_CURRENT_YEAR_TIER_POINTS","VOIDED_TP" = DBT_INTERNAL_SOURCE."VOIDED_TP","CURRENT_FC_BALANCE" = DBT_INTERNAL_SOURCE."CURRENT_FC_BALANCE","BASE_FC_EXPIRATION" = DBT_INTERNAL_SOURCE."BASE_FC_EXPIRATION","UNCLAIMED_BONUS_FC" = DBT_INTERNAL_SOURCE."UNCLAIMED_BONUS_FC","TOTAL_OUSTANDING_FC_BALANCE" = DBT_INTERNAL_SOURCE."TOTAL_OUSTANDING_FC_BALANCE","FANCASH_UPDATED_TIMESTAMP" = DBT_INTERNAL_SOURCE."FANCASH_UPDATED_TIMESTAMP","_UPDATE_TS" = DBT_INTERNAL_SOURCE."_UPDATE_TS"
    

    when not matched then insert
        ("PRIVATE_FAN_ID", "USER_LAST_TXN_TS_UTC", "LOYALTY_TIER", "POINTS_TIER", "POINTS_TIER_RANK", "AMOUNTS_TO_NEXT_POINTS_TIER", "STATUS_MATCH_ACTIVE", "CURRENT_YEAR_TIER_POINTS", "POINTS_TIER_NUMBER", "PRIOR_YEAR_TIER_POINTS", "ROLLOVER_TP", "OSB_CURRENT_YEAR_TIER_POINTS", "OC_CURRENT_YEAR_TIER_POINTS", "COMMERCE_CURRENT_YEAR_TIER_POINTS", "FBG_GOODWILL_CURRENT_YEAR_TIER_POINTS", "TLC_CURRENT_YEAR_TIER_POINTS", "FBG_CURRENT_YEAR_TIER_POINTS", "OTHER_CURRENT_YEAR_TIER_POINTS", "VOIDED_TP", "CURRENT_FC_BALANCE", "BASE_FC_EXPIRATION", "UNCLAIMED_BONUS_FC", "TOTAL_OUSTANDING_FC_BALANCE", "FANCASH_UPDATED_TIMESTAMP", "_INSERT_TS", "_UPDATE_TS")
    values
        ("PRIVATE_FAN_ID", "USER_LAST_TXN_TS_UTC", "LOYALTY_TIER", "POINTS_TIER", "POINTS_TIER_RANK", "AMOUNTS_TO_NEXT_POINTS_TIER", "STATUS_MATCH_ACTIVE", "CURRENT_YEAR_TIER_POINTS", "POINTS_TIER_NUMBER", "PRIOR_YEAR_TIER_POINTS", "ROLLOVER_TP", "OSB_CURRENT_YEAR_TIER_POINTS", "OC_CURRENT_YEAR_TIER_POINTS", "COMMERCE_CURRENT_YEAR_TIER_POINTS", "FBG_GOODWILL_CURRENT_YEAR_TIER_POINTS", "TLC_CURRENT_YEAR_TIER_POINTS", "FBG_CURRENT_YEAR_TIER_POINTS", "OTHER_CURRENT_YEAR_TIER_POINTS", "VOIDED_TP", "CURRENT_FC_BALANCE", "BASE_FC_EXPIRATION", "UNCLAIMED_BONUS_FC", "TOTAL_OUSTANDING_FC_BALANCE", "FANCASH_UPDATED_TIMESTAMP", "_INSERT_TS", "_UPDATE_TS")


/* {"app": "dbt", "dbt_snowflake_query_tags_version": "2.5.0", "dbt_version": "1.8.7", "project_name": "fes_data", "target_name": "dev", "target_database": "FDE_DEV", "target_schema": "FDE_STAGE", "invocation_id": "4da07dc3-e2f1-44d1-a315-46ab6ea0b58f", "run_started_at": "2026-04-09T20:49:10.366178+00:00", "full_refresh": false, "which": "run", "node_name": "pfi_fanatics_one_attributes", "node_alias": "pfi_fanatics_one_attributes", "node_package_name": "fes_data", "node_original_file_path": "models/fangraph/private_fan_id/pfi_fanatics_one_attributes.sql", "node_database": "fangraph_dev", "node_schema": "private_fan_id", "node_id": "model.fes_data.pfi_fanatics_one_attributes", "node_resource_type": "model", "node_meta": {}, "node_tags": ["fangraph"], "invocation_command": "dbt run -m fangraph", "node_refs": ["tier_points_ledger_v2", "pfi_tenant_id_mapping", "loyalty_balance"], "materialized": "incremental", "raw_code_hash": "9b8b3d2e8a7922f6d69f71c99b53fd41"} */;
