-- Query ID: 01c39a21-0112-6ccc-0000-e307218bd816
-- Database: FDE_DEV
-- Schema: FDE_STAGE
-- Warehouse: FDE_DEVELOPER_XL_WH
-- Executed: 2026-04-09T21:53:06.917000+00:00
-- Elapsed: 890ms
-- Environment: FES

merge into fangraph_dev.topps_digital.dim_topps_digital_purchase as DBT_INTERNAL_DEST
        using fangraph_dev.topps_digital.dim_topps_digital_purchase__dbt_tmp as DBT_INTERNAL_SOURCE
        on (
                    DBT_INTERNAL_SOURCE.purchase_key = DBT_INTERNAL_DEST.purchase_key
                )

    
    when matched then update set
        "FANGRAPH_ID" = DBT_INTERNAL_SOURCE."FANGRAPH_ID","TOPPS_DIGITAL_USER_ID" = DBT_INTERNAL_SOURCE."TOPPS_DIGITAL_USER_ID","USER_NAME" = DBT_INTERNAL_SOURCE."USER_NAME","APP_NAME" = DBT_INTERNAL_SOURCE."APP_NAME","USER_PROFILE_KEY" = DBT_INTERNAL_SOURCE."USER_PROFILE_KEY","PURCHASE_KEY" = DBT_INTERNAL_SOURCE."PURCHASE_KEY","STORE_PRODUCT_KEY" = DBT_INTERNAL_SOURCE."STORE_PRODUCT_KEY","STORE_ITEM_KEY" = DBT_INTERNAL_SOURCE."STORE_ITEM_KEY","PURCHASE_TS" = DBT_INTERNAL_SOURCE."PURCHASE_TS","PRODUCT_RELEASE_DT" = DBT_INTERNAL_SOURCE."PRODUCT_RELEASE_DT","PRODUCT_EXPIRES_DT" = DBT_INTERNAL_SOURCE."PRODUCT_EXPIRES_DT","PRODUCT_INTERNAL_NAME" = DBT_INTERNAL_SOURCE."PRODUCT_INTERNAL_NAME","STORE_ITEM_NAME" = DBT_INTERNAL_SOURCE."STORE_ITEM_NAME","STORE_ITEM_REDEEMABLE_CATEGORY" = DBT_INTERNAL_SOURCE."STORE_ITEM_REDEEMABLE_CATEGORY","IS_SINGLE_DAY_RELEASE_PRODUCT" = DBT_INTERNAL_SOURCE."IS_SINGLE_DAY_RELEASE_PRODUCT","OS" = DBT_INTERNAL_SOURCE."OS","USD_PURCHASES" = DBT_INTERNAL_SOURCE."USD_PURCHASES","USD_PURCHASE_AMOUNT" = DBT_INTERNAL_SOURCE."USD_PURCHASE_AMOUNT","GEM_PURCHASES" = DBT_INTERNAL_SOURCE."GEM_PURCHASES","GEM_PURCHASE_AMOUNT" = DBT_INTERNAL_SOURCE."GEM_PURCHASE_AMOUNT","COIN_PURCHASES" = DBT_INTERNAL_SOURCE."COIN_PURCHASES","COIN_PURCHASE_AMOUNT" = DBT_INTERNAL_SOURCE."COIN_PURCHASE_AMOUNT","REDEEMABLE_GEMS" = DBT_INTERNAL_SOURCE."REDEEMABLE_GEMS","REDEEMABLE_COINS" = DBT_INTERNAL_SOURCE."REDEEMABLE_COINS","REDEEMABLE_PACKS" = DBT_INTERNAL_SOURCE."REDEEMABLE_PACKS","REDEEMABLE_COLLECTIBLES" = DBT_INTERNAL_SOURCE."REDEEMABLE_COLLECTIBLES","STORE_ITEM_PACK_NON_BASE_COLLECTIBLES_AVAILABLE" = DBT_INTERNAL_SOURCE."STORE_ITEM_PACK_NON_BASE_COLLECTIBLES_AVAILABLE","_UPDATE_TS" = DBT_INTERNAL_SOURCE."_UPDATE_TS"
    

    when not matched then insert
        ("FANGRAPH_ID", "TOPPS_DIGITAL_USER_ID", "USER_NAME", "APP_NAME", "USER_PROFILE_KEY", "PURCHASE_KEY", "STORE_PRODUCT_KEY", "STORE_ITEM_KEY", "PURCHASE_TS", "PRODUCT_RELEASE_DT", "PRODUCT_EXPIRES_DT", "PRODUCT_INTERNAL_NAME", "STORE_ITEM_NAME", "STORE_ITEM_REDEEMABLE_CATEGORY", "IS_SINGLE_DAY_RELEASE_PRODUCT", "OS", "USD_PURCHASES", "USD_PURCHASE_AMOUNT", "GEM_PURCHASES", "GEM_PURCHASE_AMOUNT", "COIN_PURCHASES", "COIN_PURCHASE_AMOUNT", "REDEEMABLE_GEMS", "REDEEMABLE_COINS", "REDEEMABLE_PACKS", "REDEEMABLE_COLLECTIBLES", "STORE_ITEM_PACK_NON_BASE_COLLECTIBLES_AVAILABLE", "_INSERT_TS", "_UPDATE_TS")
    values
        ("FANGRAPH_ID", "TOPPS_DIGITAL_USER_ID", "USER_NAME", "APP_NAME", "USER_PROFILE_KEY", "PURCHASE_KEY", "STORE_PRODUCT_KEY", "STORE_ITEM_KEY", "PURCHASE_TS", "PRODUCT_RELEASE_DT", "PRODUCT_EXPIRES_DT", "PRODUCT_INTERNAL_NAME", "STORE_ITEM_NAME", "STORE_ITEM_REDEEMABLE_CATEGORY", "IS_SINGLE_DAY_RELEASE_PRODUCT", "OS", "USD_PURCHASES", "USD_PURCHASE_AMOUNT", "GEM_PURCHASES", "GEM_PURCHASE_AMOUNT", "COIN_PURCHASES", "COIN_PURCHASE_AMOUNT", "REDEEMABLE_GEMS", "REDEEMABLE_COINS", "REDEEMABLE_PACKS", "REDEEMABLE_COLLECTIBLES", "STORE_ITEM_PACK_NON_BASE_COLLECTIBLES_AVAILABLE", "_INSERT_TS", "_UPDATE_TS")


/* {"app": "dbt", "dbt_snowflake_query_tags_version": "2.5.0", "dbt_version": "1.8.7", "project_name": "fes_data", "target_name": "dev", "target_database": "FDE_DEV", "target_schema": "FDE_STAGE", "invocation_id": "4da07dc3-e2f1-44d1-a315-46ab6ea0b58f", "run_started_at": "2026-04-09T20:49:10.366178+00:00", "full_refresh": false, "which": "run", "node_name": "dim_topps_digital_purchase", "node_alias": "dim_topps_digital_purchase", "node_package_name": "fes_data", "node_original_file_path": "models/fangraph/dim/dim_topps_digital_purchase.sql", "node_database": "fangraph_dev", "node_schema": "topps_digital", "node_id": "model.fes_data.dim_topps_digital_purchase", "node_resource_type": "model", "node_meta": {}, "node_tags": ["fangraph"], "invocation_command": "dbt run -m fangraph", "node_refs": ["fangraph_id_final"], "materialized": "incremental", "raw_code_hash": "aa0e2708d9c3d90bf4960b5c961ab5a9"} */;
