-- Query ID: 01c39a56-0212-67a9-24dd-07031948155f
-- Database: FBG_GOVERNANCE
-- Schema: unknown
-- Warehouse: TABLEAU_M_PROD
-- Last Executed: 2026-04-09T22:46:52.547000+00:00
-- Elapsed: 3271ms
-- Run Count: 3
-- Environment: FBG

SELECT "Custom SQL Query"."ACCOUNT_AGE_DAYS" AS "ACCOUNT_AGE_DAYS",
  CAST("Custom SQL Query"."ACCO_ID" AS TEXT) AS "ACCO_ID",
  "Custom SQL Query"."AUDIT_NOTE" AS "AUDIT_NOTE",
  "Custom SQL Query"."AUDIT_NOTE_DATE" AS "AUDIT_NOTE_DATE",
  "Custom SQL Query"."CASHOUT_CT" AS "CASHOUT_CT",
  "Custom SQL Query"."CASHOUT_PCT" AS "CASHOUT_PCT",
  "Custom SQL Query"."DEP_TURNOVER" AS "DEP_TURNOVER",
  "Custom SQL Query"."DEVICE_UUID" AS "DEVICE_UUID",
  "Custom SQL Query"."GEOLOCATION_CT" AS "GEOLOCATION_CT",
  "Custom SQL Query"."IP_ADDRESS" AS "IP_ADDRESS",
  "Custom SQL Query"."LAST_GEOLOCATION" AS "LAST_GEOLOCATION",
  "Custom SQL Query"."LATEST_MANUAL_WD_DATE" AS "LATEST_MANUAL_WD_DATE",
  "Custom SQL Query"."LATEST_TRANS_DATE" AS "LATEST_TRANS_DATE",
  "Custom SQL Query"."LT_DEPOSIT_AMT" AS "LT_DEPOSIT_AMT",
  "Custom SQL Query"."OSB_SHORT_BET_CT" AS "OSB_SHORT_BET_CT",
  "Custom SQL Query"."PAYMENT_BRAND" AS "PAYMENT_BRAND",
  "Custom SQL Query"."PB_MIGRATED" AS "PB_MIGRATED",
  "Custom SQL Query"."SD_ACCO_ID" AS "SD_ACCO_ID",
  "Custom SQL Query"."SD_GEOLOCATION_CT" AS "SD_GEOLOCATION_CT",
  "Custom SQL Query"."SD_LAST_GEOLOCATION" AS "SD_LAST_GEOLOCATION",
  "Custom SQL Query"."SD_STATUS" AS "SD_STATUS",
  "Custom SQL Query"."SD_TOTAL_CT" AS "SD_TOTAL_CT",
  "Custom SQL Query"."STATUS" AS "STATUS",
  "Custom SQL Query"."TEST" AS "TEST",
  "Custom SQL Query"."TOTAL_CT" AS "TOTAL_CT",
  "Custom SQL Query"."VIP" AS "VIP",
  CAST("Custom SQL Query"."WD_METHOD_AGE_DAYS" AS TEXT) AS "WD_METHOD_AGE_DAYS"
FROM (
  SELECT *
  FROM FBG_GOVERNANCE.GOVERNANCE.WITHDRAWAL_REVIEW_MASTER
) "Custom SQL Query"
