-- Query ID: 01c39a64-0112-6bf9-0000-e307218da7ee
-- Database: AAIA
-- Schema: unknown
-- Warehouse: FDE_LOYALTY_ANALYST_LG_WH
-- Last Executed: 2026-04-09T23:00:58.344000+00:00
-- Elapsed: 12208ms
-- Run Count: 2
-- Environment: FES

SELECT
    QUERY_ID,
    QUERY_TEXT,
    DATABASE_NAME,
    SCHEMA_NAME,
    WAREHOUSE_NAME,
    START_TIME,
    EXECUTION_STATUS,
    TOTAL_ELAPSED_TIME
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
    RESULT_LIMIT => 10000
))
WHERE EXECUTION_STATUS = 'SUCCESS'
  AND QUERY_TYPE IN ('SELECT', 'CREATE_TABLE_AS_SELECT', 'INSERT', 'MERGE', 'UPDATE', 'DELETE', 'CREATE_TABLE', 'CREATE_VIEW')
  AND (QUERY_TAG IS NULL OR QUERY_TAG = '')
ORDER BY START_TIME DESC
