-- Query ID: 01c39a0c-0112-6806-0000-e307218b6746
-- Database: USER$TKUNKEL@FANATICSINC.COM
-- Schema: PUBLIC
-- Warehouse: FDE_FES_ANALYST_XL_WH
-- Executed: 2026-04-09T21:32:28.605000+00:00
-- Elapsed: 43733ms
-- Environment: FES

WITH base AS (
    SELECT
        CLIENT_CUSTOMER_ID AS FANGRAPH_ID,
        TRIM(AUDIENCE_NAME) AS AUDIENCE_NAME
    FROM GROWTHLOOP.FLYWHEEL_SYSTEM.SNAPSHOTTING_LATEST_SNAPSHOTS
    WHERE TRIM(AUDIENCE_NAME) IN (
        'FAN_League_NHL_T2',
        'FAN_League_NFL_T2',
        'FAN_League_MLB_T2',
        'FAN_League_NBA_T2',
        'FAN_League_NCAA_T2',
        'FAN_League_CombatSports_T1',
        'FAN_AllFans_T1'
    )
),
with_demos AS (
    SELECT
        b.FANGRAPH_ID,
        b.AUDIENCE_NAME,
        CASE
            WHEN aa.AGE BETWEEN 18 AND 20 THEN '18-20'
            WHEN aa.AGE BETWEEN 21 AND 30 THEN '21-30'
            WHEN aa.AGE BETWEEN 31 AND 40 THEN '31-40'
            WHEN aa.AGE BETWEEN 41 AND 50 THEN '41-50'
            WHEN aa.AGE BETWEEN 51 AND 60 THEN '51-60'
            WHEN aa.AGE BETWEEN 61 AND 70 THEN '61-70'
            WHEN aa.AGE BETWEEN 71 AND 80 THEN '71-80'
            WHEN aa.AGE > 80 THEN '80+'
        END AS AGE_BUCKET,
        fg.FANGRAPH_GENDER AS GENDER,
        aa.INCOME_HH
    FROM base b
    LEFT JOIN FANGRAPH.AAIA.AAIA_ID_LKP lkp
        ON lkp.FANGRAPH_ID = b.FANGRAPH_ID
    LEFT JOIN FANGRAPH.AAIA.AUDIENCE_ACUITY aa
        ON aa.ID = lkp.AAIA_ID
    LEFT JOIN FANGRAPH.ADMIN.FANGRAPH fg
        ON fg.FANGRAPH_ID = b.FANGRAPH_ID
),
total_audience AS (
    SELECT AUDIENCE_NAME, 'TOTAL AUDIENCE' AS CATEGORY, 'ALL' AS BREAKDOWN, COUNT(DISTINCT FANGRAPH_ID) AS FANGRAPH_ID_COUNT
    FROM base
    GROUP BY AUDIENCE_NAME
),
age_breakdown AS (
    SELECT AUDIENCE_NAME, 'AGE' AS CATEGORY, AGE_BUCKET AS BREAKDOWN, COUNT(DISTINCT FANGRAPH_ID) AS FANGRAPH_ID_COUNT
    FROM with_demos
    WHERE AGE_BUCKET IS NOT NULL
    GROUP BY AUDIENCE_NAME, AGE_BUCKET
),
gender_breakdown AS (
    SELECT AUDIENCE_NAME, 'GENDER' AS CATEGORY, GENDER AS BREAKDOWN, COUNT(DISTINCT FANGRAPH_ID) AS FANGRAPH_ID_COUNT
    FROM with_demos
    WHERE GENDER IN ('MALE', 'FEMALE')
    GROUP BY AUDIENCE_NAME, GENDER
),
income_breakdown AS (
    SELECT AUDIENCE_NAME, 'INCOME' AS CATEGORY, INCOME_HH AS BREAKDOWN, COUNT(DISTINCT FANGRAPH_ID) AS FANGRAPH_ID_COUNT
    FROM with_demos
    WHERE INCOME_HH IS NOT NULL AND INCOME_HH != 'O. $250K +'
    GROUP BY AUDIENCE_NAME, INCOME_HH
)
SELECT * FROM total_audience
UNION ALL
SELECT * FROM age_breakdown
UNION ALL
SELECT * FROM gender_breakdown
UNION ALL
SELECT * FROM income_breakdown
ORDER BY
    AUDIENCE_NAME,
    CASE CATEGORY
        WHEN 'TOTAL AUDIENCE' THEN 0
        WHEN 'AGE' THEN 1
        WHEN 'GENDER' THEN 2
        WHEN 'INCOME' THEN 3
    END,
    CASE
        WHEN CATEGORY = 'AGE' THEN
            CASE BREAKDOWN
                WHEN '18-20' THEN 1 WHEN '21-30' THEN 2 WHEN '31-40' THEN 3
                WHEN '41-50' THEN 4 WHEN '51-60' THEN 5 WHEN '61-70' THEN 6
                WHEN '71-80' THEN 7 WHEN '80+' THEN 8
            END
        WHEN CATEGORY = 'GENDER' THEN
            CASE BREAKDOWN WHEN 'MALE' THEN 1 WHEN 'FEMALE' THEN 2 END
        WHEN CATEGORY = 'INCOME' THEN
            CASE LEFT(BREAKDOWN, 1)
                WHEN 'A' THEN 1 WHEN 'B' THEN 2 WHEN 'C' THEN 3 WHEN 'D' THEN 4
                WHEN 'E' THEN 5 WHEN 'F' THEN 6 WHEN 'G' THEN 7 WHEN 'H' THEN 8
                WHEN 'K' THEN 9 WHEN 'L' THEN 10 WHEN 'M' THEN 11 WHEN 'N' THEN 12
                WHEN 'P' THEN 13 WHEN 'Q' THEN 14 WHEN 'R' THEN 15 WHEN 'S' THEN 16
                WHEN 'T' THEN 17 WHEN 'U' THEN 18
            END
    END;
