-- Query ID: 01c39a32-0212-67a8-24dd-07031940a077
-- Database: FBG_SOURCE
-- Schema: unknown
-- Warehouse: BI_L_WH
-- Executed: 2026-04-09T22:10:46.290000+00:00
-- Elapsed: 2827ms
-- Environment: FBG

SELECT "Custom SQL Query"."ACCO_ID" AS "ACCO_ID",
  "Custom SQL Query"."ATTRIBUTE_LOYALTY_LAST_UPDATE_ET" AS "ATTRIBUTE_LOYALTY_LAST_UPDATE_ET",
  "Custom SQL Query"."COMMERCE_CURRENT_YEAR_TIER_POINTS" AS "COMMERCE_CURRENT_YEAR_TIER_POINTS",
  "Custom SQL Query"."CURRENT_LOYALTY_TIER_THRESHOLD" AS "CURRENT_LOYALTY_TIER_THRESHOLD",
  "Custom SQL Query"."CURRENT_ONE_CREDIT_EARNING_POINTS" AS "CURRENT_ONE_CREDIT_EARNING_POINTS",
  "Custom SQL Query"."CURRENT_YEAR_TIER_POINTS" AS "CURRENT_YEAR_TIER_POINTS",
  "Custom SQL Query"."EARNING_TOWARDS_ONE_CREDIT" AS "EARNING_TOWARDS_ONE_CREDIT",
  "Custom SQL Query"."FAST_TRACK_END_DATE" AS "FAST_TRACK_END_DATE",
  "Custom SQL Query"."FAST_TRACK_START_DATE" AS "FAST_TRACK_START_DATE",
  "Custom SQL Query"."FBG_GOODWILL_CURRENT_YEAR_TIER_POINTS" AS "FBG_GOODWILL_CURRENT_YEAR_TIER_POINTS",
  "Custom SQL Query"."HISTORICAL_OC_BALANCE" AS "HISTORICAL_OC_BALANCE",
  "Custom SQL Query"."IS_CASINO_VIP" AS "IS_CASINO_VIP",
  "Custom SQL Query"."IS_CURRENTLY_FAST_TRACK" AS "IS_CURRENTLY_FAST_TRACK",
  "Custom SQL Query"."IS_VIP" AS "IS_VIP",
  "Custom SQL Query"."LAST_YEAR_TIER_POINTS" AS "LAST_YEAR_TIER_POINTS",
  "Custom SQL Query"."LEAD_OWNER" AS "LEAD_OWNER",
  "Custom SQL Query"."LOYALTY_LAST_UPDATE_ET" AS "LOYALTY_LAST_UPDATE_ET",
  "Custom SQL Query"."LOYALTY_TIER" AS "LOYALTY_TIER",
  "Custom SQL Query"."NEXT_LOYALTY_TIER" AS "NEXT_LOYALTY_TIER",
  CAST("Custom SQL Query"."NEXT_LOYALTY_TIER_THRESHOLD" AS DOUBLE) AS "NEXT_LOYALTY_TIER_THRESHOLD",
  "Custom SQL Query"."NEXT_TIER_THRESHOLD" AS "NEXT_TIER_THRESHOLD",
  "Custom SQL Query"."OC_CURRENT_YEAR_TIER_POINTS" AS "OC_CURRENT_YEAR_TIER_POINTS",
  "Custom SQL Query"."ONE_CREDIT_BALANCE" AS "ONE_CREDIT_BALANCE",
  "Custom SQL Query"."ONE_CREDT_THRESHOLD" AS "ONE_CREDT_THRESHOLD",
  "Custom SQL Query"."OSB_CURRENT_YEAR_TIER_POINTS" AS "OSB_CURRENT_YEAR_TIER_POINTS",
  "Custom SQL Query"."OTHER_CURRENT_YEAR_TIER_POINTS" AS "OTHER_CURRENT_YEAR_TIER_POINTS",
  "Custom SQL Query"."POINTS_TIER" AS "POINTS_TIER",
  "Custom SQL Query"."POINTS_TO_NEXT_LOYALTY_TIER" AS "POINTS_TO_NEXT_LOYALTY_TIER",
  "Custom SQL Query"."POINTS_TO_NEXT_ONE_CREDIT" AS "POINTS_TO_NEXT_ONE_CREDIT",
  "Custom SQL Query"."REMAINING_ONE_CREDITS_TO_EARN" AS "REMAINING_ONE_CREDITS_TO_EARN",
  "Custom SQL Query"."ROLLOVER_2025_TIER_POINTS" AS "ROLLOVER_2025_TIER_POINTS",
  "Custom SQL Query"."STATUS_MATCH_START" AS "STATUS_MATCH_START",
  "Custom SQL Query"."TIER_POINTS_PRIOR_TO_BLACK" AS "TIER_POINTS_PRIOR_TO_BLACK",
  "Custom SQL Query"."TIER_POINTS_SINCE_BLACK" AS "TIER_POINTS_SINCE_BLACK",
  "Custom SQL Query"."TLC_CURRENT_YEAR_TIER_POINTS" AS "TLC_CURRENT_YEAR_TIER_POINTS",
  "Custom SQL Query"."TOTAL_FBG_CURRENT_YEAR_TIER_POINTS" AS "TOTAL_FBG_CURRENT_YEAR_TIER_POINTS",
  "Custom SQL Query"."TOTAL_OC_REDEEMED_NON_FC" AS "TOTAL_OC_REDEEMED_NON_FC",
  "Custom SQL Query"."TOTAL_OC_TO_FC" AS "TOTAL_OC_TO_FC",
  "Custom SQL Query"."TOTAL_OC_VOIDED" AS "TOTAL_OC_VOIDED",
  "Custom SQL Query"."TRIAL_EXPIRY" AS "TRIAL_EXPIRY",
  "Custom SQL Query"."TRIAL_TARGET_POINTS" AS "TRIAL_TARGET_POINTS",
  "Custom SQL Query"."VIP_HOST" AS "VIP_HOST"
FROM (
  SELECT f.*, is_vip, is_casino_vip, VIP_Host, f.next_loyalty_tier_threshold as next_tier_threshold, c.lead_owner
  FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.F1_Attributes F
  INNER JOIN FBG_ANALYTICS_ENGINEERING.CUSTOMERS.CUSTOMER_MART C
  On F.Acco_ID = C.Acco_ID
  WHERE c.is_Test_account = FALSE
) "Custom SQL Query"
