-- Query ID: 01c39a63-0212-6cb9-24dd-0703194a7537
-- Database: ACCOUNT_CONFIG
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Last Executed: 2026-04-09T22:59:41.322000+00:00
-- Elapsed: 74939ms
-- Run Count: 2
-- Environment: FBG

SELECT
    QUERY_ID,
    QUERY_TEXT,
    DATABASE_NAME,
    SCHEMA_NAME,
    WAREHOUSE_NAME,
    START_TIME,
    EXECUTION_STATUS,
    TOTAL_ELAPSED_TIME
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
    RESULT_LIMIT => 10000
))
WHERE EXECUTION_STATUS = 'SUCCESS'
  AND QUERY_TYPE IN ('SELECT', 'CREATE_TABLE_AS_SELECT', 'INSERT', 'MERGE', 'UPDATE', 'DELETE', 'CREATE_TABLE', 'CREATE_VIEW')
  AND (QUERY_TAG IS NULL OR QUERY_TAG = '')
ORDER BY START_TIME DESC
