-- Query ID: 01c39a64-0212-67a9-24dd-0703194ab247
-- Database: FBG_SHEETZU
-- Schema: unknown
-- Warehouse: BI_M_WH
-- Last Executed: 2026-04-09T23:00:37.757000+00:00
-- Elapsed: 419ms
-- Run Count: 3
-- Environment: FBG

SELECT "GAME_PROVIDER_RECON_NOTES"."DW_LAST_UPDATED" AS "DW_LAST_UPDATED",
  "GAME_PROVIDER_RECON_NOTES"."GAME_PROVIDER" AS "GAME_PROVIDER",
  "GAME_PROVIDER_RECON_NOTES"."GAMING_DATE" AS "GAMING_DATE (GAME_PROVIDER_RECON_NOTES)",
  "GAME_PROVIDER_RECON_NOTES"."GAMING_DATE" AS "GAMING_DATE",
  "GAME_PROVIDER_RECON_NOTES"."JURISDICTION" AS "JURISDICTION (GAME_PROVIDER_RECON_NOTES)",
  "GAME_PROVIDER_RECON_NOTES"."JURISDICTION" AS "JURISDICTION",
  "GAME_PROVIDER_RECON_NOTES"."LASTEST_UPDATE__FBG" AS "LASTEST_UPDATE__FBG",
  "GAME_PROVIDER_RECON_NOTES"."LASTEST_UPDATE__GAME_PROVIDER" AS "LASTEST_UPDATE__GAME_PROVIDER",
  "GAME_PROVIDER_RECON_NOTES"."VARIANCE_NOTES" AS "VARIANCE_NOTES"
FROM "FBG_SHEETZU"."DEFAULT"."GAME_PROVIDER_RECON_NOTES" "GAME_PROVIDER_RECON_NOTES"
