-- Query ID: 01c39a24-0212-644a-24dd-0703193cd8df
-- Database: FBG_SHEETZU
-- Schema: unknown
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T21:56:25.106000+00:00
-- Elapsed: 442ms
-- Environment: FBG

SELECT "GAME_PROVIDER_RECON_NOTES"."DW_LAST_UPDATED" AS "DW_LAST_UPDATED",
  "GAME_PROVIDER_RECON_NOTES"."GAME_PROVIDER" AS "GAME_PROVIDER",
  "GAME_PROVIDER_RECON_NOTES"."GAMING_DATE" AS "GAMING_DATE (GAME_PROVIDER_RECON_NOTES)",
  "GAME_PROVIDER_RECON_NOTES"."GAMING_DATE" AS "GAMING_DATE",
  "GAME_PROVIDER_RECON_NOTES"."JURISDICTION" AS "JURISDICTION (GAME_PROVIDER_RECON_NOTES)",
  "GAME_PROVIDER_RECON_NOTES"."JURISDICTION" AS "JURISDICTION",
  "GAME_PROVIDER_RECON_NOTES"."LASTEST_UPDATE__FBG" AS "LASTEST_UPDATE__FBG",
  "GAME_PROVIDER_RECON_NOTES"."LASTEST_UPDATE__GAME_PROVIDER" AS "LASTEST_UPDATE__GAME_PROVIDER",
  "GAME_PROVIDER_RECON_NOTES"."VARIANCE_NOTES" AS "VARIANCE_NOTES"
FROM "FBG_SHEETZU"."DEFAULT"."GAME_PROVIDER_RECON_NOTES" "GAME_PROVIDER_RECON_NOTES"
