-- Query ID: 01c39a0c-0212-6dbe-24dd-0703193719c3
-- Database: FBG_ANALYTICS_ENGINEERING_DEV
-- Schema: unknown
-- Warehouse: BI_L_WH
-- Executed: 2026-04-09T21:32:14.169000+00:00
-- Elapsed: 611ms
-- Environment: FBG

SELECT
  fmx.account_id,
  fmx.case_id AS fmx_case_id,
  fmx.case_number AS fmx_case_number,
  fmx.case_type AS fmx_case_type,
  fmx.case_subtype AS fmx_case_subtype,
  fmx.case_status AS fmx_case_status,
  fmx.case_closed_est AS fmx_closed_date,
  fmx.last_email_time AS fmx_last_email_time,
  DATEDIFF(DAY, fmx.case_closed_est, fmx.last_email_time) AS days_email_after_closed,
  fbg_case.case_id AS fbg_case_id,
  fbg_case.case_number AS fbg_case_number,
  fbg_case.case_type AS fbg_case_type,
  fbg_case.case_subtype AS fbg_case_subtype,
  fbg_case.product_flag AS fbg_product_flag,
  fbg_case.case_source AS fbg_case_source,
  fbg_case.case_created_est AS fbg_case_created_date,
  fbg_case.case_status AS fbg_case_status
FROM FBG_ANALYTICS.OPERATIONS.CS_CASES AS fmx
INNER JOIN FBG_ANALYTICS.OPERATIONS.CS_CASES AS fbg_case
  ON fmx.account_id = fbg_case.account_id
  AND TO_DATE(fbg_case.case_created_est) = TO_DATE(fmx.last_email_time)
  AND fbg_case.product_flag IN ('Sportsbook', 'Casino')
WHERE
  fmx.product_flag = 'FMX'
  AND fmx.is_closed = TRUE
  AND fmx.case_status = 'Resolved'
  AND fmx.case_closed_est < DATEADD(DAY, -3, CURRENT_TIMESTAMP)
  AND fmx.last_email_time >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP)
  AND fmx.last_email_time IS NOT NULL
  AND DATEDIFF(DAY, fmx.case_closed_est, fmx.last_email_time) >= 3
  AND fmx.account_id IS NOT NULL
ORDER BY
  fmx.account_id,
  fmx.case_closed_est DESC NULLS LAST,
  fbg_case.case_created_est

-- Generated by Cortex
;
