-- Query ID: 01c39a1e-0212-6dbe-24dd-0703193bac6f
-- Database: FBG_ANALYTICS_ENGINEERING_DEV
-- Schema: TRADING
-- Warehouse: TRADING_XL_WH
-- Executed: 2026-04-09T21:50:56.426000+00:00
-- Elapsed: 3477ms
-- Environment: FBG

SELECT * FROM ( ( SELECT
        WAGER_STATE,
        DATE_TRUNC('WEEK', CAST(WAGER_PLACED_TIME_EST AS DATE)) AS time_period,
        COUNT(DISTINCT ACCOUNT_ID)                              AS n_accounts,
        COUNT(DISTINCT WAGER_ID)                                AS n_wagers
    FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
    WHERE WAGER_PLACED_TIME_EST >= '2025-01-01'
      AND WAGER_PLACED_TIME_EST <  '2025-02-01'
      AND WAGER_STATE IN ('IL', 'IN')
      AND IS_TEST_WAGER      = FALSE
      AND IS_DUPLICATE_WAGER = FALSE
      AND WAGER_STATUS       IN ('SETTLED', 'ACCEPTED')
    GROUP BY 1, 2
    ORDER BY 1, 2 ) ) AS "SF_CONNECTOR_QUERY_ALIAS"
