-- Query ID: 01c39a1f-0212-6e7d-24dd-0703193bd9a3
-- Database: FBG_ANALYTICS_ENGINEERING_DEV
-- Schema: TRADING
-- Warehouse: TRADING_XL_WH
-- Last Executed: 2026-04-09T21:51:04.777000+00:00
-- Elapsed: 1342825ms
-- Run Count: 2
-- Environment: FBG

SELECT * FROM ( ( WITH

-- Step 1: Base merged table
base AS (
    SELECT
        t.ACCOUNT_ID, t.WAGER_ID, t.LEG_ID,
        t.WAGER_PLACED_TIME_EST,
        t.EXPECTED_HOLD_PCT_BY_WAGER, t.TOTAL_EXPECTED_HOLD_PCT_BY_WAGER,
        t.EXPECTED_NGR_BY_WAGER, t.EXPECTED_GGR_BY_WAGER,
        t.TOTAL_STAKE_BY_WAGER, t.TOTAL_CASH_STAKE_BY_WAGER,
        t.TOTAL_PRICE_BY_WAGER, t.TOTAL_WINNINGS_BY_WAGER,
        t.PROMOTION_BOOST_PERCENTAGE, t.NON_BOOSTED_BET_PRICE,
        t.LEG_CLOSING_LINE_VALUE, t.LEG_ODDS,
        t.NUMBER_OF_LINES_BY_WAGER, t.LEG_PROBABILITY,
        t.WAGER_BET_TYPE, t.EVENT_NAME, t.EVENT_ID,
        t.EVENT_SPORT_NAME, t.WAGER_PUNTER_COLOR, t.WAGER_STATE,
        t.PROMOTION_SETTLEMENT_TYPE, t.MARKET_WINNER_CATEGORY,
        t.ACCOUNT_VALUE_BAND_AS_OF_PLACEMENT,
        t.EXPECTED_TRADING_WIN_BY_WAGER,
        s.BETTYPE,
        s.SUBBETS_SAMEGAMEPARLAY_PLACEMENTPROBABILITY,
        s.SUBBETS_SAMEGAMEPARLAY_POTENTIALPAYOUTPROBABILITY,
        s.SUBBETS_SINGLELEG_PROBABILITY,
        s.SUBBETS_SAMEGAMEPARLAY_LEGS_EVENTID,
        s.SUBBETS_SAMEGAMEPARLAY_LEGS_ID,
    FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART AS t
    LEFT JOIN (
    SELECT
        s.*,
        CASE
            WHEN s.BETTYPE IN ('BET_TYPE_SAME_GAME_PARLAY', 'BET_TYPE_SAME_GAME_PARLAY_STACK')
                THEN s.SUBBETS_SAMEGAMEPARLAY_LEGS_ID
            WHEN s.BETTYPE IN ('BET_TYPE_SINGLE', 'BET_TYPE_STRAIGHT_PARLAY')
                THEN s.SUBBETS_SINGLELEG_ID
            ELSE NULL
        END AS LEGID
    FROM FBG_ANALYTICS.JLG.SGP_LEG_DETAILS AS s
) AS s
    ON  t.ACCOUNT_ID = s.CUSTOMERID
    AND t.WAGER_ID   = s.ID
    AND t.LEG_ID     = s.LEGID
    
    WHERE t.WAGER_PLACED_TIME_EST >= '2025-01-01'
      AND t.WAGER_PLACED_TIME_EST <  '2026-03-15'
      AND t.IS_TEST_WAGER      = FALSE
      AND t.IS_FREE_BET_WAGER  = FALSE
      AND t.IS_DUPLICATE_WAGER = FALSE
      AND t.WAGER_STATUS       IN ('SETTLED', 'ACCEPTED')
      AND t.WAGER_CHANNEL      IN ('ONLINE', 'INTERNET')
      AND t.TOTAL_STAKE_BY_WAGER < 10000
      AND t.WAGER_STATE         IN ('IL', 'NY', 'OH', 'PA', 'MI', 'AZ', 'MD', 'NJ', 'MA', 'NC', 'CT', 'VA', 'TN', 'IN', 'LA', 'CO', 'KY', 'KS', 'IA', 'DC', 'WV', 'VT', 'WY')
),
-- Step 2a: EV straight parlay
straight_parlay_ev AS (
    SELECT ACCOUNT_ID, WAGER_ID,
        CASE
            WHEN COUNT_IF(LEG_ODDS IS NULL OR LEG_ODDS <= 0) > 0 THEN NULL
            WHEN COUNT_IF(LEG_PROBABILITY IS NULL OR LEG_PROBABILITY < 0 OR LEG_PROBABILITY > 1) > 0 THEN NULL
            ELSE REDUCE(ARRAY_AGG(LEG_ODDS), 1, (acc, x) -> acc * x) *
                 REDUCE(ARRAY_AGG(LEG_PROBABILITY), 1, (acc, x) -> acc * x)
        END AS EV_STRAIGHT_PARLAY
    FROM base WHERE WAGER_BET_TYPE = 'MULTIPLE'
    GROUP BY ACCOUNT_ID, WAGER_ID
),
event_probs AS (
    SELECT ACCOUNT_ID, WAGER_ID, EVENT_ID,
        COUNT(*) AS legs_per_event,
        CASE WHEN COUNT(*) > 1 THEN MAX(SUBBETS_SAMEGAMEPARLAY_PLACEMENTPROBABILITY)
             ELSE MAX(LEG_PROBABILITY) END AS EVENT_PROBABILITY
    FROM base WHERE WAGER_BET_TYPE = 'SGP Stack' AND EVENT_ID IS NOT NULL
    GROUP BY ACCOUNT_ID, WAGER_ID, EVENT_ID
),
sgp_stack_ev AS (
    SELECT ACCOUNT_ID, WAGER_ID,
        CASE WHEN COUNT_IF(EVENT_PROBABILITY IS NULL OR EVENT_PROBABILITY < 0 OR EVENT_PROBABILITY > 1) > 0 THEN NULL
             ELSE REDUCE(ARRAY_AGG(EVENT_PROBABILITY), 1, (acc, x) -> acc * x)
        END AS PROBABILITY_PRODUCT
    FROM event_probs GROUP BY ACCOUNT_ID, WAGER_ID
),
ev_potential_outcome AS (
    SELECT ACCOUNT_ID, WAGER_ID,
        SUM(LEG_ODDS * LEG_PROBABILITY) / COUNT(*) AS EV_POTENTIAL_OUTCOME
    FROM base WHERE LEG_ODDS IS NOT NULL AND LEG_PROBABILITY IS NOT NULL
    GROUP BY ACCOUNT_ID, WAGER_ID
),
with_ev AS (
    SELECT b.*,
        CASE
            WHEN b.WAGER_PLACED_TIME_EST < '2025-06-10' THEN NULL
            WHEN b.WAGER_BET_TYPE = 'SINGLE'     THEN b.LEG_ODDS * b.LEG_PROBABILITY
            WHEN b.WAGER_BET_TYPE = 'MULTIPLE'   THEN sp.EV_STRAIGHT_PARLAY
            WHEN b.WAGER_BET_TYPE = 'BETBUILDER' THEN b.TOTAL_PRICE_BY_WAGER * b.SUBBETS_SAMEGAMEPARLAY_POTENTIALPAYOUTPROBABILITY
            WHEN b.WAGER_BET_TYPE = 'SGP Stack'  THEN b.TOTAL_PRICE_BY_WAGER * sgp.PROBABILITY_PRODUCT
            ELSE NULL
        END AS EV,
        CASE WHEN b.WAGER_PLACED_TIME_EST < '2025-06-10' THEN NULL
             ELSE b.LEG_ODDS * b.LEG_PROBABILITY END AS EV_SINGLE_BET,
        CASE WHEN b.WAGER_PLACED_TIME_EST < '2025-06-10' THEN NULL
             ELSE po.EV_POTENTIAL_OUTCOME END AS EV_POTENTIAL_OUTCOME,
        sh.SHARP
    FROM base AS b
    LEFT JOIN straight_parlay_ev   AS sp  ON b.ACCOUNT_ID = sp.ACCOUNT_ID  AND b.WAGER_ID = sp.WAGER_ID  AND b.WAGER_BET_TYPE = 'MULTIPLE'
    LEFT JOIN sgp_stack_ev         AS sgp ON b.ACCOUNT_ID = sgp.ACCOUNT_ID AND b.WAGER_ID = sgp.WAGER_ID AND b.WAGER_BET_TYPE = 'SGP Stack'
    LEFT JOIN ev_potential_outcome AS po  ON b.ACCOUNT_ID = po.ACCOUNT_ID  AND b.WAGER_ID = po.WAGER_ID
    LEFT JOIN FBG_ANALYTICS.TRADING.SHARP_MODEL_FEATURES AS sh ON b.ACCOUNT_ID = sh.ACCO_ID
),
-- Step 3: Collapse to wager level
wager_level AS (
    SELECT DISTINCT
        ACCOUNT_ID, WAGER_ID, WAGER_PLACED_TIME_EST, WAGER_BET_TYPE, WAGER_STATE,
        NUMBER_OF_LINES_BY_WAGER, TOTAL_PRICE_BY_WAGER, TOTAL_STAKE_BY_WAGER,
        TOTAL_CASH_STAKE_BY_WAGER, TOTAL_WINNINGS_BY_WAGER,
        CASE WHEN TOTAL_WINNINGS_BY_WAGER > 0 THEN 1 ELSE 0 END AS WAGER_WIN,
        CASE
            WHEN TOTAL_CASH_STAKE_BY_WAGER IS NULL OR TOTAL_CASH_STAKE_BY_WAGER = 0 THEN NULL
            ELSE TOTAL_WINNINGS_BY_WAGER / TOTAL_CASH_STAKE_BY_WAGER
        END AS PAYOUT_PER_DOLLAR,
        EXPECTED_HOLD_PCT_BY_WAGER, TOTAL_EXPECTED_HOLD_PCT_BY_WAGER,
        EXPECTED_NGR_BY_WAGER, EXPECTED_GGR_BY_WAGER,
        PROMOTION_BOOST_PERCENTAGE, NON_BOOSTED_BET_PRICE,
        PROMOTION_SETTLEMENT_TYPE, WAGER_PUNTER_COLOR,
        ACCOUNT_VALUE_BAND_AS_OF_PLACEMENT,
        SHARP,
        FIRST_VALUE(EV) OVER (PARTITION BY WAGER_ID ORDER BY EV IS NOT NULL DESC, LEG_ID)                              AS EV,
        FIRST_VALUE(EV_SINGLE_BET) OVER (PARTITION BY WAGER_ID ORDER BY EV_SINGLE_BET IS NOT NULL DESC, LEG_ID)        AS EV_SINGLE_BET,
        FIRST_VALUE(EV_POTENTIAL_OUTCOME) OVER (PARTITION BY WAGER_ID ORDER BY EV_POTENTIAL_OUTCOME IS NOT NULL DESC, LEG_ID) AS EV_POTENTIAL_OUTCOME,
        FIRST_VALUE(EV - EV_SINGLE_BET) OVER (PARTITION BY WAGER_ID ORDER BY EV IS NOT NULL DESC, LEG_ID)              AS EV_DIFF_SINGLE,
        FIRST_VALUE(EV - EV_POTENTIAL_OUTCOME) OVER (PARTITION BY WAGER_ID ORDER BY EV IS NOT NULL DESC, LEG_ID)       AS EV_DIFF_POTENTIAL_OUTCOME,
        FIRST_VALUE(BETTYPE) OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID)                                               AS bettype,
        FIRST_VALUE(SUBBETS_SAMEGAMEPARLAY_POTENTIALPAYOUTPROBABILITY) OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID)     AS sgp_payout_probability,
        FIRST_VALUE(LEG_PROBABILITY)        OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID) AS first_leg_probability,
        FIRST_VALUE(LEG_CLOSING_LINE_VALUE) OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID) AS first_leg_clv,
        FIRST_VALUE(LEG_ODDS)               OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID) AS first_leg_odds,
        FIRST_VALUE(EVENT_ID)               OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID) AS first_event_id,
        FIRST_VALUE(EVENT_NAME)             OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID) AS first_event_name,
        FIRST_VALUE(EVENT_SPORT_NAME)       OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID) AS first_event_sport,
        FIRST_VALUE(MARKET_WINNER_CATEGORY) OVER (PARTITION BY WAGER_ID ORDER BY LEG_ID) AS first_market_winner_category,
        CASE
            WHEN MAX(TOTAL_STAKE_BY_WAGER) OVER (PARTITION BY WAGER_ID) IS NOT NULL
             AND MAX(TOTAL_STAKE_BY_WAGER) OVER (PARTITION BY WAGER_ID) != 0
            THEN 1 - (MAX(EXPECTED_TRADING_WIN_BY_WAGER) OVER (PARTITION BY WAGER_ID) /
                      MAX(TOTAL_STAKE_BY_WAGER)           OVER (PARTITION BY WAGER_ID))
            ELSE NULL
        END AS EH_CALCULATED
    FROM with_ev
)

-- Step 5: Final SELECT
SELECT w.*
FROM wager_level AS w ) ) AS "SF_CONNECTOR_QUERY_ALIAS"
