-- Query ID: 01c39a65-0212-6dbe-24dd-0703194b0dd7
-- Database: FBG_STITCH
-- Schema: unknown
-- Warehouse: BI_SM_WH
-- Last Executed: 2026-04-09T23:01:29.829000+00:00
-- Elapsed: 84ms
-- Run Count: 3
-- Environment: FBG

SELECT "GAME_PROVIDER_RECON_NOTES_SHEETZU"."DW_LAST_UPDATED" AS "DW_LAST_UPDATED",
  "GAME_PROVIDER_RECON_NOTES_SHEETZU"."GAME_PROVIDER" AS "GAME_PROVIDER",
  "GAME_PROVIDER_RECON_NOTES_SHEETZU"."GAMING_DATE" AS "GAMING_DATE",
  "GAME_PROVIDER_RECON_NOTES_SHEETZU"."JURISDICTION" AS "JURISDICTION",
  "GAME_PROVIDER_RECON_NOTES_SHEETZU"."LASTEST_UPDATE__FBG" AS "LASTEST_UPDATE__FBG",
  "GAME_PROVIDER_RECON_NOTES_SHEETZU"."LASTEST_UPDATE__GAME_PROVIDER" AS "LASTEST_UPDATE__GAME_PROVIDER",
  "GAME_PROVIDER_RECON_NOTES_SHEETZU"."VARIANCE_NOTES" AS "VARIANCE_NOTES"
FROM "FBG_STITCH"."GS_REG_GAME_PROVIDER_RECON"."GAME_PROVIDER_RECON_NOTES_SHEETZU" "GAME_PROVIDER_RECON_NOTES_SHEETZU"
