-- Query ID: 01c39a4c-0212-6e7d-24dd-070319457943
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: TABLEAU_XL_PROD
-- Executed: 2026-04-09T22:36:13.877000+00:00
-- Elapsed: 773ms
-- Environment: FBG

SELECT "Custom SQL Query"."ACCO_ID" AS "ACCO_ID",
  "Custom SQL Query"."ACQUISITION_BONUS_NAME" AS "ACQUISITION_BONUS_NAME",
  "Custom SQL Query"."DAY1_OC_CC_AWARD_PA" AS "DAY1_OC_CC_AWARD_PA",
  "Custom SQL Query"."DAY1_OC_FS_AWARD_MI" AS "DAY1_OC_FS_AWARD_MI",
  "Custom SQL Query"."DAY1_OSB_FC_AWARD_MI" AS "DAY1_OSB_FC_AWARD_MI",
  "Custom SQL Query"."DAY1_OSB_FC_AWARD_PA" AS "DAY1_OSB_FC_AWARD_PA",
  "Custom SQL Query"."DAY1_OSB_WAGER" AS "DAY1_OSB_WAGER",
  "Custom SQL Query"."DAY2_OC_CC_AWARD_PA" AS "DAY2_OC_CC_AWARD_PA",
  "Custom SQL Query"."DAY2_OC_CC_OPTIN_PA" AS "DAY2_OC_CC_OPTIN_PA",
  "Custom SQL Query"."DAY2_OC_FS_AWARD_MI" AS "DAY2_OC_FS_AWARD_MI",
  "Custom SQL Query"."DAY2_OC_FS_OPTIN_MI" AS "DAY2_OC_FS_OPTIN_MI",
  "Custom SQL Query"."DAY2_OSB_FC_AWARD_MI" AS "DAY2_OSB_FC_AWARD_MI",
  "Custom SQL Query"."DAY2_OSB_FC_AWARD_PA" AS "DAY2_OSB_FC_AWARD_PA",
  "Custom SQL Query"."DAY2_OSB_FC_OPTIN_MI" AS "DAY2_OSB_FC_OPTIN_MI",
  "Custom SQL Query"."DAY2_OSB_FC_OPTIN_PA" AS "DAY2_OSB_FC_OPTIN_PA",
  "Custom SQL Query"."DAY2_OSB_WAGER" AS "DAY2_OSB_WAGER",
  "Custom SQL Query"."DAY3_OC_CC_AWARD_PA" AS "DAY3_OC_CC_AWARD_PA",
  "Custom SQL Query"."DAY3_OC_CC_OPTIN_PA" AS "DAY3_OC_CC_OPTIN_PA",
  "Custom SQL Query"."DAY3_OC_FS_AWARD_MI" AS "DAY3_OC_FS_AWARD_MI",
  "Custom SQL Query"."DAY3_OC_FS_OPTIN_MI" AS "DAY3_OC_FS_OPTIN_MI",
  "Custom SQL Query"."DAY3_OSB_FC_AWARD_MI" AS "DAY3_OSB_FC_AWARD_MI",
  "Custom SQL Query"."DAY3_OSB_FC_AWARD_PA" AS "DAY3_OSB_FC_AWARD_PA",
  "Custom SQL Query"."DAY3_OSB_FC_OPTIN_MI" AS "DAY3_OSB_FC_OPTIN_MI",
  "Custom SQL Query"."DAY3_OSB_FC_OPTIN_PA" AS "DAY3_OSB_FC_OPTIN_PA",
  "Custom SQL Query"."DAY3_OSB_WAGER" AS "DAY3_OSB_WAGER",
  "Custom SQL Query"."DAY4_OC_FS_AWARD_MI" AS "DAY4_OC_FS_AWARD_MI",
  "Custom SQL Query"."DAY4_OC_FS_OPTIN_MI" AS "DAY4_OC_FS_OPTIN_MI",
  "Custom SQL Query"."DAY5_OC_FS_AWARD_MI" AS "DAY5_OC_FS_AWARD_MI",
  "Custom SQL Query"."DAY5_OC_FS_OPTIN_MI" AS "DAY5_OC_FS_OPTIN_MI",
  "Custom SQL Query"."KYC_TIMESTAMP" AS "KYC_TIMESTAMP",
  "Custom SQL Query"."OC_WAGER_10_MI" AS "OC_WAGER_10_MI",
  "Custom SQL Query"."OC_WAGER_30_PA" AS "OC_WAGER_30_PA",
  "Custom SQL Query"."REG_TIMESTAMP" AS "REG_TIMESTAMP"
FROM (
  select * from fbg_analytics.casino.reporting_suo_dual_product
) "Custom SQL Query"
