-- Query ID: 01c39a3a-0212-67a9-24dd-0703194251d7
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: BI_XL_WH
-- Executed: 2026-04-09T22:18:11.950000+00:00
-- Elapsed: 85ms
-- Environment: FBG

SELECT "VIP_QUARTERLY_ACQUISITION_TARGETS"."NAME" AS "NAME",
  "VIP_QUARTERLY_ACQUISITION_TARGETS"."QUARTER" AS "QUARTER (VIP_QUARTERLY_ACQUISITION_TARGETS)",
  "VIP_QUARTERLY_ACQUISITION_TARGETS"."TARGET" AS "TARGET"
FROM "FBG_ANALYTICS"."VIP"."VIP_QUARTERLY_ACQUISITION_TARGETS" "VIP_QUARTERLY_ACQUISITION_TARGETS"
