-- Query ID: 01c39a01-0212-67a8-24dd-07031934aa4b
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: TRADING_XL_WH
-- Executed: 2026-04-09T21:21:20.451000+00:00
-- Elapsed: 2596ms
-- Environment: FBG

SELECT "BUSINESS_MIX_RUNNING_UP_BETS"."ACCO_ID" AS "ACCO_ID",
  "BUSINESS_MIX_RUNNING_UP_BETS"."BET_PROB" AS "BET_PROB",
  "BUSINESS_MIX_RUNNING_UP_BETS"."BET_TYPE_NEW" AS "BET_TYPE_NEW",
  "BUSINESS_MIX_RUNNING_UP_BETS"."BOOSTED_BET_PRICE" AS "BOOSTED_BET_PRICE",
  "BUSINESS_MIX_RUNNING_UP_BETS"."BOOST_PERCENTAGE" AS "BOOST_PERCENTAGE",
  "BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE" AS "CURRENT_VALUE",
  "BUSINESS_MIX_RUNNING_UP_BETS"."EVENT" AS "EVENT",
  "BUSINESS_MIX_RUNNING_UP_BETS"."EVENT_TIME" AS "EVENT_TIME",
  "BUSINESS_MIX_RUNNING_UP_BETS"."FREE_BET" AS "FREE_BET",
  "BUSINESS_MIX_RUNNING_UP_BETS"."ID" AS "ID",
  "BUSINESS_MIX_RUNNING_UP_BETS"."INSTRUMENT_ID" AS "INSTRUMENT_ID",
  "BUSINESS_MIX_RUNNING_UP_BETS"."LEGS" AS "LEGS",
  "BUSINESS_MIX_RUNNING_UP_BETS"."MARKET" AS "MARKET",
  "BUSINESS_MIX_RUNNING_UP_BETS"."OUTSTANDING_LEGS" AS "OUTSTANDING_LEGS",
  "BUSINESS_MIX_RUNNING_UP_BETS"."PLACED_TIME_ET" AS "PLACED_TIME_ET",
  "BUSINESS_MIX_RUNNING_UP_BETS"."POTENTIAL_PAYOUT" AS "POTENTIAL_PAYOUT",
  "BUSINESS_MIX_RUNNING_UP_BETS"."RESULT_TYPE" AS "RESULT_TYPE",
  "BUSINESS_MIX_RUNNING_UP_BETS"."SELECTION" AS "SELECTION",
  "BUSINESS_MIX_RUNNING_UP_BETS"."TOTAL_STAKE" AS "TOTAL_STAKE",
  "BUSINESS_MIX_RUNNING_UP_BETS"."VOIDED_LEGS" AS "VOIDED_LEGS",
  "BUSINESS_MIX_RUNNING_UP_BETS"."WINNING_LEGS" AS "WINNING_LEGS",
  CAST("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE" AS DOUBLE) AS "avg:CURRENT_VALUE:ok",
  SUM("BUSINESS_MIX_RUNNING_UP_BETS"."ORIGINAL_LEG_PRICE") AS "sum:ORIGINAL_LEG_PRICE:ok"
FROM "FBG_ANALYTICS"."TRADING"."BUSINESS_MIX_RUNNING_UP_BETS" "BUSINESS_MIX_RUNNING_UP_BETS"
WHERE ((NOT ("BUSINESS_MIX_RUNNING_UP_BETS"."BET_PROB" IS NULL)) AND (("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE" >= 0) OR ("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE" IS NULL)) AND ("BUSINESS_MIX_RUNNING_UP_BETS"."MARKET" = '1st Round Leader') AND ("BUSINESS_MIX_RUNNING_UP_BETS"."OUTSTANDING_LEGS" <= 2) AND ("BUSINESS_MIX_RUNNING_UP_BETS"."SELECTION" = 'Justin Rose'))
GROUP BY 1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21
