-- Query ID: 01c39a0d-0212-6b00-24dd-07031937a7c7
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH_PROD
-- Executed: 2026-04-09T21:33:16.657000+00:00
-- Elapsed: 703ms
-- Environment: FBG

SELECT "USER_AGGREGATED_REPORT_DATASOURCE"."LIVE_BET" AS "LIVE_BET",
  SUM("USER_AGGREGATED_REPORT_DATASOURCE"."TOTAL_HANDLE") AS "sum:TOTAL_HANDLE:ok"
FROM "FBG_ANALYTICS"."TRADING"."USER_AGGREGATED_REPORT_DATASOURCE" "USER_AGGREGATED_REPORT_DATASOURCE"
WHERE (((CAST("USER_AGGREGATED_REPORT_DATASOURCE"."ACCOUNT_ID" AS TEXT) IS NULL) OR (CAST("USER_AGGREGATED_REPORT_DATASOURCE"."ACCOUNT_ID" AS TEXT) <> '2026159')) AND (CAST("USER_AGGREGATED_REPORT_DATASOURCE"."ACCOUNT_ID" AS TEXT) = '1744917') AND ("USER_AGGREGATED_REPORT_DATASOURCE"."DATE_ALK" >= '2024-01-01 00:00:00.000'::TIMESTAMP_NTZ) AND ("USER_AGGREGATED_REPORT_DATASOURCE"."DATE_ALK" < '2027-01-01 00:00:00.000'::TIMESTAMP_NTZ) AND ((("USER_AGGREGATED_REPORT_DATASOURCE"."STAKE_FACTOR_CURRENT_EQUALS_TOB" >= 0) AND ("USER_AGGREGATED_REPORT_DATASOURCE"."STAKE_FACTOR_CURRENT_EQUALS_TOB" <= 1)) OR ("USER_AGGREGATED_REPORT_DATASOURCE"."STAKE_FACTOR_CURRENT_EQUALS_TOB" IS NULL)))
GROUP BY 1
