-- Query ID: 01c39a0d-0212-6b00-24dd-07031937a657
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH_PROD
-- Executed: 2026-04-09T21:33:07.800000+00:00
-- Elapsed: 2695ms
-- Environment: FBG

SELECT "USER_AGGREGATED_REPORT_DATASOURCE"."CASINO_SEGMENT" AS "CASINO_SEGMENT",
  "USER_AGGREGATED_REPORT_DATASOURCE"."FAVORITE_ONLINE_CASINO_GAME_ALL_TIME" AS "FAVORITE_ONLINE_CASINO_GAME_ALL_TIME",
  "USER_AGGREGATED_REPORT_DATASOURCE"."FBG_FTU_DATE" AS "FBG_FTU_DATE",
  "USER_AGGREGATED_REPORT_DATASOURCE"."IN_PLAY_DELAY" AS "IN_PLAY_DELAY",
  "USER_AGGREGATED_REPORT_DATASOURCE"."LEAD_OWNER" AS "LEAD_OWNER",
  "USER_AGGREGATED_REPORT_DATASOURCE"."PSEUDONYM" AS "PSEUDONYM",
  "USER_AGGREGATED_REPORT_DATASOURCE"."SBK_CLUSTER" AS "SBK_CLUSTER",
  "USER_AGGREGATED_REPORT_DATASOURCE"."USER_SEGMENT" AS "USER_SEGMENT",
  "USER_AGGREGATED_REPORT_DATASOURCE"."VIP_HOST" AS "VIP_HOST",
  "USER_AGGREGATED_REPORT_DATASOURCE"."VIP_OSB_TIER" AS "VIP_OSB_TIER",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS") AS "avg:ALERTS:ok",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED") AS "avg:ALERTS_RESOLVED:ok",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."CASINO_HANDLE") AS "avg:CASINO_HANDLE:ok",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."CASINO_NGR") AS "avg:CASINO_NGR:ok",
  AVG((CASE WHEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" <> 0 THEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_POS" / "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" END)) AS "avg:Calculation_1168121165724221442:ok",
  AVG((CASE WHEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" <> 0 THEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_SHARP" / "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" END)) AS "avg:Calculation_1168121165724397571:ok",
  AVG((CASE WHEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" <> 0 THEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_NEUTRAL" / "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" END)) AS "avg:Calculation_1168121165724569604:ok",
  AVG((CASE WHEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" <> 0 THEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_POS_LOW_CONFIDENCE" / "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" END)) AS "avg:Calculation_1168121165724708869:ok",
  AVG((CASE WHEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" <> 0 THEN "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_SHARP_LOW_CONFIDENCE" / "USER_AGGREGATED_REPORT_DATASOURCE"."ALERTS_RESOLVED" END)) AS "avg:Calculation_1168121165725675526:ok",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."PUSH_7DAYS_PCT") AS "avg:PUSH_7DAYS_PCT:ok",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."PUSH_LIFETIME_PCT") AS "avg:PUSH_LIFETIME_PCT:ok",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."STAKEFACTOR") AS "avg:STAKEFACTOR:ok",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."VOID_7DAYS_PCT") AS "avg:VOID_7DAYS_PCT:ok",
  AVG("USER_AGGREGATED_REPORT_DATASOURCE"."VOID_LIFETIME_PCT") AS "avg:VOID_LIFETIME_PCT:ok"
FROM "FBG_ANALYTICS"."TRADING"."USER_AGGREGATED_REPORT_DATASOURCE" "USER_AGGREGATED_REPORT_DATASOURCE"
WHERE (((CAST("USER_AGGREGATED_REPORT_DATASOURCE"."ACCOUNT_ID" AS TEXT) IS NULL) OR (CAST("USER_AGGREGATED_REPORT_DATASOURCE"."ACCOUNT_ID" AS TEXT) <> '2026159')) AND (CAST("USER_AGGREGATED_REPORT_DATASOURCE"."ACCOUNT_ID" AS TEXT) = '1744917') AND ((("USER_AGGREGATED_REPORT_DATASOURCE"."STAKE_FACTOR_CURRENT_EQUALS_TOB" >= 0) AND ("USER_AGGREGATED_REPORT_DATASOURCE"."STAKE_FACTOR_CURRENT_EQUALS_TOB" <= 1)) OR ("USER_AGGREGATED_REPORT_DATASOURCE"."STAKE_FACTOR_CURRENT_EQUALS_TOB" IS NULL)))
GROUP BY 1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10
