-- Query ID: 01c39a2b-0212-6dbe-24dd-0703193e8d1b
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: TABLEAU_XL_PROD
-- Executed: 2026-04-09T22:03:26.144000+00:00
-- Elapsed: 116030ms
-- Environment: FBG

SELECT "Custom SQL Query"."ADHERENCE_EXCEPTION_DURATION" AS "ADHERENCE_EXCEPTION_DURATION",
  "Custom SQL Query"."AGENT_EMAIL" AS "AGENT_EMAIL",
  "Custom SQL Query"."AGENT_HANDLE_TIME_MINUTES" AS "AGENT_HANDLE_TIME_MINUTES",
  "Custom SQL Query"."AGENT_ID" AS "AGENT_ID",
  "Custom SQL Query"."AGENT_NAME" AS "AGENT_NAME",
  "Custom SQL Query"."CASE_NUMBER" AS "CASE_NUMBER",
  "Custom SQL Query"."CASE_SUBTYPE" AS "CASE_SUBTYPE",
  "Custom SQL Query"."CASE_TYPE" AS "CASE_TYPE",
  "Custom SQL Query"."DAILY_ADHERENCE_PERCENTAGE" AS "DAILY_ADHERENCE_PERCENTAGE",
  "Custom SQL Query"."DATE" AS "DATE",
  "Custom SQL Query"."FCR" AS "FCR",
  "Custom SQL Query"."OUT_OF_ADHERENCE_DURATION" AS "OUT_OF_ADHERENCE_DURATION",
  "Custom SQL Query"."PRODUCT_FLAG" AS "PRODUCT_FLAG",
  "Custom SQL Query"."ROSTERED_TOTAL_DURATION" AS "ROSTERED_TOTAL_DURATION"
FROM (
  SELECT *
  FROM fbg_analytics.operations.cs_agent_leaderboard
  WHERE date >= '2024-09-01'
) "Custom SQL Query"
