-- Query ID: 01c39a2d-0212-6cb9-24dd-0703193f3267
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: BI_L_WH
-- Executed: 2026-04-09T22:05:37.849000+00:00
-- Elapsed: 78ms
-- Environment: FBG

SELECT "VIP_QUARTERLY_ACQUISITION_TARGETS"."NAME" AS "NAME",
  "VIP_QUARTERLY_ACQUISITION_TARGETS"."QUARTER" AS "QUARTER (VIP_QUARTERLY_ACQUISITION_TARGETS)",
  "VIP_QUARTERLY_ACQUISITION_TARGETS"."TARGET" AS "TARGET"
FROM "VIP"."VIP_QUARTERLY_ACQUISITION_TARGETS" "VIP_QUARTERLY_ACQUISITION_TARGETS"
