-- Query ID: 01c39a01-0212-67a8-24dd-07031934aac3
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: TRADING_XL_WH
-- Executed: 2026-04-09T21:21:24.162000+00:00
-- Elapsed: 123ms
-- Environment: FBG

SELECT "BUSINESS_MIX_RUNNING_UP_BETS"."ID" AS "ID",
  AVG("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE") AS "avg:CURRENT_VALUE:ok"
FROM "FBG_ANALYTICS"."TRADING"."BUSINESS_MIX_RUNNING_UP_BETS" "BUSINESS_MIX_RUNNING_UP_BETS"
WHERE ((NOT ("BUSINESS_MIX_RUNNING_UP_BETS"."BET_PROB" IS NULL)) AND (("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE" >= 0) OR ("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE" IS NULL)) AND ("BUSINESS_MIX_RUNNING_UP_BETS"."MARKET" = '1st Round Leader') AND ("BUSINESS_MIX_RUNNING_UP_BETS"."OUTSTANDING_LEGS" <= 2) AND ("BUSINESS_MIX_RUNNING_UP_BETS"."SELECTION" = 'Justin Rose'))
GROUP BY 1
