-- Query ID: 01c39a03-0212-644a-24dd-07031935618f
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: BI_XL_WH
-- Executed: 2026-04-09T21:23:28.046000+00:00
-- Elapsed: 55526ms
-- Environment: FBG

SELECT "PNL_OVERALL"."ACCOUNT_STATUS" AS "ACCOUNT_STATUS",
  "PNL_OVERALL"."Acco ID" AS "Acco ID (PNL_OVERALL)",
  "PNL_OVERALL"."Acq" AS "Acq (PNL_OVERALL)",
  "PNL_OVERALL"."Bonus Handle" AS "Bonus Handle (PNL_OVERALL)",
  "PNL_OVERALL"."CURRENT_VIP_HOST" AS "CURRENT_VIP_HOST",
  "PNL_OVERALL"."CVP" AS "CVP (PNL_OVERALL)",
  "PNL_OVERALL"."Cash GGR" AS "Cash GGR (PNL_OVERALL)",
  "PNL_OVERALL"."Cash Handle" AS "Cash Handle (PNL_OVERALL)",
  "PNL_OVERALL"."Cash eGGR" AS "Cash eGGR (PNL_OVERALL)",
  "PNL_OVERALL"."Daily Cas Segment Cohort" AS "Daily Cas Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."Daily Ent Segment Cohort" AS "Daily Ent Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."Daily Osb Segment Cohort" AS "Daily Osb Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."Date" AS "Date (PNL_OVERALL)",
  "PNL_OVERALL"."Finance NGR" AS "Finance NGR (PNL_OVERALL)",
  "PNL_OVERALL"."Finance eNGR" AS "Finance eNGR (PNL_OVERALL)",
  "PNL_OVERALL"."Focus" AS "Focus (PNL_OVERALL)",
  "PNL_OVERALL"."Gift Cost" AS "Gift Cost (PNL_OVERALL)",
  "PNL_OVERALL"."Lead Create Date" AS "Lead Create Date",
  "PNL_OVERALL"."Lead Owner" AS "Lead Owner (PNL_OVERALL)",
  "PNL_OVERALL"."Loyalty Tier" AS "Loyalty Tier (PNL_OVERALL)",
  "PNL_OVERALL"."Mig" AS "Mig (PNL_OVERALL)",
  "PNL_OVERALL"."Month" AS "Month (PNL_OVERALL)",
  "PNL_OVERALL"."Monthly Cas Segment Cohort" AS "Monthly Cas Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."Monthly Ent Segment Cohort" AS "Monthly Ent Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."Monthly Osb Segment Cohort" AS "Monthly Osb Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."NGR" AS "NGR (PNL_OVERALL)",
  "PNL_OVERALL"."Non VIP Acq" AS "Non VIP Acq",
  "PNL_OVERALL"."Non VIP Bonus Handle" AS "Non VIP Bonus Handle",
  "PNL_OVERALL"."Non VIP CVP" AS "Non VIP CVP",
  "PNL_OVERALL"."Non VIP Cash GGR" AS "Non VIP Cash GGR",
  "PNL_OVERALL"."Non VIP Cash Handle" AS "Non VIP Cash Handle",
  "PNL_OVERALL"."Non VIP Cash eGGR" AS "Non VIP Cash eGGR",
  "PNL_OVERALL"."Non VIP Finance NGR" AS "Non VIP Finance NGR",
  "PNL_OVERALL"."Non VIP Finance eNGR" AS "Non VIP Finance eNGR",
  "PNL_OVERALL"."Non VIP Gift Cost" AS "Non VIP Gift Cost",
  "PNL_OVERALL"."Non VIP Mig" AS "Non VIP Mig",
  "PNL_OVERALL"."Non VIP NGR" AS "Non VIP NGR",
  "PNL_OVERALL"."Non VIP One Credit" AS "Non VIP One Credit",
  "PNL_OVERALL"."Non VIP Ret" AS "Non VIP Ret",
  "PNL_OVERALL"."Non VIP Ticket Cost" AS "Non VIP Ticket Cost",
  "PNL_OVERALL"."Non VIP Trading Win" AS "Non VIP Trading Win",
  "PNL_OVERALL"."Non VIP eAcq" AS "Non VIP eAcq",
  "PNL_OVERALL"."Non VIP eCVP" AS "Non VIP eCVP",
  "PNL_OVERALL"."Non VIP eMig" AS "Non VIP eMig",
  "PNL_OVERALL"."Non VIP eNGR" AS "Non VIP eNGR",
  "PNL_OVERALL"."Non VIP eRet" AS "Non VIP eRet",
  "PNL_OVERALL"."Non VIP eTrading Win" AS "Non VIP eTrading Win",
  "PNL_OVERALL"."One Credit" AS "One Credit (PNL_OVERALL)",
  "PNL_OVERALL"."Product" AS "Product (PNL_OVERALL)",
  "PNL_OVERALL"."Product Preference" AS "Product Preference (PNL_OVERALL)",
  "PNL_OVERALL"."Quarter" AS "Quarter (PNL_OVERALL)",
  "PNL_OVERALL"."Ret" AS "Ret (PNL_OVERALL)",
  "PNL_OVERALL"."STAKE_FACTOR" AS "STAKE_FACTOR",
  "PNL_OVERALL"."Sr Manager" AS "Sr Manager (PNL_OVERALL)",
  "PNL_OVERALL"."State" AS "State (PNL_OVERALL)",
  "PNL_OVERALL"."Team" AS "Team (PNL_OVERALL)",
  "PNL_OVERALL"."Ticket Cost" AS "Ticket Cost (PNL_OVERALL)",
  "PNL_OVERALL"."Trading Win" AS "Trading Win (PNL_OVERALL)",
  "PNL_OVERALL"."VIP Attribution" AS "VIP Attribution (PNL_OVERALL)",
  "PNL_OVERALL"."VIP Host" AS "VIP Host (PNL_OVERALL)",
  "PNL_OVERALL"."VIP Status Month" AS "VIP Status Month (PNL_OVERALL)",
  "PNL_OVERALL"."VIP Status Quarter" AS "VIP Status Quarter (PNL_OVERALL)",
  "PNL_OVERALL"."VIP Status Year" AS "VIP Status Year (PNL_OVERALL)",
  "PNL_OVERALL"."Week" AS "Week (PNL_OVERALL)",
  "PNL_OVERALL"."Weekly Cas Segment Cohort" AS "Weekly Cas Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."Weekly Ent Segment Cohort" AS "Weekly Ent Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."Weekly Osb Segment Cohort" AS "Weekly Osb Segment Cohort (PNL_OVERALL)",
  "PNL_OVERALL"."Year" AS "Year (PNL_OVERALL)",
  "PNL_OVERALL"."eAcq" AS "eAcq (PNL_OVERALL)",
  "PNL_OVERALL"."eCVP" AS "eCVP (PNL_OVERALL)",
  "PNL_OVERALL"."eMig" AS "eMig (PNL_OVERALL)",
  "PNL_OVERALL"."eNGR" AS "eNGR (PNL_OVERALL)",
  "PNL_OVERALL"."eRet" AS "eRet (PNL_OVERALL)",
  "PNL_OVERALL"."eTrading Win" AS "eTrading Win (PNL_OVERALL)"
FROM "FBG_ANALYTICS"."VIP"."PNL_OVERALL" "PNL_OVERALL"
