-- Query ID: 01c399e6-0212-6e7d-24dd-0703192e7187
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T20:54:24.168000+00:00
-- Elapsed: 705ms
-- Environment: FBG

SELECT "CM_HUB_COMPLETED_ENTRIES"."ACCOUNT_ID" AS "ACCOUNT_ID",
  "CM_HUB_COMPLETED_ENTRIES"."ACTION" AS "ACTION",
  "CM_HUB_COMPLETED_ENTRIES"."COMMENTS" AS "COMMENTS",
  "CM_HUB_COMPLETED_ENTRIES"."DATE" AS "DATE",
  "CM_HUB_COMPLETED_ENTRIES"."NEW_IPD" AS "NEW_IPD",
  "CM_HUB_COMPLETED_ENTRIES"."NEW_LIVE_SF" AS "NEW_LIVE_SF",
  "CM_HUB_COMPLETED_ENTRIES"."NEW_PM_SF" AS "NEW_PM_SF",
  "CM_HUB_COMPLETED_ENTRIES"."ORIGINAL_IPD" AS "ORIGINAL_IPD",
  "CM_HUB_COMPLETED_ENTRIES"."ORIGINAL_LIVE_SF" AS "ORIGINAL_LIVE_SF",
  "CM_HUB_COMPLETED_ENTRIES"."ORIGINAL_PM_SF" AS "ORIGINAL_PM_SF",
  "CM_HUB_COMPLETED_ENTRIES"."REC_ACTION" AS "REC_ACTION",
  "CM_HUB_COMPLETED_ENTRIES"."REPORT" AS "REPORT",
  "CM_HUB_COMPLETED_ENTRIES"."SHARP_OR_REC_OVERALL" AS "SHARP_OR_REC_OVERALL",
  "CM_HUB_COMPLETED_ENTRIES"."TRADER" AS "TRADER",
  SUM(TRY_CAST("CM_HUB_COMPLETED_ENTRIES"."CLV_ELIGIBLE" AS DOUBLE)) AS "sum:Calculation_1958784381137539072:ok",
  SUM(TRY_CAST("CM_HUB_COMPLETED_ENTRIES"."LIVE_EV" AS DOUBLE)) AS "sum:Calculation_1958784381139148801:ok",
  SUM(TRY_CAST("CM_HUB_COMPLETED_ENTRIES"."LIVE_WINDOW" AS DOUBLE)) AS "sum:Calculation_1958784381140410370:ok",
  SUM(TRY_CAST("CM_HUB_COMPLETED_ENTRIES"."SHARP_PROB" AS DOUBLE)) AS "sum:Calculation_2157787189410877441:ok",
  SUM(TRY_CAST("CM_HUB_COMPLETED_ENTRIES"."SHARP_WINDOW" AS DOUBLE)) AS "sum:Calculation_2157787189414055938:ok",
  SUM(TRY_CAST("CM_HUB_COMPLETED_ENTRIES"."CLV" AS DOUBLE)) AS "sum:Calculation_2157787189417144323:ok"
FROM "FBG_ANALYTICS"."TRADING"."CM_HUB_COMPLETED_ENTRIES" "CM_HUB_COMPLETED_ENTRIES"
WHERE ("CM_HUB_COMPLETED_ENTRIES"."ACCOUNT_ID" = '3255791')
GROUP BY 1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14
