-- Query ID: 01c399e3-0212-6dbe-24dd-0703192d6e13
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: TRADING_XL_WH
-- Executed: 2026-04-09T20:51:55.531000+00:00
-- Elapsed: 394ms
-- Environment: FBG

SELECT "BUSINESS_MIX_RUNNING_UP_BETS"."ID" AS "ID",
  AVG("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE") AS "avg:CURRENT_VALUE:ok"
FROM "FBG_ANALYTICS"."TRADING"."BUSINESS_MIX_RUNNING_UP_BETS" "BUSINESS_MIX_RUNNING_UP_BETS"
WHERE ((NOT ("BUSINESS_MIX_RUNNING_UP_BETS"."BET_PROB" IS NULL)) AND (("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE" >= 100) OR ("BUSINESS_MIX_RUNNING_UP_BETS"."CURRENT_VALUE" IS NULL)) AND ("BUSINESS_MIX_RUNNING_UP_BETS"."OUTSTANDING_LEGS" <= 2) AND ("BUSINESS_MIX_RUNNING_UP_BETS"."SELECTION" = 'Fred Couples'))
GROUP BY 1
