-- Query ID: 01c39a29-0212-6e7d-24dd-0703193e41af
-- Database: FBG_ANALYTICS
-- Schema: unknown
-- Warehouse: TABLEAU_XL_PROD
-- Executed: 2026-04-09T22:01:13.929000+00:00
-- Elapsed: 62ms
-- Environment: FBG

SELECT "AGENT_MASTER_ROSTER"."AGENT_ID" AS "AGENT_ID (AGENT_MASTER_ROSTER)",
  "AGENT_MASTER_ROSTER"."AGENT_NAME" AS "AGENT_NAME",
  "AGENT_MASTER_ROSTER"."AGENT_TYPE" AS "AGENT_TYPE",
  "AGENT_MASTER_ROSTER"."DAYS_OFF" AS "DAYS_OFF",
  "AGENT_MASTER_ROSTER"."DW_LAST_UPDATED" AS "DW_LAST_UPDATED",
  "AGENT_MASTER_ROSTER"."EMAIL" AS "EMAIL",
  "AGENT_MASTER_ROSTER"."FANAPP" AS "FANAPP",
  "AGENT_MASTER_ROSTER"."FTE_SEASONAL" AS "FTE_SEASONAL",
  "AGENT_MASTER_ROSTER"."HOME_LOCATION" AS "HOME_LOCATION",
  "AGENT_MASTER_ROSTER"."IL_LICENSE" AS "IL_LICENSE",
  "AGENT_MASTER_ROSTER"."IN_LICENSE" AS "IN_LICENSE",
  "AGENT_MASTER_ROSTER"."LEAVE_END_DATE" AS "LEAVE_END_DATE",
  "AGENT_MASTER_ROSTER"."NJ_LICENSE" AS "NJ_LICENSE",
  "AGENT_MASTER_ROSTER"."PA_LICENCE" AS "PA_LICENCE",
  "AGENT_MASTER_ROSTER"."REMOTE" AS "REMOTE",
  "AGENT_MASTER_ROSTER"."REPORTS_TO" AS "REPORTS_TO",
  "AGENT_MASTER_ROSTER"."SALESFORCE_ID" AS "SALESFORCE_ID",
  "AGENT_MASTER_ROSTER"."SF_ALIAS" AS "SF_ALIAS",
  "AGENT_MASTER_ROSTER"."SHIFT_(EST)" AS "SHIFT_(EST)",
  "AGENT_MASTER_ROSTER"."START_DATE" AS "START_DATE",
  "AGENT_MASTER_ROSTER"."STATUS" AS "STATUS",
  "AGENT_MASTER_ROSTER"."TERM_DATE" AS "TERM_DATE",
  "AGENT_MASTER_ROSTER"."TITLE" AS "TITLE",
  "AGENT_MASTER_ROSTER"."VIP_SKILLED" AS "VIP_SKILLED",
  "AGENT_MASTER_ROSTER"."WV_LICENSE" AS "WV_LICENSE"
FROM "FBG_ANALYTICS"."OPERATIONS"."AGENT_MASTER_ROSTER" "AGENT_MASTER_ROSTER"
