-- Query ID: 01c39a46-0212-6cb9-24dd-07031944a3fb
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:30:28.310000+00:00
-- Elapsed: 970ms
-- Environment: FBG

WITH __casino_daily_settled_agg AS (
  SELECT
    acco_id,
    game_id,
    settled_date_alk,
    cash_bet_stake,
    casino_credit_bet_stake,
    freespin_bet_stake,
    ggr,
    is_test_account,
    total_bet_count,
    total_stake
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_DAILY_SETTLED_AGG
), __casino_game_details AS (
  SELECT
    category,
    game_name,
    game_type,
    granular_game_type,
    game_id
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_GAME_DETAILS
)
/* Top games played last 30 days */
SELECT
  cg.game_name,
  cg.category,
  cg.game_type,
  cg.granular_game_type,
  SUM(cd.total_stake) AS total_handle,
  SUM(cd.ggr) AS ggr,
  SUM(cd.total_bet_count) AS total_bets,
  SUM(cd.cash_bet_stake) AS cash_handle,
  SUM(cd.freespin_bet_stake) AS freespin_handle,
  SUM(cd.casino_credit_bet_stake) AS credit_handle
FROM __casino_daily_settled_agg AS cd
INNER JOIN __casino_game_details AS cg
  ON cd.game_id = cg.game_id
WHERE
  cd.acco_id = '2144018'
  AND cd.is_test_account = '0'
  AND cd.settled_date_alk >= DATEADD(DAY, -30, CURRENT_DATE)
GROUP BY
  cg.game_name,
  cg.category,
  cg.game_type,
  cg.granular_game_type
ORDER BY
  total_handle DESC NULLS LAST
LIMIT 15 /* Generated by Cortex */;
