-- Query ID: 01c39a41-0212-67a8-24dd-070319433b5f
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:25:03.876000+00:00
-- Elapsed: 1969ms
-- Environment: FBG

WITH __casino_daily_settled_agg AS (
  SELECT
    acco_id,
    game_id,
    settled_date_alk,
    cash_bet_stake,
    ggr,
    is_test_account,
    ngr,
    total_bet_count,
    total_stake
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_DAILY_SETTLED_AGG
)
/* Previous 30 days (31-60 days ago) for benchmark comparison */
SELECT
  SUM(cd.total_stake) AS total_handle,
  SUM(cd.cash_bet_stake) AS cash_handle,
  SUM(cd.ggr) AS ggr,
  SUM(cd.ngr) AS ngr,
  SUM(cd.total_bet_count) AS total_bets,
  COUNT(DISTINCT cd.settled_date_alk) AS active_days,
  COUNT(DISTINCT cd.game_id) AS unique_games_played
FROM __casino_daily_settled_agg AS cd
WHERE
  cd.acco_id = '2144018'
  AND cd.settled_date_alk >= DATEADD(DAY, -60, CURRENT_DATE)
  AND cd.settled_date_alk < DATEADD(DAY, -30, CURRENT_DATE)
  AND cd.is_test_account = '0' /* Generated by Cortex */;
