-- Query ID: 01c39a3a-0212-6cb9-24dd-0703194227eb
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T22:18:08.311000+00:00
-- Elapsed: 1342ms
-- Environment: FBG

select ACCO_ID "Account ID", SUM_51 "sort-F_HBO-OcyI-0", IS_CASINO_VIP "Is Casino VIP", IS_VIP "Is Sports VIP", LOYALTY_TIER "Current Loyalty Tier", NEXT_LOYALTY_TIER "Next Loyalty Tier", VIP_HOST "Account Manager", LEAD_OWNER "Lead Owner", SUM_49 "Current Year Tier Points", SUM_47 "ONE Credit Balance", SUM_48 "Points to Next Tier" from (select ACCO_ID, LOYALTY_TIER, NEXT_LOYALTY_TIER, IS_VIP, IS_CASINO_VIP, VIP_HOST, LEAD_OWNER, SUM_47, SUM_48, SUM_49, SUM_51 from (select Q1.ACCO_ID, Q1.LOYALTY_TIER, Q1.NEXT_LOYALTY_TIER, Q1.IS_VIP, Q1.IS_CASINO_VIP, Q1.VIP_HOST, Q1.LEAD_OWNER, Q1.SUM_47, Q1.SUM_48, Q1.SUM_49, Q2.SUM_51, Q2.ACCO_ID_52 from (select ACCO_ID, LOYALTY_TIER, NEXT_LOYALTY_TIER, IS_VIP, IS_CASINO_VIP, VIP_HOST, LEAD_OWNER, sum(ONE_CREDIT_BALANCE) SUM_47, sum(iff(LOYALTY_TIER = 'ONEblack', null, case NEXT_LOYALTY_TIER when 'ONEmember pro' then 100 when 'ONEgold' then 2500 when 'ONEplatinum' then 10000 when 'ONEblack' then 20000 else null end - CURRENT_YEAR_TIER_POINTS)) SUM_48, sum(CURRENT_YEAR_TIER_POINTS) SUM_49 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.F1_ATTRIBUTES_REPORTING where VIP_HOST is null and LEAD_OWNER is null and (not LEAD_OWNER in ('Taylor OBrien', 'Will Rolapp', 'Teddy Moeller', 'Pete Donahue', 'Michael Hermalyn', 'Michael Bernstein', 'Jack Shuster', 'Griffen Colton', 'Ekin VanWinkle', 'Darren OBrien', 'Admin User') or LEAD_OWNER is null) and LOYALTY_TIER is null and ACCO_ID = 299144 group by NEXT_LOYALTY_TIER, LOYALTY_TIER, VIP_HOST, LEAD_OWNER, ACCO_ID, IS_CASINO_VIP, IS_VIP) Q1 left join (select sum(case LOYALTY_TIER when 'Black' then 100 + CURRENT_YEAR_TIER_POINTS / 1000000 when 'Platinum' then 50 + CURRENT_YEAR_TIER_POINTS / 1000000 when 'Gold' then 10 + CURRENT_YEAR_TIER_POINTS / 1000000 when 'Member+' then 1 + CURRENT_YEAR_TIER_POINTS / 1000000 when 'Member' then CURRENT_YEAR_TIER_POINTS / 1000000 else 0 end) SUM_51, ACCO_ID ACCO_ID_52 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.F1_ATTRIBUTES_REPORTING where VIP_HOST is null and LEAD_OWNER is null and (not LEAD_OWNER in ('Taylor OBrien', 'Will Rolapp', 'Teddy Moeller', 'Pete Donahue', 'Michael Hermalyn', 'Michael Bernstein', 'Jack Shuster', 'Griffen Colton', 'Ekin VanWinkle', 'Darren OBrien', 'Admin User') or LEAD_OWNER is null) and LOYALTY_TIER is null and ACCO_ID = 299144 group by ACCO_ID) Q2 on equal_null(Q1.ACCO_ID, Q2.ACCO_ID_52) order by Q2.SUM_51 desc nulls last, Q1.ACCO_ID asc, Q1.IS_CASINO_VIP asc, Q1.IS_VIP asc, Q1.LOYALTY_TIER asc, Q1.NEXT_LOYALTY_TIER asc, Q1.VIP_HOST asc, Q1.LEAD_OWNER asc limit 10001) Q4) Q5 order by SUM_51 desc nulls last, ACCO_ID asc, IS_CASINO_VIP asc, IS_VIP asc, LOYALTY_TIER asc, NEXT_LOYALTY_TIER asc, VIP_HOST asc, LEAD_OWNER asc limit 10001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/workbook/FanaticsONE-Tier-Point-Tracker-34xRCyFUIYDTAc49GkmZLs?:displayNodeId=scErs5PAoP","kind":"adhoc","request-id":"g019d7452f3cb795b8322f60213732278","user-id":"3iAxZuQ3G72Y9oDKqtSqeCAlzlGuU","email":"phurpa.sherpa@betfanatics.com"}
