-- Query ID: 01c39a0c-0212-6b00-24dd-07031937a49f
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T21:32:53.126000+00:00
-- Elapsed: 449ms
-- Environment: FBG

select CAST_30 "Bus Date", ACTIVES "Daily Cash Actives", FTUS "FTUS (Daily Actuals)", CASH_HANDLE "Daily Cash Handle", TRADING_WIN "Daily Trading Win", TRADING_NGR "Daily Sportsbook NGR", TRADING_ENGR "Sportsbook eNGR", X_TRADING_WIN "Expected TW", RETENTION_COSTS_DAILY "Daily Retention Costs", ACQUISITION_COSTS_DAILY "Acquisition Costs Daily", MIGRATION_COSTS_DAILY "Daily Migration Costs", EXP_RETENTION_COSTS_DAILY "Exp Retention Costs Daily", EXP_ACQUISITION_COSTS_DAILY "Exp Acquisition Costs Daily", EXP_MIGRATION_COSTS_DAILY "Exp Migration Costs Daily", MTD_ACTIVES "Mtd Actives", NEW_UNIQUE_ACTIVES "NEW_UNIQUE_ACTIVES (Custom SQL Query)", PRIOR_MONTH_ACTIVES "PRIOR_MONTH_ACTIVES (Custom SQL Query1)", RETAINED_MTD "RETAINED_MTD (Custom SQL Query1)", CASH_GGR "Cash GGR", EXPECTED_GGR "Expected Ggr_daily forecast (custom sql)", BOOST_COST "Daily Boost Costs_daily forecast (custom sql)", EXP_BOOST_COST "Exp Boost Cost_daily forecast (custom sql)", FINANCE_REVENUE_DAILY "Finance Revenue Daily_daily forecast (custom sql)", EXP_FINANCE_REVENUE_DAILY "Exp Finance Revenue Daily", NEW_UNIQUE_ACTIVES_LY, DIV_27 "Daily Total eRTC", DIV_26 "Daily Total RTC", DIV_29 "Daily NGR %", EQ_28 "Calc", OSB_SEGMENT "OSB_SEGMENT (Custom SQL Query1)" from (select OSB_SEGMENT, ACTIVES, FTUS, CASH_HANDLE, TRADING_WIN, TRADING_NGR, TRADING_ENGR, X_TRADING_WIN, RETENTION_COSTS_DAILY, ACQUISITION_COSTS_DAILY, MIGRATION_COSTS_DAILY, EXP_RETENTION_COSTS_DAILY, EXP_ACQUISITION_COSTS_DAILY, EXP_MIGRATION_COSTS_DAILY, MTD_ACTIVES, NEW_UNIQUE_ACTIVES, PRIOR_MONTH_ACTIVES, RETAINED_MTD, CASH_GGR, EXPECTED_GGR, BOOST_COST, EXP_BOOST_COST, FINANCE_REVENUE_DAILY, EXP_FINANCE_REVENUE_DAILY, NEW_UNIQUE_ACTIVES_LY, RETENTION_COSTS_DAILY / nullif(CASH_GGR, 0) DIV_26, EXPECTED_GGR / nullif(EXPECTED_GGR, 0) DIV_27, BUS_DATE = to_date('2025-03-30', 'YYYY-MM-DD') EQ_28, TRADING_NGR / nullif(CASH_HANDLE, 0) DIV_29, BUS_DATE::timestamp_ltz CAST_30 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_DAILY_DS) Q1 limit 10001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-Sample-34rdU89t8adkDkUiTTTdmE?:displayNodeId=8gogQi5F7-","kind":"adhoc","request-id":"g019d74298b1e7c3ca2086f44a90127de","user-id":"RJPpDi9ofjj2luRLdu0geI6rWoD5l","email":"Brett.Pendleton@betfanatics.com"}
