-- Query ID: 01c39a36-0212-67a8-24dd-070319411f4b
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:14:42.872000+00:00
-- Elapsed: 3147ms
-- Environment: FBG

WITH __trading_sportsbook_mart AS (
  SELECT
    is_free_bet_wager,
    is_test_wager,
    market_grouping,
    wager_channel,
    wager_status,
    wager_settlement_time_alk,
    total_cash_ggr_by_legs,
    total_cash_stake_by_legs,
    wager_id
  FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
)
/* Verify the date range being used for T12M */
SELECT
  CURRENT_DATE AS today,
  DATEADD(YEAR, -1, CURRENT_DATE) AS twelve_months_ago,
  MIN(TO_DATE(wager_settlement_time_alk)) AS earliest_settlement,
  MAX(TO_DATE(wager_settlement_time_alk)) AS latest_settlement,
  COUNT(DISTINCT wager_id) AS num_bets,
  SUM(total_cash_stake_by_legs) AS cash_handle,
  SUM(total_cash_ggr_by_legs) AS cash_ggr,
  SUM(total_cash_ggr_by_legs) / NULLIF(NULLIF(SUM(total_cash_stake_by_legs), 0), 0) AS cash_hold_pct
FROM __trading_sportsbook_mart
WHERE
  wager_status IN ('ACCEPTED', 'SETTLED')
  AND wager_channel = 'INTERNET'
  AND is_test_wager = 'FALSE'
  AND is_free_bet_wager = 'FALSE'
  AND market_grouping = 'OTHER - LIGHTNING MARKETS'
  AND TO_DATE(wager_settlement_time_alk) >= DATEADD(YEAR, -1, CURRENT_DATE)
  AND TO_DATE(wager_settlement_time_alk) <= CURRENT_DATE /* Generated by Cortex */;
