-- Query ID: 01c39a46-0212-6dbe-24dd-07031944746b
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:30:10.523000+00:00
-- Elapsed: 4594ms
-- Environment: FBG

WITH __customer_mart AS (
  SELECT
    acquisition_channel,
    casino_cluster,
    casino_game_preference,
    current_casino_tier,
    current_casino_value,
    f1_loyalty_tier,
    first_bet_state,
    is_pvip,
    is_vip,
    max_casino_tier,
    max_casino_value,
    platform,
    product_preference,
    registration_product,
    status,
    casino_ftu_date_alk,
    first_deposit_date_alk,
    last_login_time_alk,
    registration_date_alk,
    acco_id,
    casino_first_cash_bet_amount,
    casino_played_days
  FROM FBG_ANALYTICS_ENGINEERING.CUSTOMERS.CUSTOMER_MART
)
/* Customer profile information */
SELECT
  cm.acco_id,
  cm.casino_cluster,
  cm.casino_game_preference,
  cm.current_casino_tier,
  cm.current_casino_value,
  cm.max_casino_tier,
  cm.max_casino_value,
  cm.f1_loyalty_tier,
  cm.is_vip,
  cm.is_pvip,
  cm.product_preference,
  cm.platform,
  cm.registration_product,
  cm.status,
  cm.casino_played_days,
  cm.casino_first_cash_bet_amount,
  cm.casino_ftu_date_alk,
  cm.first_deposit_date_alk,
  cm.registration_date_alk,
  cm.last_login_time_alk,
  cm.first_bet_state,
  cm.acquisition_channel
FROM __customer_mart AS cm
WHERE
  cm.acco_id = '2144018' /* Generated by Cortex */;
