-- Query ID: 01c399c8-0212-67a8-24dd-07031927db23
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:24:23.404000+00:00
-- Elapsed: 76ms
-- Environment: FBG

with W1 as (select Q2.WEEK_DATE, Q2.USER_SEGMENT, count(Q3.USER_SEGMENT) COUNT_29 from (select WEEK_DATE, USER_SEGMENT from (select WEEK_DATE, USER_SEGMENT, row_number() over (partition by USER_SEGMENT, WEEK_DATE order by '' asc) ROWNUMBER_16 from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_WEEKLY_FORECAST qualify ROWNUMBER_16 = 1) Q1) Q2 left join (select NEW_SEGMENTS_WEEKLY_RETENTION.WEEK_DATE, NEW_SEGMENTS_WEEKLY_RETENTION.USER_SEGMENT from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_WEEKLY_RETENTION right join (select HIGH_LEVEL_SEGMENT, SPORTSLIFECYCLE, CHURN_WEEK::timestamp_ltz CAST_28 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_WEEKLY_RETENTION_DS) Q4 on try_to_timestamp_ltz(NEW_SEGMENTS_WEEKLY_RETENTION.WEEK_DATE) = Q4.CAST_28 and NEW_SEGMENTS_WEEKLY_RETENTION.USER_SEGMENT = Q4.HIGH_LEVEL_SEGMENT and NEW_SEGMENTS_WEEKLY_RETENTION.LIFECYCLE = Q4.SPORTSLIFECYCLE) Q3 on Q2.USER_SEGMENT = Q3.USER_SEGMENT and Q2.WEEK_DATE = Q3.WEEK_DATE group by Q2.USER_SEGMENT, Q2.WEEK_DATE) select COUNT_36 "Count of User Segment", SUM_37 "CountIf of Calc", SUM_38 "CountIf of Calc (1)", SUM_39 "CountIf of Calc (2)", USER_SEGMENT "User Segment", WEEK_DATE "Week Date", GT_30 "__cond_JOIN_AGGR_MULTI_MATCHED_CF", EQ_31 "__cond_JOIN_AGGR_UNMATCHED_CF" from (select Q10.WEEK_DATE, Q10.USER_SEGMENT, Q10.GT_30, Q10.EQ_31, Q12.COUNT_36, Q12.SUM_37, Q12.SUM_38, Q12.SUM_39 from (select WEEK_DATE, USER_SEGMENT, COUNT_29 > 1 GT_30, COUNT_29 = 0 EQ_31 from (select * from W1 Q8 order by USER_SEGMENT asc, WEEK_DATE asc limit 10001) Q9) Q10 cross join (select count(USER_SEGMENT) COUNT_36, sum(iff(COUNT_29 = 0, 1, 0)) SUM_37, sum(iff(COUNT_29 = 1, 1, 0)) SUM_38, sum(iff(COUNT_29 > 1, 1, 0)) SUM_39 from W1 Q11) Q12) Q14 order by USER_SEGMENT asc, WEEK_DATE asc limit 10001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-1-34rdU89t8adkDkUiTTTdmE?:displayNodeId=oJJgYHF9Nq","kind":"adhoc","request-id":"g019d73ead0ea7c33a1dad87a5e5a5d8a","user-id":"L3vHZYjsyKujxXKFJJVEoOSTC4m5s","email":"sai.manish@squadrondata.com"}
