-- Query ID: 01c39a0e-0212-6e7d-24dd-07031938066b
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Executed: 2026-04-09T21:34:10.665000+00:00
-- Elapsed: 2176ms
-- Environment: FBG

SELECT 
  TO_CHAR(SPORTSBOOK_FTU_DATE_ALK, 'YYYY-MM') AS ftu_cohort,
  ROUND(AVG(FOOTBALL_CASH_BET_AMOUNT), 2) as avg_football,
  ROUND(AVG(BASKETBALL_CASH_BET_AMOUNT), 2) as avg_basketball,
  ROUND(AVG(BASEBALL_CASH_BET_AMOUNT), 2) as avg_baseball,
  ROUND(AVG(HOCKEY_CASH_BET_AMOUNT), 2) as avg_hockey,
  ROUND(AVG(SOCCER_CASH_BET_AMOUNT), 2) as avg_soccer,
  ROUND(AVG(TENNIS_CASH_BET_AMOUNT), 2) as avg_tennis,
  ROUND(AVG(GOLF_CASH_BET_AMOUNT), 2) as avg_golf,
  ROUND(AVG(OTHER_CASH_BET_AMOUNT), 2) as avg_other,
  ROUND(AVG(FOOTBALL_CASH_BET_AMOUNT) / NULLIF(AVG(CASH_BET_AMOUNT), 0) * 100, 1) as pct_football,
  ROUND(AVG(BASKETBALL_CASH_BET_AMOUNT) / NULLIF(AVG(CASH_BET_AMOUNT), 0) * 100, 1) as pct_basketball,
  ROUND(AVG(BASEBALL_CASH_BET_AMOUNT) / NULLIF(AVG(CASH_BET_AMOUNT), 0) * 100, 1) as pct_baseball,
  ROUND(AVG(SOCCER_CASH_BET_AMOUNT) / NULLIF(AVG(CASH_BET_AMOUNT), 0) * 100, 1) as pct_soccer,
  ROUND(AVG(TENNIS_CASH_BET_AMOUNT) / NULLIF(AVG(CASH_BET_AMOUNT), 0) * 100, 1) as pct_tennis
FROM fbg_analytics_dev.product_and_customer.SPORTSBOOK_LTV_90DAYS_V2
GROUP BY 1
ORDER BY 1
