-- Query ID: 01c399c6-0212-67a9-24dd-07031927f043
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Executed: 2026-04-09T20:22:33.814000+00:00
-- Elapsed: 735ms
-- Environment: FBG

SELECT 'In CDNA not in FMX' AS DIRECTION, CRYPTO.PROCESS_DATE
FROM FBG_SOURCE.CRYPTO.TSP_EOD_SUMMARY CRYPTO
LEFT JOIN FBG_FINANCE.STAGING.FMX_RECONCILIATION_REPORT_DAILY FMX
  ON CRYPTO.PROCESS_DATE = FMX.TRANS_DATE_EST
WHERE FMX.TRANS_DATE_EST IS NULL
UNION ALL
SELECT 'In FMX not in CDNA' AS DIRECTION, FMX.TRANS_DATE_EST
FROM FBG_FINANCE.STAGING.FMX_RECONCILIATION_REPORT_DAILY FMX
LEFT JOIN FBG_SOURCE.CRYPTO.TSP_EOD_SUMMARY CRYPTO
  ON FMX.TRANS_DATE_EST = CRYPTO.PROCESS_DATE
WHERE CRYPTO.PROCESS_DATE IS NULL
ORDER BY 2 DESC
