-- Query ID: 01c399c3-0212-6dbe-24dd-07031926afd3
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Executed: 2026-04-09T20:19:19.877000+00:00
-- Elapsed: 99ms
-- Environment: FBG

WITH daily AS (
    SELECT
        WAGER_PLACED_TIME_EST::DATE AS BET_DATE,
        COUNT(DISTINCT BET_ID)       AS BETS,
        COUNT(DISTINCT ACCO_ID)      AS UNIQUE_BETTORS,
        SUM(HANDLE)                  AS HANDLE,
        SUM(GGR)                     AS GGR,
        SUM(TW)                      AS TOTAL_WINS,
        SUM(XGGR)                    AS EXPECTED_GGR,
        ROUND(CASE WHEN SUM(HANDLE) > 0 THEN SUM(GGR) / SUM(HANDLE) * 100 END, 2) AS GGR_MARGIN_PCT,
        ROUND(CASE WHEN SUM(HANDLE) > 0 THEN SUM(XGGR) / SUM(HANDLE) * 100 END, 2) AS EXPECTED_GGR_MARGIN_PCT
    FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SQUAD_BETS_TRADING_MART
    WHERE COMP = 'NHL'
      AND STATUS = 'SETTLED'
    GROUP BY 1
)
SELECT
    BET_DATE,
    BETS,
    UNIQUE_BETTORS,
    ROUND(HANDLE, 2)        AS DAILY_HANDLE,
    ROUND(GGR, 2)           AS DAILY_GGR,
    ROUND(TOTAL_WINS, 2)    AS DAILY_TW,
    ROUND(EXPECTED_GGR, 2)  AS DAILY_XGGR,
    GGR_MARGIN_PCT          AS DAILY_GGR_MARGIN_PCT,
    EXPECTED_GGR_MARGIN_PCT AS DAILY_XGGR_MARGIN_PCT,
    SUM(BETS)        OVER (ORDER BY BET_DATE)               AS CUM_BETS,
    SUM(HANDLE)      OVER (ORDER BY BET_DATE)               AS CUM_HANDLE,
    ROUND(SUM(GGR)   OVER (ORDER BY BET_DATE), 2)           AS CUM_GGR,
    ROUND(SUM(TOTAL_WINS) OVER (ORDER BY BET_DATE), 2)      AS CUM_TW,
    ROUND(SUM(EXPECTED_GGR) OVER (ORDER BY BET_DATE), 2)    AS CUM_XGGR,
    ROUND(CASE WHEN SUM(HANDLE) OVER (ORDER BY BET_DATE) > 0
          THEN SUM(GGR) OVER (ORDER BY BET_DATE) / SUM(HANDLE) OVER (ORDER BY BET_DATE) * 100 END, 2)
          AS CUM_GGR_MARGIN_PCT,
    ROUND(CASE WHEN SUM(HANDLE) OVER (ORDER BY BET_DATE) > 0
          THEN SUM(EXPECTED_GGR) OVER (ORDER BY BET_DATE) / SUM(HANDLE) OVER (ORDER BY BET_DATE) * 100 END, 2)
          AS CUM_XGGR_MARGIN_PCT
FROM daily
ORDER BY BET_DATE
