-- Query ID: 01c399cc-0212-67a9-24dd-070319287f5b
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:28:15.403000+00:00
-- Elapsed: 789ms
-- Environment: FBG

select COUNTDISTINCT_58 "CountDistinct of Case Id", DIV_65 "Abandonment %", DIV_66 "Bot Resolution % (update)", DIV_67 "Containment %", MEDIAN_59 "Median of Bot Handle Time" from (select count(distinct CASE_ID) COUNTDISTINCT_58, median(abs(datediff(second, coalesce(least(LAST_BOT_MESSAGE_TIME::timestamp_ltz, FIRST_AGENT_MESSAGE_TIME::timestamp_ltz), LAST_BOT_MESSAGE_TIME::timestamp_ltz), FIRST_MESSAGE_TIME::timestamp_ltz)) / 60) MEDIAN_59, sum(iff(RESOLUTION = 'Abandoned', 1, 0)) / nullif(COUNTDISTINCT_58, 0) DIV_65, count(distinct iff(RESOLUTION = 'Bot Resolved', CASE_ID, null)) / nullif(count(distinct iff(RESOLUTION = 'Bot Resolved', CASE_ID, null)) + count(distinct iff(RESOLUTION = 'Bot Unresolved', CASE_ID, null)), 0) DIV_66, sum(CONTAINMENT) / nullif(COUNTDISTINCT_58, 0) DIV_67 from FBG_ANALYTICS.OPERATIONS.CHATBOT_CASES where date_trunc(day, CASE_CREATED_EST::timestamp_ltz) < to_timestamp_ltz('2026-04-09T00:00:00.000000000+00:00', 'YYYY-MM-DDTHH24:MI:SS.FF9TZH:TZM') and CASE_TYPE in ('Account', 'Withdrawal', 'Deposit', 'Responsible Gaming', 'Taxes', 'FanaticsONE', 'FanApp', 'FanCash', 'Casino Payout', 'Casino Credit', 'Casino Errors') and RESOLUTION in ('Bot Resolved', 'Bot Created Email Case', 'Agent Resolved', 'Bot Completed', 'Bot Unresolved', 'Agent Completed', 'Full Unresolved', 'Abandoned') and case IS_AI_AGENT when 'False' then 'Chatbot' when 'True' then 'AI Agent' else null end is not null and date_trunc(day, CASE_CREATED_EST::timestamp_ltz) >= to_timestamp_ltz('2026-04-02T00:00:00.000000000+00:00', 'YYYY-MM-DDTHH24:MI:SS.FF9TZH:TZM') and date_trunc(day, CASE_CREATED_EST::timestamp_ltz) <= to_timestamp_ltz('2026-04-09T23:59:59.999000000+00:00', 'YYYY-MM-DDTHH24:MI:SS.FF9TZH:TZM')) Q1

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/workbook/Net-Zero-Health-Dashboard-3LBzlYO0NmPkyIBsM3GWZp?:displayNodeId=qZmKz_dkKO","kind":"adhoc","request-id":"g019d73ee5fbc75cd9090946be8afb3e7","user-id":"FtGGBxLcALxCM9j7UBd51zQIMS7qp","email":"neshat.mohammadi@betfanatics.com"}
