-- Query ID: 01c399c7-0212-6dbe-24dd-07031927ba1f
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T20:23:00.492000+00:00
-- Elapsed: 1688ms
-- Environment: FBG

WITH __cs_cases AS (
  SELECT
    case_id,
    case_type,
    chat_full_transcript,
    is_ai_agent,
    product_flag,
    csat_score,
    is_contained,
    is_escalated
  FROM FBG_ANALYTICS.OPERATIONS.CS_CASES
)
/* Break down the transcript-matched cases by case_type to see which types are most impacted */
SELECT
  case_type,
  COUNT(DISTINCT case_id) AS total_cases,
  SUM(CASE WHEN is_contained = 1 THEN 1 ELSE 0 END) AS contained,
  ROUND(
    SUM(CASE WHEN is_contained = 1 THEN 1 ELSE 0 END) / NULLIF(NULLIF(COUNT(DISTINCT case_id), 0), 0),
    4
  ) AS containment_rate,
  SUM(CASE WHEN is_escalated = 1 THEN 1 ELSE 0 END) AS escalated,
  ROUND(
    SUM(CASE WHEN is_escalated = 1 THEN 1 ELSE 0 END) / NULLIF(NULLIF(COUNT(DISTINCT case_id), 0), 0),
    4
  ) AS escalation_rate,
  ROUND(AVG(csat_score), 2) AS avg_csat
FROM __cs_cases
WHERE
  is_ai_agent = 'True'
  AND product_flag = 'Casino'
  AND (
    chat_full_transcript ILIKE '%wager history%'
    OR chat_full_transcript ILIKE '%wagering history%'
    OR chat_full_transcript ILIKE '%bet history%'
    OR chat_full_transcript ILIKE '%casino credit%'
    OR chat_full_transcript ILIKE '%casino balance%'
    OR chat_full_transcript ILIKE '%account balance%'
    OR chat_full_transcript ILIKE '%my balance%'
    OR chat_full_transcript ILIKE '%my wager%'
    OR chat_full_transcript ILIKE '%my bet%'
    OR chat_full_transcript ILIKE '%transaction history%'
    OR chat_full_transcript ILIKE '%play history%'
    OR chat_full_transcript ILIKE '%game history%'
    OR chat_full_transcript ILIKE '%recent wager%'
    OR chat_full_transcript ILIKE '%recent bet%'
    OR chat_full_transcript ILIKE '%bonus balance%'
    OR chat_full_transcript ILIKE '%promo balance%'
    OR chat_full_transcript ILIKE '%promotional credit%'
    OR chat_full_transcript ILIKE '%free credit%'
    OR chat_full_transcript ILIKE '%slot history%'
    OR chat_full_transcript ILIKE '%spin history%'
  )
GROUP BY
  case_type
ORDER BY
  total_cases DESC /* Generated by Cortex */;
