-- Query ID: 01c399d9-0212-67a8-24dd-0703192b8a4f
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T20:41:05.937000+00:00
-- Elapsed: 2929ms
-- Environment: FBG

WITH __trading_sportsbook_mart AS (
  SELECT
    account_id,
    event_name,
    is_live_bet_leg,
    wager_channel,
    wager_status,
    event_time_alk,
    total_cash_ggr_by_legs,
    total_cash_stake_by_legs,
    total_ggr_by_legs,
    total_stake_by_legs,
    wager_id
  FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
), __customer_mart AS (
  SELECT
    is_test_account,
    acco_id
  FROM FBG_ANALYTICS_ENGINEERING.CUSTOMERS.CUSTOMER_MART
)
SELECT
  CASE WHEN t.is_live_bet_leg = TRUE THEN 'Live' ELSE 'Pre-Game' END AS bet_timing,
  COUNT(DISTINCT t.wager_id) AS total_wagers,
  SUM(t.total_stake_by_legs) AS total_handle,
  SUM(t.total_cash_stake_by_legs) AS cash_handle,
  SUM(t.total_ggr_by_legs) AS total_ggr,
  SUM(t.total_cash_ggr_by_legs) AS cash_ggr
FROM __trading_sportsbook_mart AS t
INNER JOIN __customer_mart AS c
  ON t.account_id = c.acco_id
WHERE
  t.wager_status IN ('ACCEPTED', 'SETTLED')
  AND c.is_test_account = FALSE
  AND t.wager_channel = 'INTERNET'
  AND TO_DATE(t.event_time_alk) = CURRENT_DATE
  AND t.event_name ILIKE '%Michigan%'
  AND t.event_name ILIKE '%Denver%'
GROUP BY
  bet_timing
ORDER BY
  total_handle DESC NULLS LAST /* Generated by Cortex */;
