-- Query ID: 01c39a15-0212-6e7d-24dd-07031939acdf
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Executed: 2026-04-09T21:41:11.385000+00:00
-- Elapsed: 2245ms
-- Environment: FBG

SELECT 
    LEG_MARKET_TYPE AS MARKET_CODE,
    ANY_VALUE(LEG_MARKET) AS EXAMPLE_MARKET_NAME,
    COUNT(*) AS BET_COUNT
FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
WHERE EVENT_SPORT_NAME ILIKE '%soccer%'
  AND WAGER_PLACED_TIME_EST >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY LEG_MARKET_TYPE
ORDER BY BET_COUNT DESC
