-- Query ID: 01c399c8-0212-67a9-24dd-07031927f973
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:24:02.316000+00:00
-- Elapsed: 110ms
-- Environment: FBG

select WEEK_DATE "Week Date", USER_SEGMENT "User Segment", LIFECYCLE "Lifecycle", ACTIVES_LAST_WEEK "Actives Last Week", OF_WHICH_ACTIVE_THIS_WEEK "Of Which Active This Week", DW_LAST_UPDATED "Dw Last Updated", HIGH_LEVEL_SEGMENT "High Level Segment", CAST_11 "Churn Week", SPORTSLIFECYCLE "Sportslifecycle", ACTIVESLASTWEEK "Activeslastweek", OFWHICHACTIVETHISWEEK "Ofwhichactivethisweek" from (select NEW_SEGMENTS_WEEKLY_RETENTION.WEEK_DATE, NEW_SEGMENTS_WEEKLY_RETENTION.USER_SEGMENT, NEW_SEGMENTS_WEEKLY_RETENTION.LIFECYCLE, NEW_SEGMENTS_WEEKLY_RETENTION.ACTIVES_LAST_WEEK, NEW_SEGMENTS_WEEKLY_RETENTION.OF_WHICH_ACTIVE_THIS_WEEK, NEW_SEGMENTS_WEEKLY_RETENTION.DW_LAST_UPDATED, Q2.HIGH_LEVEL_SEGMENT, Q2.SPORTSLIFECYCLE, Q2.ACTIVESLASTWEEK, Q2.OFWHICHACTIVETHISWEEK, Q2.CAST_11 from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_WEEKLY_RETENTION right join (select HIGH_LEVEL_SEGMENT, SPORTSLIFECYCLE, ACTIVESLASTWEEK, OFWHICHACTIVETHISWEEK, CHURN_WEEK::timestamp_ltz CAST_11 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_WEEKLY_RETENTION_DS) Q2 on try_to_timestamp_ltz(NEW_SEGMENTS_WEEKLY_RETENTION.WEEK_DATE) = Q2.CAST_11 and NEW_SEGMENTS_WEEKLY_RETENTION.USER_SEGMENT = Q2.HIGH_LEVEL_SEGMENT and NEW_SEGMENTS_WEEKLY_RETENTION.LIFECYCLE = Q2.SPORTSLIFECYCLE) Q1 limit 131001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-1-34rdU89t8adkDkUiTTTdmE?:displayNodeId=FLIThpx7-y","kind":"adhoc","request-id":"g019d73ea83427eae9fdb93e829842846","user-id":"L3vHZYjsyKujxXKFJJVEoOSTC4m5s","email":"sai.manish@squadrondata.com"}
