-- Query ID: 01c39a15-0212-67a9-24dd-07031939f1cb
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Executed: 2026-04-09T21:41:07.310000+00:00
-- Elapsed: 4651ms
-- Environment: FBG

SELECT 
    LEG_MARKET_TYPE AS MARKET_CODE,
    COUNT(DISTINCT LEG_MARKET) AS DISTINCT_MARKET_VARIANTS,
    ANY_VALUE(LEG_MARKET) AS EXAMPLE_MARKET_NAME
FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
WHERE EVENT_SPORT_NAME ILIKE '%soccer%'
  AND WAGER_PLACED_TIME_EST >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY LEG_MARKET_TYPE
ORDER BY DISTINCT_MARKET_VARIANTS DESC
