-- Query ID: 01c39a41-0212-6e7d-24dd-070319434c33
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:25:16.246000+00:00
-- Elapsed: 235ms
-- Environment: FBG

WITH __casino_daily_settled_agg AS (
  SELECT
    acco_id,
    game_id,
    settled_date_alk,
    cash_bet_stake,
    ggr,
    is_test_account,
    ngr,
    total_bet_count,
    total_stake
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_DAILY_SETTLED_AGG
)
/* Daily trend last 30 days */
SELECT
  cd.settled_date_alk AS play_date,
  SUM(cd.total_stake) AS daily_handle,
  SUM(cd.cash_bet_stake) AS daily_cash_handle,
  SUM(cd.ggr) AS daily_ggr,
  SUM(cd.ngr) AS daily_ngr,
  SUM(cd.total_bet_count) AS daily_bets,
  COUNT(DISTINCT cd.game_id) AS games_played
FROM __casino_daily_settled_agg AS cd
WHERE
  cd.acco_id = '2144018'
  AND cd.settled_date_alk >= DATEADD(DAY, -30, CURRENT_DATE)
  AND cd.is_test_account = '0'
GROUP BY
  cd.settled_date_alk
ORDER BY
  cd.settled_date_alk DESC NULLS LAST /* Generated by Cortex */;
