-- Query ID: 01c399c7-0212-67a8-24dd-07031927d91b
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T20:23:47.793000+00:00
-- Elapsed: 779ms
-- Environment: FBG

WITH __cs_cases AS (
  SELECT
    case_id,
    case_type,
    chat_full_transcript,
    is_ai_agent,
    product_flag,
    case_created_est,
    is_contained,
    is_escalated
  FROM FBG_ANALYTICS.OPERATIONS.CS_CASES
), baseline AS (
  SELECT
    COUNT(DISTINCT case_id) AS total_ai_casino_cases,
    SUM(CASE WHEN is_contained = 1 THEN 1 ELSE 0 END) AS current_contained,
    ROUND(
      SUM(CASE WHEN is_contained = 1 THEN 1 ELSE 0 END) / NULLIF(NULLIF(COUNT(DISTINCT case_id), 0), 0),
      4
    ) AS current_containment_rate,
    SUM(CASE WHEN is_escalated = 1 THEN 1 ELSE 0 END) AS current_escalated,
    ROUND(
      SUM(CASE WHEN is_escalated = 1 THEN 1 ELSE 0 END) / NULLIF(NULLIF(COUNT(DISTINCT case_id), 0), 0),
      4
    ) AS current_escalation_rate
  FROM __cs_cases
  WHERE
    is_ai_agent = 'True'
    AND product_flag = 'Casino'
    AND case_created_est >= DATEADD(MONTH, -3, CURRENT_DATE)
), impacted AS (
  SELECT
    COUNT(DISTINCT case_id) AS impacted_cases,
    SUM(CASE WHEN is_contained = 1 THEN 1 ELSE 0 END) AS currently_contained,
    SUM(CASE WHEN is_contained = 0 THEN 1 ELSE 0 END) AS currently_not_contained,
    SUM(CASE WHEN is_escalated = 1 THEN 1 ELSE 0 END) AS currently_escalated
  FROM __cs_cases
  WHERE
    is_ai_agent = 'True'
    AND product_flag = 'Casino'
    AND case_created_est >= DATEADD(MONTH, -3, CURRENT_DATE)
    AND (
      chat_full_transcript ILIKE '%wager history%'
      OR chat_full_transcript ILIKE '%wagering history%'
      OR chat_full_transcript ILIKE '%bet history%'
      OR chat_full_transcript ILIKE '%casino credit%'
      OR chat_full_transcript ILIKE '%casino balance%'
      OR chat_full_transcript ILIKE '%account balance%'
      OR chat_full_transcript ILIKE '%my balance%'
      OR chat_full_transcript ILIKE '%my wager%'
      OR chat_full_transcript ILIKE '%my bet%'
      OR chat_full_transcript ILIKE '%transaction history%'
      OR chat_full_transcript ILIKE '%play history%'
      OR chat_full_transcript ILIKE '%game history%'
      OR chat_full_transcript ILIKE '%recent wager%'
      OR chat_full_transcript ILIKE '%recent bet%'
      OR chat_full_transcript ILIKE '%bonus balance%'
      OR chat_full_transcript ILIKE '%promo balance%'
      OR chat_full_transcript ILIKE '%promotional credit%'
      OR chat_full_transcript ILIKE '%free credit%'
      OR chat_full_transcript ILIKE '%slot history%'
      OR chat_full_transcript ILIKE '%spin history%'
      OR case_type = 'Casino Credit'
    )
)
SELECT
  b.total_ai_casino_cases,
  b.current_contained,
  b.current_containment_rate,
  b.current_escalated,
  b.current_escalation_rate,
  i.impacted_cases,
  i.currently_contained AS impacted_currently_contained,
  i.currently_not_contained AS impacted_not_contained,
  i.currently_escalated AS impacted_currently_escalated,
  ROUND(i.impacted_cases / NULLIF(NULLIF(b.total_ai_casino_cases, 0), 0), 4) AS pct_of_total_volume,
  ROUND(i.impacted_cases * 0.70) AS projected_impacted_contained_at_70pct, /* If we achieve 70% containment on the impacted pool */
  ROUND(i.impacted_cases * 0.70) - i.currently_contained AS net_new_contained,
  ROUND(
    (
      b.current_contained + (
        ROUND(i.impacted_cases * 0.70) - i.currently_contained
      )
    ) / NULLIF(NULLIF(b.total_ai_casino_cases, 0), 0),
    4
  ) AS projected_containment_rate, /* New overall containment rate */
  ROUND(i.currently_escalated * 0.15) AS projected_escalation_reduction, /* Escalation reduction (15% reduction target) */
  b.current_escalated - ROUND(i.currently_escalated * 0.15) AS projected_new_escalated,
  ROUND(
    (
      b.current_escalated - ROUND(i.currently_escalated * 0.15)
    ) / NULLIF(NULLIF(b.total_ai_casino_cases, 0), 0),
    4
  ) AS projected_escalation_rate
FROM baseline AS b, impacted AS i /* Generated by Cortex */;
