-- Query ID: 01c39a35-0212-6dbe-24dd-07031941223b
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:13:21.152000+00:00
-- Elapsed: 3779ms
-- Environment: FBG

WITH __trading_sportsbook_mart AS (
  SELECT
    account_id,
    is_free_bet_wager,
    is_test_wager,
    leg_sport_category,
    market_definition,
    market_grouping,
    wager_channel,
    wager_status,
    wager_settlement_time_alk,
    total_cash_ggr_by_legs,
    total_cash_stake_by_legs,
    wager_id
  FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
)
/* Trailing 12 month lightning market handle (Apr 2025 - Apr 2026) */
SELECT
  leg_sport_category AS sport,
  COUNT(DISTINCT market_definition) AS num_markets,
  COUNT(DISTINCT wager_id) AS num_bets,
  COUNT(DISTINCT account_id) AS num_bettors,
  SUM(total_cash_stake_by_legs) AS cash_handle,
  SUM(total_cash_ggr_by_legs) AS cash_ggr,
  SUM(total_cash_ggr_by_legs) / NULLIF(NULLIF(SUM(total_cash_stake_by_legs), 0), 0) AS cash_hold_pct
FROM __trading_sportsbook_mart
WHERE
  wager_status IN ('ACCEPTED', 'SETTLED')
  AND wager_channel = 'INTERNET'
  AND is_test_wager = 'FALSE'
  AND is_free_bet_wager = 'FALSE'
  AND market_grouping = 'OTHER - LIGHTNING MARKETS'
  AND TO_DATE(wager_settlement_time_alk) >= DATEADD(YEAR, -1, CURRENT_DATE)
  AND TO_DATE(wager_settlement_time_alk) <= CURRENT_DATE
GROUP BY
  1
ORDER BY
  cash_handle DESC /* Generated by Cortex */;
