-- Query ID: 01c399da-0212-67a8-24dd-0703192c01af
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:42:32.784000+00:00
-- Elapsed: 429ms
-- Environment: FBG

select COUNT_35 "Count of Actives", WEEK_NUMBER "Week Number", CAST_30 "Week Date", DATEPARSE_18 "DateParse of Calc", USER_SEGMENT "User Segment", ACTIVITY_SEGMENT "Activity Segment", CAST_21 "Actives", CAST_25 "Hpa", CAST_22 "Cash Handle", TRADING_WIN_PERCENT "Trading Win Percent", CAST_29 "Trading Win", RETENTION_RTC "Retention Rtc", CAST_20 "Acquisition Promo Cost", CAST_26 "Migration Cost", CAST_27 "Retention Cost", CAST_28 "Trading Ngr", CAST_23 "Cumulative Trading Ngr", CAST_24 "Dw Last Updated", WEEK_DATE "Week Date (1)", DATEADD_19 "Default Summary Week", V_17 "Default Summary Date", EQ_16 "Summary Week Flag", ACTIVES "Actives (1)", HPA_33 "Hpa (1)", CASH_HANDLE "Cash Handle (1)", TRADING_WIN "Trading Win (1)", ACQUISITION_PROMO_COST "Acquisition Promo Cost (1)", MIGRATION_COST "Migration Cost (1)", RETENTION_COST_32 "Retention Cost (1)", CUMULATIVE_TRADING_NGR "Cumulative Trading Ngr (1)", TRADING_NGR "Trading Ngr (1)", DW_LAST_UPDATED_31 "Dw Last Updated (1)" from (select Q2.WEEK_NUMBER, Q2.WEEK_DATE, Q2.USER_SEGMENT, Q2.ACTIVITY_SEGMENT, Q2.ACTIVES, Q2.CASH_HANDLE, Q2.TRADING_WIN_PERCENT, Q2.TRADING_WIN, Q2.RETENTION_RTC, Q2.ACQUISITION_PROMO_COST, Q2.MIGRATION_COST, Q2.TRADING_NGR, Q2.CUMULATIVE_TRADING_NGR, Q2.EQ_16, Q2.V_17, Q2.DATEPARSE_18, Q2.DATEADD_19, Q2.CAST_20, Q2.CAST_21, Q2.CAST_22, Q2.CAST_23, Q2.CAST_24, Q2.CAST_25, Q2.CAST_26, Q2.CAST_27, Q2.CAST_28, Q2.CAST_29, Q2.CAST_30, Q2.DW_LAST_UPDATED_31, Q2.RETENTION_COST_32, Q2.HPA_33, Q3.COUNT_35 from (select WEEK_NUMBER, WEEK_DATE, USER_SEGMENT, ACTIVITY_SEGMENT, ACTIVES, CASH_HANDLE, TRADING_WIN_PERCENT, TRADING_WIN, RETENTION_RTC, ACQUISITION_PROMO_COST, MIGRATION_COST, TRADING_NGR, CUMULATIVE_TRADING_NGR, try_to_timestamp_ltz(WEEK_DATE) = dateadd(day, 1, dateadd('day', -1, date_trunc(week, dateadd('day', 1, dateadd(day, -1, try_to_timestamp_ltz('1/1/2024')))))) EQ_16, to_timestamp_ltz('2026-04-08T00:00:00.000000000+00:00', 'YYYY-MM-DDTHH24:MI:SS.FF9TZH:TZM') V_17, try_to_timestamp_ltz('[Week Date]', 'DD"/"Mon"/"YYYY') DATEPARSE_18, dateadd(day, -6, dateadd('day', -1, date_trunc(week, dateadd('day', 1, to_timestamp_ltz('2026-04-09T00:00:00.000000000+00:00', 'YYYY-MM-DDTHH24:MI:SS.FF9TZH:TZM'))))) DATEADD_19, try_to_double(ACQUISITION_PROMO_COST) CAST_20, try_to_double(ACTIVES) CAST_21, try_to_double(CASH_HANDLE) CAST_22, try_to_double(CUMULATIVE_TRADING_NGR) CAST_23, try_to_timestamp_ltz(DW_LAST_UPDATED) CAST_24, try_to_double(HPA) CAST_25, try_to_double(MIGRATION_COST) CAST_26, try_to_double(RETENTION_COST) CAST_27, try_to_double(TRADING_NGR) CAST_28, try_to_double(TRADING_WIN) CAST_29, try_to_timestamp_ltz(WEEK_DATE) CAST_30, DW_LAST_UPDATED DW_LAST_UPDATED_31, RETENTION_COST RETENTION_COST_32, HPA HPA_33 from (select * from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_WEEKLY_FORECAST limit 36601) Q1) Q2 cross join (select count(try_to_double(ACTIVES)) COUNT_35 from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_WEEKLY_FORECAST) Q3) Q5 limit 36601

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-1-34rdU89t8adkDkUiTTTdmE?:displayNodeId=aL5HKQrqaP","kind":"adhoc","request-id":"g019d73fb73cb75ee9185e8920dd598a4","user-id":"L3vHZYjsyKujxXKFJJVEoOSTC4m5s","email":"sai.manish@squadrondata.com"}
