-- Query ID: 01c39a2f-0212-67a8-24dd-0703193fa1eb
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T22:07:36.671000+00:00
-- Elapsed: 17702ms
-- Environment: FBG

with W1 as (select avg(METRIC_VALUE) AVG_11, case METRIC_NAME when 'Agent Quality' then 'Agent' when 'Contained Bot Resolution' then 'Bot' else case METRIC_NAME when 'Payment Quality Score' then 'Payment' when 'Withdrawal Pend Time' then 'Withdrawal Pend' else METRIC_NAME end end SWITCH_12 from FBG_ANALYTICS.OPERATIONS.QUALITY_METRICS where METRIC_NAME in ('Agent Quality', 'Contained Bot Resolution', 'Payment Quality Score', 'Withdrawal Pend Time') and METRIC_DATE >= to_date('2026-03-22', 'YYYY-MM-DD') and METRIC_DATE <= to_date('2026-04-04', 'YYYY-MM-DD') group by SWITCH_12) select SWITCH_12 "Name", IF_23 "Score", NULL_EQ_21 from (select Q3.SWITCH_12, Q9.NULL_EQ_21, iff(Q9.NULL_EQ_21, Q9.MAX_20, null) IF_23 from (select * from W1 Q2 order by SWITCH_12 asc limit 10001) Q3 left join (select max(IF_17) MAX_20, equal_null(min(IF_17), MAX_20) NULL_EQ_21, SWITCH_9 SWITCH_10 from (select Q4.SWITCH_9, case when Q4.METRIC_NAME in ('Agent Quality', 'Contained Bot Resolution') or Q4.METRIC_NAME = 'Withdrawal Pend Time' then concat(coalesce(round(Q6.AVG_12 * 100, 2)::text, ''), '%') when Q4.METRIC_NAME = 'Payment Quality Score' then concat(coalesce(round(Q6.AVG_12, 2)::text, ''), '%') else round(Q6.AVG_12, 2)::text end IF_17 from (select METRIC_NAME, case METRIC_NAME when 'Agent Quality' then 'Agent' when 'Contained Bot Resolution' then 'Bot' else case METRIC_NAME when 'Payment Quality Score' then 'Payment' when 'Withdrawal Pend Time' then 'Withdrawal Pend' else METRIC_NAME end end SWITCH_9 from FBG_ANALYTICS.OPERATIONS.QUALITY_METRICS where METRIC_NAME in ('Agent Quality', 'Contained Bot Resolution', 'Payment Quality Score', 'Withdrawal Pend Time') and METRIC_DATE >= to_date('2026-03-22', 'YYYY-MM-DD') and METRIC_DATE <= to_date('2026-04-04', 'YYYY-MM-DD')) Q4 left join (select AVG_11 AVG_12, SWITCH_12 SWITCH_13 from W1 Q5) Q6 on equal_null(Q4.SWITCH_9, Q6.SWITCH_13)) Q8 group by SWITCH_9) Q9 on equal_null(Q3.SWITCH_12, Q9.SWITCH_10)) Q11 order by SWITCH_12 asc limit 10001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/workbook/Ops-Rubric-7hFWGd8C2Dse5B7IMBoAaB?:displayNodeId=bqrasW-mN_","kind":"adhoc","request-id":"g019d744956107473857d3b8d622fb684","user-id":"Q36uPgS6an5DT7qnPb06TRLfDwexE","email":"Annie.Frenette@betfanatics.com"}
