-- Query ID: 01c399e2-0212-67a9-24dd-0703192d2ae3
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:50:02.854000+00:00
-- Elapsed: 1616ms
-- Environment: FBG

select CAST_290 "Switch Date_Granularity_DM", DIV_303 "⭐  Launches per Active", V_301, DIV_304 "Cash Launches per Active", DIV_291 "% 1 Game Launch", DIV_292 "📌 % 2+ Game Launches", MEDIAN_293 "📌 Median", AVG_294 "Avg", PERCENTILECONT_295 P75, PERCENTILECONT_296 P90, DIV_297 "Session 1 Launch", DIV_298 "Session 2 Launches" from (select SESSION_WEEK_ALK::timestamp_ltz CAST_290, count(distinct iff(DISTINCT_GAME_LAUNCHES > 0, SESSION_UUID, null)) / nullif(count(distinct SESSION_UUID), 0) DIV_291, count(distinct iff(DISTINCT_GAME_LAUNCHES >= 2, SESSION_UUID, null)) / nullif(count(distinct SESSION_UUID), 0) DIV_292, median(iff(PRODUCT_NAME <> 'Web_app' and IS_LOBBY_FIRST_LAUNCH = 1, SECONDS_CASINO_INT_TO_FIRST_LAUNCH, null)) MEDIAN_293, avg(iff(PRODUCT_NAME <> 'Web_app' and IS_LOBBY_FIRST_LAUNCH = 1, SECONDS_CASINO_INT_TO_FIRST_LAUNCH, null)) AVG_294, percentile_cont(0.75) within group (order by iff(PRODUCT_NAME <> 'Web_app' and IS_LOBBY_FIRST_LAUNCH = 1, SECONDS_CASINO_INT_TO_FIRST_LAUNCH, null) asc) PERCENTILECONT_295, percentile_cont(0.9) within group (order by iff(PRODUCT_NAME <> 'Web_app' and IS_LOBBY_FIRST_LAUNCH = 1, SECONDS_CASINO_INT_TO_FIRST_LAUNCH, null) asc) PERCENTILECONT_296, sum(TRADING_NGR) / nullif(count(distinct iff(DISTINCT_GAME_LAUNCHES > 0, SESSION_UUID, null)), 0) DIV_297, sum(TRADING_NGR) / nullif(count(distinct iff(DISTINCT_GAME_LAUNCHES >= 2, SESSION_UUID, null)), 0) DIV_298, true V_301, sum(DISTINCT_GAME_LAUNCHES) / nullif(count(distinct iff(CASH_STAKE > 0, USER_ID, null)), 0) DIV_303, sum(CASH_CONVERTED_GAME_LAUNCHES) / nullif(count(distinct iff(CASH_STAKE > 0, USER_ID, null)), 0) DIV_304 from FBG_ANALYTICS.CASINO.PHH_CASINO_SESSIONS_TO_GAME_LAUNCHES_REPORT where not CASINO_SUPER_VIP and SESSION_DATE_ALK >= to_timestamp_ntz('2026-03-02 00:00:00.000000000', 'YYYY-MM-DD HH24:MI:SS.FF9') group by CAST_290) Q1 order by CAST_290 asc limit 25001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/workbook/Product-Health-Hub-5K7wHNcDUTxTnU49MXx3Xu?:displayNodeId=g0YYmwuYQl","kind":"adhoc","request-id":"g019d740252557e48ae7277fd1a6e28e9","user-id":"XFnSY8L83Bb6SJzIJ82MNBv1Jmmyp","email":"Jaime.Meek@betfanatics.com"}
