-- Query ID: 01c39a2b-0212-6dbe-24dd-0703193e8b33
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T22:03:15.394000+00:00
-- Elapsed: 4500ms
-- Environment: FBG

select AGENT_NAME "TopK Value", COUNT_330 "TopK Count", ISNULL_335 "TopK Null Sort", AGENT_NAME_336 "Text Seach Column" from (select AGENT_NAME, COUNT_330, AGENT_NAME is null ISNULL_335, AGENT_NAME AGENT_NAME_336 from (select AGENT_NAME, count(1) COUNT_330 from (select Q5.AGENT_NAME from (select AGENT_NAME, AGENT_ID, HOME_LOCATION, REPORTS_TO from (select distinct Q1.AGENT_NAME, Q1.AGENT_EMAIL, Q1.AGENT_ID, Q1.CASE_NUMBER, Q1.FCR, Q1.AGENT_HANDLE_TIME_MINUTES, Q1.DATETRUNC_14, Q2.HOME_LOCATION, Q2.REPORTS_TO, (Q1.ROSTERED_TOTAL_DURATION - (Q1.OUT_OF_ADHERENCE_DURATION - Q1.ADHERENCE_EXCEPTION_DURATION)) / nullif(Q1.ROSTERED_TOTAL_DURATION, 0) DIV_49, try_to_double(Q1.IF_19) CAST_53 from (select AGENT_NAME, AGENT_EMAIL, AGENT_ID, CASE_NUMBER, FCR, AGENT_HANDLE_TIME_MINUTES, ROSTERED_TOTAL_DURATION, OUT_OF_ADHERENCE_DURATION, ADHERENCE_EXCEPTION_DURATION, date_trunc(day, "DATE"::timestamp_ltz) DATETRUNC_14, iff("DATE"::timestamp_ltz = try_to_timestamp_ltz('2025-10-20'), null, DAILY_ADHERENCE_PERCENTAGE) IF_19 from FBG_ANALYTICS.OPERATIONS.CS_AGENT_LEADERBOARD where contains(lower(AGENT_NAME), lower('Shawn')) and date_trunc(day, "DATE"::timestamp_ltz) <= to_timestamp_ltz('2026-03-29T00:00:00.000000000+00:00', 'YYYY-MM-DDTHH24:MI:SS.FF9TZH:TZM') and date_trunc(day, "DATE"::timestamp_ltz) >= to_timestamp_ltz('2025-11-30T00:00:00.000000000+00:00', 'YYYY-MM-DDTHH24:MI:SS.FF9TZH:TZM')) Q1 left join FBG_ANALYTICS.OPERATIONS.AGENT_MASTER_ROSTER Q2 on Q1.AGENT_ID = Q2.SALESFORCE_ID) Q4) Q5 left join (select SALESFORCE_ID SALESFORCE_ID_118, max(AGENT_ID) MAX_119, equal_null(min(AGENT_ID), MAX_119) NULL_EQ_120 from (select distinct AGENT_ID, STATUS, SALESFORCE_ID from FBG_ANALYTICS.OPERATIONS.AGENT_MASTER_ROSTER) Q6 group by SALESFORCE_ID) Q7 on Q5.AGENT_ID = Q7.SALESFORCE_ID_118 group by Q5.AGENT_NAME, Q5.REPORTS_TO, Q5.HOME_LOCATION, try_to_double(iff(Q7.NULL_EQ_120, Q7.MAX_119, null))) Q9 group by AGENT_NAME) Q10) Q11 order by ISNULL_335 desc, COUNT_330 desc, AGENT_NAME asc limit 201

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/workbook/Leadership-Facing-Agent-Leaderboard-3hxHnWEukomA8yCKM4g7cj","kind":"adhoc","request-id":"g019d7445574574549f40dfe00e9cbc27","user-id":"7gh6Erd2nOvXrYqLJdYZsSzwdW8d6","email":"patrick.graham@betfanatics.com"}
