-- Query ID: 01c39a46-0212-6cb9-24dd-07031944a533
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:30:34.371000+00:00
-- Elapsed: 308ms
-- Environment: FBG

WITH __casino_daily_settled_agg AS (
  SELECT
    acco_id,
    state,
    settled_date_alk,
    ggr,
    is_test_account,
    ngr,
    total_stake
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_DAILY_SETTLED_AGG
)
/* State-level activity last 30 days */
SELECT
  cd.state,
  SUM(cd.total_stake) AS total_handle,
  SUM(cd.ggr) AS ggr,
  SUM(cd.ngr) AS ngr,
  COUNT(DISTINCT cd.settled_date_alk) AS active_days
FROM __casino_daily_settled_agg AS cd
WHERE
  cd.acco_id = '2144018'
  AND cd.is_test_account = '0'
  AND cd.settled_date_alk >= DATEADD(DAY, -30, CURRENT_DATE)
GROUP BY
  cd.state
ORDER BY
  total_handle DESC NULLS LAST /* Generated by Cortex */;
