-- Query ID: 01c39a3a-0212-67a8-24dd-0703194243a7
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:18:31.196000+00:00
-- Elapsed: 3883ms
-- Environment: FBG

WITH __trading_sportsbook_mart AS (
  SELECT
    is_free_bet_wager,
    is_test_wager,
    leg_sport_category,
    market_definition,
    market_grouping,
    wager_channel,
    wager_status,
    wager_settlement_time_alk,
    total_cash_ggr_by_legs,
    total_cash_stake_by_legs,
    wager_id
  FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
)
/* Get T12M hold % for each comparable market */
SELECT
  leg_sport_category AS sport,
  market_definition,
  COUNT(DISTINCT wager_id) AS num_bets,
  SUM(total_cash_stake_by_legs) AS cash_handle,
  SUM(total_cash_ggr_by_legs) AS cash_ggr,
  SUM(total_cash_ggr_by_legs) / NULLIF(NULLIF(SUM(total_cash_stake_by_legs), 0), 0) AS cash_hold_pct
FROM __trading_sportsbook_mart
WHERE
  wager_status IN ('ACCEPTED', 'SETTLED')
  AND wager_channel = 'INTERNET'
  AND is_test_wager = 'FALSE'
  AND is_free_bet_wager = 'FALSE'
  AND market_grouping = 'OTHER - LIGHTNING MARKETS'
  AND TO_DATE(wager_settlement_time_alk) >= DATEADD(YEAR, -1, CURRENT_DATE)
  AND TO_DATE(wager_settlement_time_alk) <= CURRENT_DATE
GROUP BY
  1,
  2
ORDER BY
  CASE leg_sport_category
    WHEN 'NFL'
    THEN 1
    WHEN 'NBA'
    THEN 2
    WHEN 'MLB'
    THEN 3
    WHEN 'CFB'
    THEN 4
    WHEN 'NCAA Basketball'
    THEN 5
    WHEN 'Soccer'
    THEN 6
  END,
  cash_handle DESC /* Generated by Cortex */;
