-- Query ID: 01c39a0b-0212-6dbe-24dd-070319371307
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T21:31:14.098000+00:00
-- Elapsed: 226ms
-- Environment: FBG

select WEEK_NUM_TARGET "Week Num Target", DATE_TARGET "Date Target", CASH_HANDLE_TARGET "Cash Handle Target", CAST_29 "Cash_Handle_Target", TRADING_WIN_TARGET "Trading Win Target", CAST_25 "Trading_Win_Target", TRADING_NGR_TARGET "Trading Ngr Target", CAST_34 "Trading_Ngr_Target", CAST_31 "Ftus Target", CAST_30 "Actives Target", CAST_32 "Mtd Actives Target", CAST_33 "New Unique Actives Target", AQUISITION_COSTS_TARGET "Aquisition Costs Target", CAST_23 "Aquisition_Costs_Target", RETENTION_COSTS_TARGET "Retention Costs Target", CAST_28 "Retention_Costs_Target", MIGRATION_COSTS_TARGET "Migration Costs Target", BOOST_COST_TARGET "Boost Cost Target", CAST_24 "Boost_Cost_Target", MTD_RETENTION "MTD RETENTION", DIV_27 "MTD_RETENTION (Daily Targets)", DW_LAST_UPDATED "Dw Last Updated", BOOST_COST_TARGET_26 "Boost Cost Target (copy)", SUB_19 "Cash GGR Target", SUB_16 "Cash GGR Target (copy)", ADD_20 "eNGR w/o Acq Target", ADD_15 "Promo Cost Target", ADD_21 "Promo Cost Target (copy)", CAST_17 "Trading Ngr Target (copy)", CAST_18 "Trading Ngr Target (copy) (copy)", CAST_22 "Trading Win Target (copy)" from (select WEEK_NUM_TARGET, DATE_TARGET, CASH_HANDLE_TARGET, TRADING_WIN_TARGET, TRADING_NGR_TARGET, AQUISITION_COSTS_TARGET, RETENTION_COSTS_TARGET, MIGRATION_COSTS_TARGET, BOOST_COST_TARGET, MTD_RETENTION, DW_LAST_UPDATED, try_to_double(replace(replace(AQUISITION_COSTS_TARGET, '$', ''), ',', '')) + try_to_double(replace(replace(RETENTION_COSTS_TARGET, '$', ''), ',', '')) ADD_15, try_to_double(replace(replace(TRADING_WIN_TARGET, '$', ''), ',', '')) - try_to_double(replace(replace(BOOST_COST_TARGET, '$', ''), ',', '')) SUB_16, try_to_double(replace(replace(TRADING_NGR_TARGET, '$', ''), ',', '')) CAST_17, CAST_17 CAST_18, SUB_16 SUB_19, CAST_17 + try_to_double(replace(replace(AQUISITION_COSTS_TARGET, '$', ''), ',', '')) ADD_20, ADD_15 ADD_21, try_to_double(replace(replace(TRADING_WIN_TARGET, '$', ''), ',', '')) CAST_22, try_to_double(replace(replace(AQUISITION_COSTS_TARGET, '$', ''), ',', '')) CAST_23, try_to_double(replace(replace(BOOST_COST_TARGET, '$', ''), ',', '')) CAST_24, CAST_22 CAST_25, BOOST_COST_TARGET BOOST_COST_TARGET_26, try_to_double(replace(MTD_RETENTION, '%', '')) / 100 DIV_27, try_to_double(replace(replace(RETENTION_COSTS_TARGET, '$', ''), ',', '')) CAST_28, try_to_double(replace(replace(CASH_HANDLE_TARGET, '$', ''), ',', '')) CAST_29, try_to_double(ACTIVES_TARGET) CAST_30, try_to_double(FTUS_TARGET) CAST_31, try_to_double(MTD_ACTIVES_TARGET) CAST_32, try_to_double(NEW_UNIQUE_ACTIVES_TARGET) CAST_33, CAST_17 CAST_34 from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_TARGETS) Q1 limit 10001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-Sample-34rdU89t8adkDkUiTTTdmE?:displayNodeId=zYeO5J89lq","kind":"adhoc","request-id":"g019d742808277dc6892721ca5537e0b2","user-id":"RJPpDi9ofjj2luRLdu0geI6rWoD5l","email":"Brett.Pendleton@betfanatics.com"}
