-- Query ID: 01c399fb-0212-6dbe-24dd-070319332d93
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XL_WH
-- Executed: 2026-04-09T21:15:27.121000+00:00
-- Elapsed: 1701ms
-- Environment: FBG

WITH
TREATMENT_ASSIGNMENTS AS (
    SELECT ACCO_ID, TESTID, TESTGROUPID
    FROM FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.v_mv_test_group_accounts
    WHERE TESTID IN (151, 152)
),

PRICING_ASSIGNMENTS AS (
    SELECT
        ACCO_ID,
        TESTGROUPID AS PRICING_TESTGROUPID,
        CASE
            WHEN TESTGROUPID = 0 THEN  1
            WHEN TESTGROUPID = 2 THEN  3
            WHEN TESTGROUPID = 3 THEN  4
            WHEN TESTGROUPID = 4 THEN  5
            WHEN TESTGROUPID = 1 THEN -1
            ELSE NULL
        END AS PRICING_TREATMENT_STATUS,
        CASE
            WHEN TESTGROUPID = 0 THEN 'HIGH'
            WHEN TESTGROUPID = 1 THEN 'CONTROL'
            WHEN TESTGROUPID = 2 THEN 'LOW_AGGRESSIVE'
            WHEN TESTGROUPID = 3 THEN 'LOW_FLAT_25_UP'
            WHEN TESTGROUPID = 4 THEN 'LOW_FLAT_13_UP'
            ELSE NULL
        END AS PRICING_TREATMENT_LABEL
    FROM TREATMENT_ASSIGNMENTS
    WHERE TESTID = 151
)
select * from pricing_assignments where acco_id IN (4121787, 5244590, 4290206, 4039617, 4137549);
