-- Query ID: 01c39a46-0212-6dbe-24dd-070319447563
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:30:21.697000+00:00
-- Elapsed: 244ms
-- Environment: FBG

WITH __casino_daily_settled_agg AS (
  SELECT
    acco_id,
    settled_date_alk,
    cash_bet_stake,
    ggr,
    is_test_account,
    ngr,
    total_bet_count,
    total_payout,
    total_stake
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_DAILY_SETTLED_AGG
)
/* Daily trend last 30 days */
SELECT
  cd.settled_date_alk AS play_date,
  SUM(cd.total_stake) AS total_handle,
  SUM(cd.cash_bet_stake) AS cash_handle,
  SUM(cd.ggr) AS ggr,
  SUM(cd.ngr) AS ngr,
  SUM(cd.total_bet_count) AS total_bets,
  SUM(cd.total_payout) AS total_payout
FROM __casino_daily_settled_agg AS cd
WHERE
  cd.acco_id = '2144018'
  AND cd.is_test_account = '0'
  AND cd.settled_date_alk >= DATEADD(DAY, -30, CURRENT_DATE)
GROUP BY
  cd.settled_date_alk
ORDER BY
  cd.settled_date_alk DESC NULLS LAST /* Generated by Cortex */;
