-- Query ID: 01c399cc-0212-6b00-24dd-0703192920c7
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:28:56.649000+00:00
-- Elapsed: 358ms
-- Environment: FBG

select FTUS_21 "TopK Value", COUNT_203 "TopK Count", ISNULL_208 "TopK Null Sort" from (select *, FTUS_21 is null ISNULL_208 from (select Q2.FTUS FTUS_21, count(1) COUNT_203 from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_FORECAST full join (select OSB_SEGMENT, FTUS, BUS_DATE::timestamp_ltz CAST_48 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_DAILY_DS) Q2 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q2.CAST_48 and NEW_SEGMENTS_DAILY_FORECAST.USER_SEGMENT = Q2.OSB_SEGMENT left join FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_TARGETS Q4 on NEW_SEGMENTS_DAILY_FORECAST."DATE" = Q4.DATE_TARGET left join (select BUS_DATE_FC::timestamp_ltz CAST_100 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_FAIRNESS_DS) Q6 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q6.CAST_100 left join (select BUS_DATE::timestamp_ltz CAST_140 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_MTD_PL_DS) Q8 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q8.CAST_140 left join (select NEW_SEGMENTS_REVENUE_FLOW_THROUGH."DATE" from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_REVENUE_FLOW_THROUGH left join (select EHOLD_BUCKET, BUS_DATE::timestamp_ltz CAST_182 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_REVENUE_FLOW_DS) Q11 on try_to_timestamp_ltz(NEW_SEGMENTS_REVENUE_FLOW_THROUGH."DATE") = Q11.CAST_182 and NEW_SEGMENTS_REVENUE_FLOW_THROUGH.HOLD_BUCKET = Q11.EHOLD_BUCKET) Q10 on NEW_SEGMENTS_DAILY_FORECAST."DATE" = Q10."DATE" group by Q2.FTUS) Q1) Q14 order by ISNULL_208 desc, COUNT_203 desc, FTUS_21 asc limit 1001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-1-34rdU89t8adkDkUiTTTdmE","kind":"adhoc","request-id":"g019d73eefe9f7e278e3be660a794a1f3","user-id":"L3vHZYjsyKujxXKFJJVEoOSTC4m5s","email":"sai.manish@squadrondata.com"}
