-- Query ID: 01c39a42-0212-67a8-24dd-07031943a973
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_L_WH
-- Executed: 2026-04-09T22:26:35.750000+00:00
-- Elapsed: 9007ms
-- Environment: FBG

SELECT
    * EXCLUDE (FBG_UAT, FBG_UAT_LAST_UPDATE, BET365, BET365_LAST_UPDATE, BETFAIR, BETFAIR_LAST_UPDATE, BETMGM, BETMGM_LAST_UPDATE, BETONLINE, BETONLINE_LAST_UPDATE, BETRIVERS, BETRIVERS_LAST_UPDATE, BOVADA, BOVADA_LAST_UPDATE, CAESARS, CAESARS_LAST_UPDATE, FANDUEL, FANDUEL_LAST_UPDATE, ESPN, ESPN_LAST_UPDATE, IBCBET, IBCBET_LAST_UPDATE, MARATHON, MARATHON_LAST_UPDATE, PINNACLE, PINNACLE_LAST_UPDATE, WILLHILL, WILLHILL_LAST_UPDATE, period_number, raw_created_timestamp, event_sport),
    DATEDIFF('second', FBG_LAST_UPDATE, PUSH_TIMESTAMP) AS FBG_LATENCY,
    DATEDIFF('second', DRAFTKINGS_LAST_UPDATE, PUSH_TIMESTAMP) AS DRAFTKINGS_LATENCY
FROM FBG_UNITY_CATALOG.QUANTS.price_alignment_history
WHERE
    market_type ILIKE '%Player%'
    and event_sport = 'BASKETBALL'
    AND is_inplay = TRUE
    and draftkings <> 0
    and FBG <> 0
    and abs(fbg-draftkings) > 2
    AND DATEDIFF('second', DRAFTKINGS_LAST_UPDATE, PUSH_TIMESTAMP) <= DATEDIFF('second', FBG_LAST_UPDATE, PUSH_TIMESTAMP)
LIMIT 100000;
