-- Query ID: 01c399e6-0212-6dbe-24dd-0703192e29a7
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T20:54:20.073000+00:00
-- Elapsed: 4277ms
-- Environment: FBG

SELECT
  -- A.NAME,
  -- A.EMAIL,
  B.ACCO_ID, -- Current account color
  VB.HIGH_LEVEL_SEGMENT, -- Added column
  B.ACCOUNT_REF,
  A.PRE_MATCH_STAKE_COEF AS ACCOUNT_SF,
  A.COLOUR_CAT AS ACCOUNT_COLOUR,
  J.JURISDICTION_NAME,
  B.CHANNEL,
  B.ID,
  B.BETSLIP_ID,
  B.PUNTER_COLOUR AS BET_COLOR, -- Color of account at time of bet
  BP.STAKE_COEF AS BET_SF,
  B.FREE_BET,
  B.STATUS,
  B.PCT_MAX_STAKE_USED,
  B.BET_TYPE,
  BP.BET_TYPE_ID,
  B.BUILD_A_BET,
  -- B.BET_RISK_GROUP,
  B.NUM_LINES,
  B.REJECTION_DETAILS,
  CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME) AS PLACED_TIME,
  ROUND(DATEDIFF(MINUTE, CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME), CONVERT_TIMEZONE('UTC', 'America/New_York', BP.EVENT_TIME)) / 60.0, 2) AS TIME_UNTIL_HOURS,
  CONCAT(
            EXTRACT(MONTH FROM CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME)) || '/',
            EXTRACT(DAY FROM CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME)) || '/',
            EXTRACT(YEAR FROM CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME))
        ) AS PLACED_DATE,
  TO_CHAR(CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME), 'HH12:MI AM') AS PLACED_TOD, -- Formatted time like "7:37 PM"
  BP.PRICE,
  B.TOTAL_PRICE,
  B.TOTAL_STAKE AS STAKE,
  B.PAYOUT,
  B.TOTAL_STAKE - B.PAYOUT AS GGR,
  -- CBP.DEMARGINATED_SELECTION_CLOSING_DECIMAL,
  -- CBP.CLV, -- Added CLV column
  ROUND(B.TOTAL_STAKE * B.TOTAL_PRICE, 2) AS TO_WIN,
  BP.SPORT,
  BP.COMP,
  BP.EVENT,
  BP.CMPP_ID,
  BP.COMP_ID,
  BP.SELECTION,
  BP.INSTRUMENT_ID,
  BP.MARKET,
  BP.MARKET_ID,
  BP.MRKT_TYPE,
  BP.NODE_ID,
  BP.RESULT_TYPE,
  BP.LIVE_BET,
  B.CASHOUT_STATUS,
  B.CASHOUT_AMT,
  CONVERT_TIMEZONE('UTC', 'America/New_York', BP.EVENT_TIME) AS EVENT_TIME,
  CONVERT_TIMEZONE('UTC', 'America/New_York', B.SETTLEMENT_TIME) AS SETTLEMENT_TIME,
  BP.PROB,
  1/NULLIF(BP.PROB, 0) AS DEC_TRUE,
  (DEC_TRUE - BP.PRICE)/DEC_TRUE AS TRUE_EXPECTED,
  EM.EXPECTED_HOLD_PCT,
  EM.TOTAL_EXPECTED_HOLD_PCT,
FROM
  FBG_SOURCE.OSB_SOURCE.ACCOUNTS A
INNER JOIN FBG_SOURCE.OSB_SOURCE.BETS B ON A.ID = B.ACCO_ID
INNER JOIN FBG_SOURCE.OSB_SOURCE.BET_PARTS BP ON B.ID = BP.BET_ID
LEFT JOIN FBG_ANALYTICS.TRADING.FCT_EXPECTED_MARGIN EM ON B.ID = EM.ID
LEFT JOIN FBG_SOURCE.OSB_SOURCE.JURISDICTIONS J ON B.JURISDICTIONS_ID = J.ID
LEFT JOIN FBG_ANALYTICS.TRADING.fct_value_bands VB ON A.ID = VB.ACCO_ID -- Added join
WHERE
--B.STATUS <> 'REJECTED'
--AND B.CHANNEL ='RETAIL'
--A.TEST = 0
--AND INSTRUMENT_ID = 507183671
--B.STATUS <> 'REJECTED'
--AND VB.HIGH_LEVEL_SEGMENT = 'Negative'
--AND B.TOTAL_PRICE >=1.7
-- AND B.ACCO_ID = 2087428
-- AND B.ACCO_ID = 2053634
-- AND B.ACCOUNT_REF = 'acostello-cic'
-- AND B.ACCO_ID IN ()
-- AND B.STATUS <> 'REJECTED'
 --AND B.ID = 25279123000019952
-- AND B.REJECTION_DETAILS = 'STAKE_LIMIT'
--AND BP.STAKE_COEF < 1
--AND A.PRE_MATCH_STAKE_COEF = .50
--AND B.PUNTER_COLOUR = 'ORANGE'
-- AND B.FREE_BET = 0
--AND B.PCT_MAX_STAKE_USED >= 50
-- (BP.EVENT LIKE '%Depaul%' OR BP.EVENT LIKE '%Robert Morris%')
--AND BP.EVENT LIKE '%New York Rangers vs. Columbus Blue Jackets%'
--AND BP.EVENT LIKE '%Kansas%'
--AND BP.MARKET LIKE '%Handicap%'
--AND MRKT_TYPE = 'AMERICAN_FOOTBALL:FTOT:B:OU'
--AND BP.SELECTION LIKE '%Celtics%'
-- AND (BP.SELECTION = 'Charlie Morton 3+' OR BP.MARKET = 'Charlie Morton - Strikeouts')
--AND BP.COMP = 'NHL'
--AND BP.COMP IN ('WNBA')
-- AND BP.COMP NOT LIKE '%NBA%' AND BP.COMP NOT LIKE '%WNBA%' AND BP.COMP NOT LIKE '%March Madness%' AND BP.COMP NOT LIKE '%NCAA%'
--AND BP.SPORT = 'TENNIS'
--AND BP.COMP NOT LIKE '%NBA%'
-- AND BP.COMP NOT LIKE '%NCAA%'
--AND BP.COMP_ID =
--AND BP.NODE_ID = 4039069
 BP.NODE_ID IN (4209816)
--AND BP.LIVE_BET = 0
--AND B.BET_TYPE = 'SINGLE'
-- AND B.BUILD_A_BET = TRUE
--AND B.NUM_LINES = 2
--AND B.PAYOUT > 0
--AND TIME_UNTIL_HOURS < 0
--AND BP.MARKET_ID = 518541406
-- AND EXTRACT(MONTH FROM CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME)) = 3 -- Format for Month
-- AND CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME)::DATE >= CURRENT_DATE - INTERVAL '1 year'
AND CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME)::DATE >= '2025-08-08'
--AND CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME)::DATE IN ('2024-02-23', '2024-02-24')
AND TO_CHAR(CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME), 'HH24:MI') BETWEEN '00:00' AND '24:00'
--AND BP.MARKET LIKE '%Corum%'
--AND BP.MRKT_TYPE = 'BASEBALL:FT:WALKOFF'
--AND CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME)::DATE >= '2025-01-09'
--AND CONVERT_TIMEZONE('UTC', 'America/New_York', B.PLACED_TIME)::DATE <= '2025-02-10'
-- AND BP.MRKT_TYPE NOT LIKE 'DARTS%'
--AND BP.EVENT NOT LIKE '%Futures%'
-- AND CONVERT_TIMEZONE('UTC', 'America/New_York', B.SETTLEMENT_TIME)::DATE <= '2024-05-31'
-- AND CONVERT_TIMEZONE('UTC', 'America/New_York', B.SETTLEMENT_TIME)::DATE >= '2024-03-01'
-- AND BP.PROB IS NOT NULL
--AND PLACED_TIME
--AND PAYOUT = 1546.13
--AND BET_ID = 24121079000120208
--AND TOTAL_PRICE = 39.37
--AND B.CASHOUT_STATUS is null
--AND J.JURISDICTION_NAME like 'CONNECTICUT'
--AND PCT_MAX_STAKE_USED >= 90
--AND B.TOTAL_STAKE >= 200
--AND B.CASHOUT_STATUS <> 'COMPLETED'
--AND BP.RESULT_TYPE = 'ACCEPTED'
--AND TIME_UNTIL_HOURS <0
--AND REJECTION_DETAILS = 'STAKE_LIMIT'
ORDER BY placed_time desc;
