-- Query ID: 01c39a41-0212-6cb9-24dd-070319435b63
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:25:32.099000+00:00
-- Elapsed: 563ms
-- Environment: FBG

WITH __casino_daily_settled_agg AS (
  SELECT
    acco_id,
    game_id,
    settled_date_alk,
    cash_bet_count,
    cash_bet_stake,
    casino_credit_bet_count,
    casino_credit_bet_stake,
    expected_ggr,
    expected_ngr,
    freespin_bet_count,
    freespin_bet_stake,
    ggr,
    is_test_account,
    ngr,
    total_bet_count,
    total_payout,
    total_stake,
    total_void
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_DAILY_SETTLED_AGG
), last_30 AS (
  SELECT
    SUM(cd.total_stake) AS handle_30d,
    SUM(cd.cash_bet_stake) AS cash_handle_30d,
    SUM(cd.freespin_bet_stake) AS freespin_handle_30d,
    SUM(cd.casino_credit_bet_stake) AS credit_handle_30d,
    SUM(cd.total_payout) AS total_payout_30d,
    SUM(cd.ggr) AS ggr_30d,
    SUM(cd.ngr) AS ngr_30d,
    SUM(cd.expected_ggr) AS expected_ggr_30d,
    SUM(cd.expected_ngr) AS expected_ngr_30d,
    SUM(cd.total_bet_count) AS total_bets_30d,
    SUM(cd.cash_bet_count) AS cash_bets_30d,
    SUM(cd.freespin_bet_count) AS freespin_bets_30d,
    SUM(cd.casino_credit_bet_count) AS credit_bets_30d,
    COUNT(DISTINCT cd.settled_date_alk) AS active_days_30d,
    COUNT(DISTINCT cd.game_id) AS unique_games_30d,
    SUM(cd.total_void) AS total_void_30d
  FROM __casino_daily_settled_agg AS cd
  WHERE
    cd.acco_id = '2144018'
    AND cd.settled_date_alk >= DATEADD(DAY, -30, CURRENT_DATE)
    AND cd.is_test_account = '0'
), last_7 AS (
  SELECT
    SUM(cd.total_stake) AS handle_7d,
    SUM(cd.cash_bet_stake) AS cash_handle_7d,
    SUM(cd.freespin_bet_stake) AS freespin_handle_7d,
    SUM(cd.casino_credit_bet_stake) AS credit_handle_7d,
    SUM(cd.total_payout) AS total_payout_7d,
    SUM(cd.ggr) AS ggr_7d,
    SUM(cd.ngr) AS ngr_7d,
    SUM(cd.expected_ggr) AS expected_ggr_7d,
    SUM(cd.expected_ngr) AS expected_ngr_7d,
    SUM(cd.total_bet_count) AS total_bets_7d,
    SUM(cd.cash_bet_count) AS cash_bets_7d,
    SUM(cd.freespin_bet_count) AS freespin_bets_7d,
    SUM(cd.casino_credit_bet_count) AS credit_bets_7d,
    COUNT(DISTINCT cd.settled_date_alk) AS active_days_7d,
    COUNT(DISTINCT cd.game_id) AS unique_games_7d,
    SUM(cd.total_void) AS total_void_7d
  FROM __casino_daily_settled_agg AS cd
  WHERE
    cd.acco_id = '2144018'
    AND cd.settled_date_alk >= DATEADD(DAY, -7, CURRENT_DATE)
    AND cd.is_test_account = '0'
)
SELECT
  *
FROM last_30
CROSS JOIN last_7 /* Generated by Cortex */;
