-- Query ID: 01c39a45-0212-6dbe-24dd-07031944718b
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_L_WH
-- Executed: 2026-04-09T22:29:34.376000+00:00
-- Elapsed: 2146ms
-- Environment: FBG

SELECT
    * EXCLUDE (FBG_UAT, FBG_UAT_LAST_UPDATE, BET365, BET365_LAST_UPDATE, BETFAIR, BETFAIR_LAST_UPDATE, BETMGM, BETMGM_LAST_UPDATE, BETONLINE, BETONLINE_LAST_UPDATE, BETRIVERS, BETRIVERS_LAST_UPDATE, BOVADA, BOVADA_LAST_UPDATE, CAESARS, CAESARS_LAST_UPDATE, FANDUEL, FANDUEL_LAST_UPDATE, DRAFTKINGS, DRAFTKINGS_LAST_UPDATE, ESPN, ESPN_LAST_UPDATE, IBCBET, IBCBET_LAST_UPDATE, MARATHON, MARATHON_LAST_UPDATE, WILLHILL, WILLHILL_LAST_UPDATE, period_number, raw_created_timestamp, event_sport),
    DATEDIFF('second', FBG_LAST_UPDATE, PUSH_TIMESTAMP) AS FBG_LATENCY,
    DATEDIFF('second', PINNACLE_LAST_UPDATE, PUSH_TIMESTAMP) AS PINNACLE_LATENCY
FROM FBG_UNITY_CATALOG.QUANTS.price_alignment_history
WHERE
    --market_type ILIKE '%Player%'
    event_sport = 'BASKETBALL'
    AND is_inplay = TRUE
    and pinnacle <> 0
    and FBG <> 0
    and abs(fbg-pinnacle) > 5
    AND DATEDIFF('second', PINNACLE_LAST_UPDATE, PUSH_TIMESTAMP) <= DATEDIFF('second', FBG_LAST_UPDATE, PUSH_TIMESTAMP)
LIMIT 1000;
