-- Query ID: 01c39a1d-0212-6cb9-24dd-0703193b6b63
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_M_WH
-- Executed: 2026-04-09T21:49:32.537000+00:00
-- Elapsed: 20674ms
-- Environment: FBG

WITH your_list AS (                                                                                                                                                                                                                                
      SELECT lower(email) AS email, first_name, last_name
      FROM (VALUES                                                                                                                                                                                                                                   
          ('5thborosports718@gmail.com','christopher','ostrow'),                                                                                                                                                                                     
          ('g.athana@yahoo.com','george','athanasopoulos'),
          ('antnixon212@gmail.com','anthony','nixon'),                                                                                                                                                                                               
          ('fgp121474@gmail.com','francis','price'),                                                                                                                                                                                                 
          ('mohayes28@aol.com','maurice','hayes'),                                                                                                                                                                                                   
          ('suvsitzky@yahoo.com','shabsai','uvsitzky'),                                                                                                                                                                                              
          ('jlorissaint@gmail.com','james','lorissaint'),                                                                                                                                                                                            
          ('bimdagrk@aol.com','dimitrios','efthimiou'),
          ('moneyr129@gmail.com','rigoberto','ramos'),                                                                                                                                                                                               
          ('ephambleton@gmail.com','eric','hambleton'),                                                                                                                                                                                              
          ('jayski726@aol.com','julio','perez'),                                                                                                                                                                                                     
          ('santino71205@aol.com','santino','desideri'),                                                                                                                                                                                             
          ('bcurtis96@optonline.net','brandon','curtis'),                                                                                                                                                                                            
          ('nick.imburgia@yahoo.com','nicholas','imburgia'),
          ('raycarotenuto@gmail.com','raymond','carotenuto'),                                                                                                                                                                                        
          ('irothblut@nhcfqhc.com','ira','rothblut'),
          ('stephen.simonis@gmail.com','stephen','simonis'),                                                                                                                                                                                         
          ('mersimbogdanovic@gmail.com','mersim','bogdanovic'),
          ('michaelpalcorn@gmail.com','michael','alcorn'),                                                                                                                                                                                           
          ('vcfarina@gmail.com','vincenzo','farina'),
          ('dabraid@gmail.com','david','braid'),                                                                                                                                                                                                     
          ('mrbrown366@hotmail.com','matt','brown'),                                                                                                                                                                                                 
          ('pyl102@gmail.com','paul','lee'),
          ('terrynyc33@gmail.com','onur','balaban'),                                                                                                                                                                                                 
          ('fanamanuel@hotmail.com','manuel','fana'),                                                                                                                                                                                                
          ('mersimbogdani24@aol.com','mersim','bogdanovic'),
          ('pjgotham@gmail.com','paul','norman'),                                                                                                                                                                                                    
          ('scumaci.jarred@gmail.com','jarred','scumaci'),
          ('cassefamily5@yahoo.com','christian','casse'),                                                                                                                                                                                            
          ('williamjh9090@gmail.com','william','hauser'),
          ('masongrey10@icloud.com','greyson','cruz'),                                                                                                                                                                                               
          ('jgreenberg230@gmail.com','jason','greenberg'),
          ('jay89aca@gmail.com','justin','leakey'),                                                                                                                                                                                                  
          ('serrao41@yahoo.com','antonio','serrao'),
          ('kylebalakitsis2@yahoo.com','kyle','balakitsis'),                                                                                                                                                                                         
          ('adam.goldbg@gmail.com','adam','goldberg'),
          ('pmahoney04@aol.com','peter','mahoney'),                                                                                                                                                                                                  
          ('stephan.lacombe@gmail.com','stephan','lacombe'),                                                                                                                                                                                         
          ('hargrovejay@yahoo.com','jaime','hargrove'),
          ('killa1216@me.com','michael','beshara'),                                                                                                                                                                                                  
          ('rkay1966@yahoo.com','refik','kukaj'),
          ('buckleybuckley98@yahoo.com','ryan','buckley'),                                                                                                                                                                                           
          ('zhersh2@gmail.com','thomas','hersh'),
          ('christopherduffus@yahoo.com','christopher','duffus'),                                                                                                                                                                                    
          ('honorablepaws@gmail.com','wilson','ortiz'),
          ('edope@aol.com','ivo','mohorovic'),                                                                                                                                                                                                       
          ('my3boysanj@aol.com','pasquale','capasso'),                                                                                                                                                                                               
          ('bobbyleiser@hotmail.com','robert','leiser'),                                                                                                                                                                                             
          ('steelers82@optonline.net','christian','casse'),                                                                                                                                                                                          
          ('calvin9524@gmail.com','calvin','olivero'),                                                                                                                                                                                               
          ('john.cisse32@gmail.com','john','cisse'),
          ('whitediamond252@aol.com','andrew','thomson'),                                                                                                                                                                                            
          ('thomas.kim24@gmail.com','thomas','kim'),
          ('ericbeer@hotmail.com','eric','beer'),                                                                                                                                                                                                    
          ('jeffreylope@gmail.com','jeffrey','lope'),                                                                                                                                                                                                
          ('d.caloianu@yahoo.com','dan','caloianu'),
          ('ezra@daicompany.com','ezra','dweck'),                                                                                                                                                                                                    
          ('blackd1165@yahoo.com','duncan','blackwood'),                                                                                                                                                                                             
          ('jslice31@aol.com','jerel','cokley'),
          ('cnooch62@aol.com','christopher','iannucci'),                                                                                                                                                                                             
          ('smithquinn27@gmail.com','quinn','smith'),                                                                                                                                                                                                
          ('bkmoe2k9@aim.com','mohammed','suleiman'),                                                                                                                                                                                                
          ('bmb9491@yahoo.com','brandon','boyle'),                                                                                                                                                                                                   
          ('baminoff35@gmail.com','benjamin','aminoff'),
          ('yaakov305weiss@gmail.com','yaakov','weiss'),                                                                                                                                                                                             
          ('jacob.kurosaki@gmail.com','jacob','kurosaki'),
          ('dutchmvster@icloud.com','saleem','mohammed'),                                                                                                                                                                                            
          ('mikebot88@gmail.com','michael','botier'),                                                                                                                                                                                                
          ('shawn.duggal@gmail.com','shawn','duggal'),
          ('antgraz8@aol.com','anthony','graziano'),                                                                                                                                                                                                 
          ('ddelia04@aol.com','daniel','delia'),                                                                                                                                                                                                     
          ('csigadel@gmail.com','cory','sigadel'),
          ('mreitanoarg@gmail.com','michael','reitano'),                                                                                                                                                                                             
          ('michaelm1723@gmail.com','michael','marino'),
          ('jblumstein@actualizeconsulting.com','jason','blumstein'),                                                                                                                                                                                
          ('servais527@gmail.com','ivan','servais'),
          ('kyleelmore777@gmail.com','kyle','mccray'),                                                                                                                                                                                               
          ('avirosenburg@gmail.com','avigall','rosenberg'),                                                                                                                                                                                          
          ('jmzelen2@gmail.com','justin','zelen'),                                                                                                                                                                                                   
          ('gmullakandov@gmail.com','gary','mullakandov'),                                                                                                                                                                                           
          ('bczarnik23@gmail.com','bartlomiej','czarnik'),                                                                                                                                                                                           
          ('msuazo22@yahoo.com','marfred','suazo'),
          ('emnem2190@aol.com','michael','mercuri'),                                                                                                                                                                                                 
          ('jason.palmatary@gmail.com','jason','palmatary'),                                                                                                                                                                                         
          ('madler68@gmail.com','matt','adler'),                                                                                                                                                                                                     
          ('jrblumstein@gmail.com','jason','blumstein'),                                                                                                                                                                                             
          ('bkelly6747@yahoo.com','brendan','kelly'),                                                                                                                                                                                                
          ('mmaneri10@gmail.com','michael','maneri'),
          ('chirag@longridgepartners.com','chirag','jethanandani'),                                                                                                                                                                                  
          ('danielmizrahi@me.com','daniel','mizrahi'),                                                                                                                                                                                               
          ('fkukaj1@yahoo.com','fleurat','kuka'),                                                                                                                                                                                                    
          ('jerryortaz@yahoo.com','lior','ortaz'),                                                                                                                                                                                                   
          ('davidhhamerman@yahoo.com','david','hamerman'),
          ('jerry.rosiellojr@gmail.com','jerry','rosiello'),                                                                                                                                                                                         
          ('dennis.dweck1@gmail.com','dennis','dweck'),
          ('mreitanoarg@aol.com','michael','reitano'),                                                                                                                                                                                               
          ('jfried88@gmail.com','joshua','friedman'),                                                                                                                                                                                                
          ('arch2399@gmail.com','aaron','eichorn'),
          ('muvaydov@icloud.com','mark','uvaydov'),                                                                                                                                                                                                  
          ('anthony.reitanojr@gmail.com','anthony','reitano'),
          ('k.basios@icloud.com','konstantine','basios'),                                                                                                                                                                                            
          ('brianmshure@gmail.com','brian','shure'),
          ('brandonkbuchanan@gmail.com','brandon','buchanan'),                                                                                                                                                                                       
          ('michael.mauro.salvatore@gmail.com','michael','salvatore'),
          ('matters248@gmail.com','matthew','holmquist'),                                                                                                                                                                                            
          ('silve005@yahoo.com','seth','silverblatt'),                                                                                                                                                                                               
          ('mytmike11@aol.com','michael','reitan'),
          ('paul.byun@hotmail.com','paul','byun'),                                                                                                                                                                                                   
          ('jastorina31@hotmail.com','joseph','astorina'),
          ('joshuacutchinbk29@gmail.com','joshua','cutchin'),                                                                                                                                                                                        
          ('papags4@aol.com','james','papagni'),
          ('ezrawkassin@gmail.com','ezra','kassin'),                                                                                                                                                                                                 
          ('bcgt178@gmail.com','garrett','thompson'),
          ('vikaaskataria@gmail.com','vikaas','kataria'),                                                                                                                                                                                            
          ('tommaguire845@gmail.com','thomas','maguire'),
          ('haynomarks@gmail.com','maria','eli'),                                                                                                                                                                                                    
          ('boobiealcantara@gmail.com','heriberto','alcantara'),
          ('tommaguire@protonmail.com','thomas','maguire'),                                                                                                                                                                                          
          ('bballane@gmail.com','brandon','ballane'),
          ('phills41@yahoo.com','taakov','saks'),                                                                                                                                                                                                    
          ('tomiazzetta@gmail.com','tom','iazzetta'),
          ('salepro1@optonline.net','salvatore','magaraci'),                                                                                                                                                                                         
          ('jturner2881@gmail.com','james','turner'),
          ('dskurowitz@gmail.com','david','skurowitz'),                                                                                                                                                                                              
          ('james.burkart97@icloud.com','james','burkart'),
          ('bredendo1@gmail.com','brandon','redendo'),                                                                                                                                                                                               
          ('wingwong1102@gmail.com','wing','huang'),
          ('dipietrolaw@yahoo.com','anthony','dipietro'),                                                                                                                                                                                            
          ('jboy106@gmail.com','jonathan','thompson'),                                                                                                                                                                                               
          ('johnpaul.sabia@gmail.com','john','sabia'),
          ('scottc719@gmail.com','scott','cacciatore'),                                                                                                                                                                                              
          ('lsandresrapalo@gmail.com','lester','sandres'),
          ('deah.zindani@gmail.com','deah','zindani'),                                                                                                                                                                                               
          ('jhick722@yahoo.com','john','hickey'),
          ('mfortuna3@me.com','michael','fortuna'),                                                                                                                                                                                                  
          ('timgutman@yahoo.com','timothy','gutman'),
          ('sps712@aol.com','scott','silberman'),                                                                                                                                                                                                    
          ('ortizedwin184@aol.com','edwin','ortiz'),                                                                                                                                                                                                 
          ('jeffrie728@gmail.com','jeff','singer'),
          ('deuceswildixi@gmail.com','chris','wright'),                                                                                                                                                                                              
          ('asahni110@gmail.com','angad','sahni'),
          ('highdemand.b@icloud.com','isiah','rambaran'),                                                                                                                                                                                            
          ('inacorns@yahoo.com','dean','mark'),
          ('lild204@aol.com','dennis','radoncic'),                                                                                                                                                                                                   
          ('bxjeff911@aol.com','jeffrey','carreno'),
          ('kblanco69@aol.com','keith','metz'),                                                                                                                                                                                                      
          ('patrick.t.okeefe@gmail.com','patrick','okeefe'),
          ('victorsalem23@gmail.com','victor','salem'),                                                                                                                                                                                              
          ('aturrigiano@yahoo.com','angelo','turrigiano'),
          ('dlfgns_127@hotmail.com','il','hwang'),                                                                                                                                                                                                   
          ('begrosser@gmail.com','bernard','grosser'),
          ('leorapalo@gmail.com','leonardo','rapalo'),                                                                                                                                                                                               
          ('matt.davis2117@optonline.net','matthew','davis'),
          ('sukhjindersonu6@gmail.com','sukhjinder','singh'),                                                                                                                                                                                        
          ('mas@katalystsecurities.com','michael','silverman'),
          ('a.kacic11@gmail.com','admir','kacic'),                                                                                                                                                                                                   
          ('fd.persona@gmail.com','franco','demartino'),
          ('dhan0517@gmail.com','david','han'),                                                                                                                                                                                                      
          ('dareheis85@gmail.com','daryush','omar'),
          ('nellynash@aol.com','nelly','messiha'),                                                                                                                                                                                                   
          ('sethfried1@aol.com','seth','fried'),                                                                                                                                                                                                     
          ('mcginleyp2@gmail.com','patrick','mcginley'),                                                                                                                                                                                             
          ('dannyetkin@yahoo.com','daniel','etkin'),                                                                                                                                                                                                 
          ('nmd1975@gmail.com','nick','difranza'),                                                                                                                                                                                                   
          ('kjfinn95@gmail.com','kyle','finn'),
          ('oraoudy@gmail.com','omar','raoudy'),                                                                                                                                                                                                     
          ('ptskee@yahoo.com','eric','swirsky'),
          ('amazingcreditrepairs@gmail.com','andre','johnson'),                                                                                                                                                                                      
          ('eldin.radoncic@me.com','eldin','radoncic'),                                                                                                                                                                                              
          ('joeduke777@aol.com','joseph','deluca'),                                                                                                                                                                                                  
          ('tuna62475@gmail.com','michael','fortuna'),                                                                                                                                                                                               
          ('bigwess30@hotmail.com','wesley','saint-vil'),
          ('mizpmr@aim.com','michael','mizhiritsky'),                                                                                                                                                                                                
          ('msprotege08@yahoo.com','morris','steinberg'),                                                                                                                                                                                            
          ('salepro11@gmail.com','a kirsten','gallardo'),                                                                                                                                                                                            
          ('carl.tirella@gmail.com','carl','tirella'),                                                                                                                                                                                               
          ('mjnilo7@gmail.com','matthew','nilo'),
          ('mi6823.mj@gmail.com','michelle','jack'),                                                                                                                                                                                                 
          ('dannyetkin@totalreloservices.com','daniel','etkin'),
          ('csafaya@gmail.com','christopher','safaya'),                                                                                                                                                                                              
          ('david.gallin@gmail.com','david','gallin'),
          ('ndifranza@gmail.com','nick','difranza'),                                                                                                                                                                                                 
          ('to81mvp@aol.com','bernard','grosser'),                                                                                                                                                                                                   
          ('jesses3939@gmail.com','jesse','sahagun'),
          ('isaacsrouko@gmail.com','isaac','srouko'),                                                                                                                                                                                                
          ('rhorvath624@yahoo.com','richard','horvath'),
          ('mindovermatter1214@gmail.com','paul','sessa'),                                                                                                                                                                                           
          ('harrisonleipold92@gmail.com','harrison','leipold'),                                                                                                                                                                                      
          ('kiaxx0112@yahoo.com','krystal','almanzar'),                                                                                                                                                                                              
          ('ptyank@aol.com','paul','tarantino'),                                                                                                                                                                                                     
          ('naquonh30@gmail.com','naquon','simmons'),                                                                                                                                                                                                
          ('tlawal@g.emporia.edu','tola','lawal'),                                                                                                                                                                                                   
          ('spertaw@gmail.com','samir','pertaw'),                                                                                                                                                                                                    
          ('dereckhardy@icloud.com','dereck','hardy jr'),
          ('shianmiller04@gmail.com','shian','miller'),                                                                                                                                                                                              
          ('billyz0917@yahoo.com','william','zambri'),
          ('ross.louis88@gmail.com','ross','atkin'),                                                                                                                                                                                                 
          ('xavier033007@yahoo.com','sergio','gonzalez'),
          ('pizzapete207@yahoo.com','peter','kazanas'),                                                                                                                                                                                              
          ('mmikemartucci@aol.com','mike','martucci'),
          ('dina.depirro@gmail.com','dina','depirro'),                                                                                                                                                                                               
          ('sangour1612@yahoo.com','ghassen','medallel'),
          ('bigt.lovesourd@yahoo.com','thomas','farrell'),                                                                                                                                                                                           
          ('kandov92@gmail.com','dani','kandov'),
          ('joe_1222@live.com','joechris','gomez'),                                                                                                                                                                                                  
          ('mmeirowitz1@gmail.com','michael','meirowitz'),                                                                                                                                                                                           
          ('bavila91@yahoo.com','brayan','avila'),                                                                                                                                                                                                   
          ('fgrese@yahoo.com','frank','grese'),                                                                                                                                                                                                      
          ('jerry.vitelli@aol.com','gerald','vitelli'),
          ('castillojulio18@me.com','julio','castillo'),                                                                                                                                                                                             
          ('fanduel11209@gmail.com','roy','berthiaume'),                                                                                                                                                                                             
          ('chaletexecutiveenterprises@gmail.com','daniel','chalet'),
          ('jpeltz514@gmail.com','jesse','peltz'),                                                                                                                                                                                                   
          ('jaredbeldock@yahoo.com','jared','beldock'),
          ('darylwilson22@yahoo.com','sherwin','wilson'),                                                                                                                                                                                            
          ('carlosvargas0467@icloud.com','carlos','vargas'),
          ('danywu1088@gmail.com','dany','wu'),                                                                                                                                                                                                      
          ('alvarezpfa@yahoo.com','patrick','alvarez'),
          ('brett.gallaway@gmail.com','brett','gallaway'),                                                                                                                                                                                           
          ('jmactionnn@gmail.com','john','mclaughlin'),
          ('miketaylor716@gmail.com','michael','taylor'),                                                                                                                                                                                            
          ('nicddun@aol.com','daniel','dunleavy'),
          ('neilrutty@hotmail.com','neil','rutty'),                                                                                                                                                                                                  
          ('joedobbie@yahoo.com','joseph','canterino'),
          ('rafaielbernardo@gmail.com','rafaiel','bernardo'),                                                                                                                                                                                        
          ('threedogsfootball@yahoo.com','steven','berman'),                                                                                                                                                                                         
          ('dquezada1991@yahoo.com','darwin','quezada'),
          ('zefhajdari1@gmail.com','zef','hajdari'),                                                                                                                                                                                                 
          ('a.bujaj2@aol.com','antonim','bujaj'),                                                                                                                                                                                                    
          ('justin.cebel@uconn.edu','justin','cebel'),                                                                                                                                                                                               
          ('seadradoncic85@gmail.com','sead','radoncic'),                                                                                                                                                                                            
          ('pstripleatransport@gmail.com','paul','shamah'),
          ('gatorfreak90@yahoo.com','michael','wang'),                                                                                                                                                                                               
          ('cjfgrese@yahoo.com','frank','grese'),
          ('aorive07@gmail.com','adrian','orive'),                                                                                                                                                                                                   
          ('jmdwek@aol.com','jacob','dwek'),                                                                                                                                                                                                         
          ('tlaw231@yahoo.com','trevor','lawrence'),
          ('17468148@qq.com','mingda','chen'),                                                                                                                                                                                                       
          ('cyoneny@hotmail.com','cihan','yilmaz'),
          ('barrettfrankel@gmail.com','barrett','frankel'),                                                                                                                                                                                          
          ('kfelizcuello@gmail.com','kelvin','feliz-cuello'),                                                                                                                                                                                        
          ('nikosfinishing@gmail.com','nikolaos','kozanitis'),                                                                                                                                                                                       
          ('metrobrokersnyc@aol.com','steven','berman'),                                                                                                                                                                                             
          ('james.curcio@yahoo.com','james','curcio'),                                                                                                                                                                                               
          ('h.perezz2019@gmail.com','henry','perez'),                                                                                                                                                                                                
          ('majorofdos@gmail.com','kwesi','moore'),                                                                                                                                                                                                  
          ('mmiro90@gmail.com','michael','miro'),                                                                                                                                                                                                    
          ('kathy_musso@yahoo.com','kathryn','musso'),
          ('jzaafarani@gmail.com','yosef','zaafarani'),                                                                                                                                                                                              
          ('ernestkalezic@icloud.com','ernest','kalezic'),
          ('tmt129@aol.com','thomas','tramutola'),                                                                                                                                                                                                   
          ('olegyav@gmail.com','oleg','yavorovskiy'),
          ('newytgod@icloud.com','anthony','batista'),                                                                                                                                                                                               
          ('tdecapua@gmail.com','thomas','decapua'),
          ('joeymanz3811@gmail.com','joseph','manzione'),                                                                                                                                                                                            
          ('harryfiggie@gmail.com','harry','figgie'),                                                                                                                                                                                                
          ('bfarnach@allseasonings.com','brendon','farnach'),                                                                                                                                                                                        
          ('weewee1022@yahoo.com','william','vanwie'),                                                                                                                                                                                               
          ('rj_sims1@icloud.com','ragille','sims'),
          ('mikeosbornewins@gmail.com','michael','osborne'),                                                                                                                                                                                         
          ('kb151@pm.me','kevin','barry'),
          ('dkangadis@gmail.com','dionisis','kangadis'),                                                                                                                                                                                             
          ('jamesmurraybc@yahoo.com','james','murray'),
          ('si47@aol.com','steven','indich'),                                                                                                                                                                                                        
          ('emre@ozandac.com','emin','ozandac'),
          ('itsallgreek2m@aol.com','john','drakopoulos'),                                                                                                                                                                                            
          ('glennpepper@icloud.com','glenn','pepper'),                                                                                                                                                                                               
          ('alan.pinto@gmail.com','alan','pinto'),                                                                                                                                                                                                   
          ('bconlan3@gmail.com','brian','conlan'),                                                                                                                                                                                                   
          ('jordanteagency@yahoo.com','jordan','haimowitz'),                                                                                                                                                                                         
          ('sangyounbak@gmail.com','sangyoun','bak'),                                                                                                                                                                                                
          ('pjgrealy@gmail.com','philip','grealy'),
          ('uesmanhattan@hotmail.com','hareram','sadhwani'),                                                                                                                                                                                         
          ('craigyankees@netscape.net','craig','appelbaum'),                                                                                                                                                                                         
          ('robert.fumerton@skadden.com','robert','fumerton'),                                                                                                                                                                                       
          ('ryan.malpiedi@gmail.com','ryan','malpiedi'),                                                                                                                                                                                             
          ('kingcard1004@yahoo.com','brandon','kim'),                                                                                                                                                                                                
          ('jordan.liebowitz82@gmail.com','jordan','liebowitz'),
          ('brian.kotch@jbsystemsconsulting.com','brian','kotch'),                                                                                                                                                                                   
          ('c.boyadjian@me.com','yervand','boyadjian'),                                                                                                                                                                                              
          ('doanyc1@hotmail.com','alexander','oliner'),                                                                                                                                                                                              
          ('jordanbhaimowitz@gmail.com','jordan','haimowitz'),                                                                                                                                                                                       
          ('bakshter@gmail.com','sangmin','bak'),                                                                                                                                                                                                    
          ('jonrwessels@hotmail.com','jon','wessels'),                                                                                                                                                                                               
          ('sangbak95@gmail.com','sangmin','bak'),                                                                                                                                                                                                   
          ('razor926123@gmail.com','raymond','torritelli'),                                                                                                                                                                                          
          ('kingcard129@yahoo.com','brandon','kim'),                                                                                                                                                                                                 
          ('danny.kanamori@gmail.com','daniel','kanamori'),                                                                                                                                                                                          
          ('bmart71823@yahoo.com','brian','martinez'),                                                                                                                                                                                               
          ('aaron.reback@gmail.com','aaron','reback'),                                                                                                                                                                                               
          ('stylishgangsta16@aol.com','jasmin','lalicic'),
          ('cobrien43@gmail.com','chris','obrien'),                                                                                                                                                                                                  
          ('yomodele8@gmail.com','tyrone','serrano'),
          ('griggio21@gmail.com','eugene','riggio'),                                                                                                                                                                                                 
          ('john@daxxcapital.com','surjit','walia'),                                                                                                                                                                                                 
          ('ilyayev.michael@gmail.com','mikhail','ilyayev'),                                                                                                                                                                                         
          ('pwfootball4life@hotmail.com','khaled','amin'),                                                                                                                                                                                           
          ('moosusa@yahoo.com','ronald','roth'),                                                                                                                                                                                                     
          ('petestanko@ymail.com','peter','stanko'),                                                                                                                                                                                                 
          ('ryancost36@gmail.com','joshua','pizarro'),                                                                                                                                                                                               
          ('nycparks10@yahoo.com','victor','schettino'),                                                                                                                                                                                             
          ('peter.crill@yahoo.com','peter','crill'),                                                                                                                                                                                                 
          ('m.sepe@roadtex.com','michael','sepe'),                                                                                                                                                                                                   
          ('adam.akel@gmail.com','adam','akel'),                                                                                                                                                                                                     
          ('funtikac@yahoo.com','igor','alterman'),                                                                                                                                                                                                  
          ('daniel.a.feinstein@gmail.com','daniel','feinstein'),                                                                                                                                                                                     
          ('fenchcorp@aol.com','john','buttaro'),                                                                                                                                                                                                    
          ('tylercusano@outlook.com','tyler','cusano'),                                                                                                                                                                                              
          ('nick.doscher@yahoo.com','nicholas','doscher'),                                                                                                                                                                                           
          ('john.montoro6@gmail.com','john','montoro'),                                                                                                                                                                                              
          ('davidkrueger33@gmail.com','david','krueger'),                                                                                                                                                                                            
          ('mote72238@mypacks.net','patrick','perry'),                                                                                                                                                                                               
          ('charlesberger1@yahoo.com','charles','berger'),                                                                                                                                                                                           
          ('fenchmgt@gmail.com','john','buttaro'),                                                                                                                                                                                                   
          ('rodineliyahu@yahoo.com','elie','rodin'),                                                                                                                                                                                                 
          ('kgrishaj11@gmail.com','kristian','grishaj'),                                                                                                                                                                                             
          ('whitestonebay1@gmail.com','elisha','blain'),                                                                                                                                                                                             
          ('abalolahamed@gmail.com','hamed','abalola'),                                                                                                                                                                                              
          ('joman099222@gmail.com','jojo','john'),                                                                                                                                                                                                   
          ('msergio013@gmail.com','michael','sergio'),                                                                                                                                                                                               
          ('lilninno@yahoo.com','michal','picozzi'),                                                                                                                                                                                                 
          ('michael@firstclassleasingny.com','michael','golomb'),                                                                                                                                                                                    
          ('artygj84@gmail.com','arton','ahmetaj'),                                                                                                                                                                                                  
          ('rich.williams922@gmail.com','richard','williams'),                                                                                                                                                                                       
          ('denmrkulic@gmail.com','denis','mrkulic'),                                                                                                                                                                                                
          ('ryanbhat@gmail.com','ryan','bhat'),                                                                                                                                                                                                      
          ('princeray061090@gmail.com','jahair','prince'),                                                                                                                                                                                           
          ('dandaman419@aol.com','daniel','mazzola'),                                                                                                                                                                                                
          ('yfrangarcia@gmail.com','yfran','garcia'),                                                                                                                                                                                                
          ('stevencohen14@gmail.com','steven','cohen'),                                                                                                                                                                                              
          ('zzannino@gmail.com','zachary','zannino'),                                                                                                                                                                                                
          ('caba108@aol.com','steven','caba'),                                                                                                                                                                                                       
          ('applefunding@aol.com','joseph','wald'),                                                                                                                                                                                                  
          ('superfocused@aol.com','babajide','adegunle'),                                                                                                                                                                                            
          ('grob1985@gmail.com','germin','robinson'),                                                                                                                                                                                                
          ('dquinn@globalsai.com','darren','quinn'),                                                                                                                                                                                                 
          ('arrubin5@gmail.com','andrew','rubin'),                                                                                                                                                                                                   
          ('subway12569@gmail.com','rajnish','bhutani'),                                                                                                                                                                                             
          ('kroney@gmail.com','eric','kronenberger'),                                                                                                                                                                                                
          ('giannotti.daniel@gmail.com','daniel','giannotti'),                                                                                                                                                                                       
          ('dottytopboss@gmail.com','odane','hazel'),                                                                                                                                                                                                
          ('tylermorrel14@winchendon.org','tyler','morrel'),                                                                                                                                                                                         
          ('cwalsh525@gmail.com','christopher','walsh'),                                                                                                                                                                                             
          ('jamesceruzzi@gmail.com','james','ceruzzi'),                                                                                                                                                                                              
          ('haukmilo@gmail.com','miloslav','hauk'),                                                                                                                                                                                                  
          ('bfredawvu@me.com','brian','freda'),                                                                                                                                                                                                      
          ('fangajizmir@gmail.com','izmir','fangaj'),                                                                                                                                                                                                
          ('apb1125@gmail.com','eric','bost'),                                                                                                                                                                                                       
          ('farrell_23@live.com','kevin','farrell'),                                                                                                                                                                                                 
          ('poker4ever78@yahoo.com','robert','boyko'),                                                                                                                                                                                               
          ('mlohser@aol.com','marc','lohser'),                                                                                                                                                                                                       
          ('benjamingoldberg14@gmail.com','benjamin','goldberg'),                                                                                                                                                                                    
          ('jaji207@yahoo.com','manuel','diaz'),                                                                                                                                                                                                     
          ('chrisboyer29@gmail.com','christopher','boyer'),                                                                                                                                                                                          
          ('adamericgoodman@gmail.com','adam','goodman')                                                                                                                                                                                             
      ) AS t(email, first_name, last_name)                                                                                                                                                                                                           
  )           ,                                                                                                                                                                                                                                       
                          email_matches AS (                                                                                                                                                                                                                                 
      SELECT      
          fg.*,
          yl.first_name  AS list_first_name,
          yl.last_name   AS list_last_name,                                                                                                                                                                                                          
          'Email'        AS MATCH_TYPE
      FROM FDE_FBG_PII_INFO.FDE_FBG_PII_INFO.FANGRAPH_PII_V fg                                                                                                                                                                                       
      INNER JOIN your_list yl                                                                                                                                                                                                                        
          ON lower(fg.FANGRAPH_EMAIL) = yl.email
      WHERE COALESCE(fg.FBG_EXCLUSION, FALSE) != TRUE                                                                                                                                                                                                
  ),                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                     
  name_matches AS (                                                                                                                                                                                                                                  
      SELECT      
          fg.*,
          yl.first_name  AS list_first_name,
          yl.last_name   AS list_last_name,
          'Name'         AS MATCH_TYPE
      FROM FDE_FBG_PII_INFO.FDE_FBG_PII_INFO.FANGRAPH_PII_V fg                                                                                                                                                                                       
      INNER JOIN your_list yl
          ON lower(fg.FANGRAPH_FIRST_NAME) = lower(yl.first_name)                                                                                                                                                                                    
          AND lower(fg.FANGRAPH_LAST_NAME) = lower(yl.last_name)
      WHERE COALESCE(fg.FBG_EXCLUSION, FALSE) != TRUE                                                                                                                                                                                                
      -- only pick up people not already matched by email
      AND lower(yl.email) NOT IN (SELECT lower(FANGRAPH_EMAIL) FROM email_matches)                                                                                                                                                                   
  )                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                     
  SELECT                                                                                                                                                                                                                                             
      MATCH_TYPE, 
      list_first_name,                                                                                                                                                                                                                               
      list_last_name,
                                                                                                                                                                                                                                                     
      -- ── WHO THEY ARE ──────────────────────────────────────                                                                                                                                                                                      
      fg.FANGRAPH_FIRST_NAME,
      fg.FANGRAPH_LAST_NAME,                                                                                                                                                                                                                         
      fg.FANGRAPH_EMAIL,
      fg.FANGRAPH_AGE_RANGE,                                                                                                                                                                                                                         
  
      -- ── CONTACT ───────────────────────────────────────────                                                                                                                                                                                      
      fg.FANGRAPH_PHONE,
      fg.FANGRAPH_PHONE_DNC,                                                                                                                                                                                                                         
      fg.COMMERCE_MOBILE_NUMBER,
      fg.AAIA_PHONE,                                                                                                                                                                                                                                 
  
      -- ── WHERE THEY LIVE ───────────────────────────────────                                                                                                                                                                                      
      fg.FANGRAPH_CITY,
      fg.FANGRAPH_STATE,                                                                                                                                                                                                                             
      fg.FANGRAPH_ZIP,

      -- ── SPORTS PREFERENCES ────────────────────────────────                                                                                                                                                                                      
      fg.FANGRAPH_PREFERENCE_NFL,
      fg.FANGRAPH_PREFERENCE_NBA,                                                                                                                                                                                                                    
      fg.FANGRAPH_PREFERENCE_MLB,                                                                                                                                                                                                                    
      fg.FANGRAPH_PREFERENCE_NHL,
      fg.FANGRAPH_PREFERENCE_NCAA,                                                                                                                                                                                                                   
      fg.FANGRAPH_PREFERENCE_NFL_TEAMS,
      fg.FANGRAPH_PREFERENCE_NBA_TEAMS,                                                                                                                                                                                                              
      fg.FANGRAPH_PREFERENCE_MLB_TEAMS,
                                                                                                                                                                                                                                                     
      -- ── FANATICS ECOSYSTEM SPEND ──────────────────────────                                                                                                                                                                                      
      fg.FANATICS_ONE_CURRENT_TIER,
      fg.COMMERCE_ORDER_AMOUNT_TOTAL           AS COMMERCE_SPEND,                                                                                                                                                                                    
      fg.LIVE_TOTAL_GMS                        AS LIVE_SPEND,                                                                                                                                                                                        
      fg.TOPPS_COM_GMV_TOTAL                   AS TOPPS_SPEND,                                                                                                                                                                                       
      COALESCE(fg.COMMERCE_ORDER_AMOUNT_TOTAL, 0)                                                                                                                                                                                                    
          + COALESCE(fg.LIVE_TOTAL_GMS, 0)                                                                                                                                                                                                           
          + COALESCE(fg.TOPPS_COM_GMV_TOTAL, 0) AS TOTAL_ECOSYSTEM_SPEND,                                                                                                                                                                            
                                                                                                                                                                                                                                                     
      -- ── NET WORTH ─────────────────────────────────────────                                                                                                                                                                                      
      fg.AAIA_NET_WORTH_HH,                                                                                                                                                                                                                          
      fg.AAIA_NET_WORTH_MIDPT_HH,                                                                                                                                                                                                                    
      fg.AAIA_INCOME_HH,
      fg.AAIA_INCOME_MIDPTS_HH,                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                     
      -- ── BETTING & GAMING AFFINITY ─────────────────────────                                                                                                                                                                                      
      fg.AAIA_GAMBLING_AFFINITY,                                                                                                                                                                                                                     
      fg.AAIA_FOOTBALL_AFFINITY,                                                                                                                                                                                                                     
      fg.AAIA_BASEBALL_AFFINITY,
      fg.AAIA_BASKETBALL_AFFINITY,
      fg.AAIA_HOCKEY_AFFINITY,                                                                                                                                                                                                                       
   
      -- ── FBG RELATIONSHIP ──────────────────────────────────                                                                                                                                                                                      
      fg.FBG_CUSTOMER_INDICATOR,
      fg.FBG_TRANSACTION_TOTAL,                                                                                                                                                                                                                      
      fg.FBG_LAST_TRANSACTION_TIMESTAMP,
      fg.FBG_VIP_TIERS,                                                                                                                                                                                                                              
      CASE        
          WHEN COALESCE(fg.FBG_CUSTOMER_INDICATOR, FALSE) = FALSE
              THEN 'A — No FBG account'                                                                                                                                                                                                              
          WHEN fg.FBG_CUSTOMER_INDICATOR = TRUE
               AND COALESCE(fg.FBG_TRANSACTION_TOTAL, 0) < 500                                                                                                                                                                                       
               AND (fg.FBG_LAST_TRANSACTION_TIMESTAMP < DATEADD('day', -90, CURRENT_DATE)                                                                                                                                                            
                    OR fg.FBG_LAST_TRANSACTION_TIMESTAMP IS NULL)                                                                                                                                                                                    
              THEN 'B — Dormant'                                                                                                                                                                                                                     
          WHEN fg.FBG_CUSTOMER_INDICATOR = TRUE                                                                                                                                                                                                      
               AND COALESCE(fg.FBG_TRANSACTION_TOTAL, 0) >= 500                                                                                                                                                                                      
               AND (fg.FBG_VIP_TIERS IS NULL OR fg.FBG_VIP_TIERS = '')
              THEN 'C — Active, not VIP'
          WHEN fg.FBG_VIP_TIERS IS NOT NULL AND fg.FBG_VIP_TIERS != ''                                                                                                                                                                               
              THEN 'D — FBG VIP'
          ELSE 'E — Review'                                                                                                                                                                                                                          
      END AS FBG_RELATIONSHIP
                                                                                                                                                                                                                                                     
  FROM (          
      SELECT * FROM email_matches
      UNION ALL
      SELECT * FROM name_matches
  ) fg

  ORDER BY
      MATCH_TYPE ASC,
      FBG_RELATIONSHIP ASC,
      TOTAL_ECOSYSTEM_SPEND DESC NULLS LAST;
