-- Query ID: 01c399c4-0212-6b00-24dd-070319275627
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:20:56.439000+00:00
-- Elapsed: 866ms
-- Environment: FBG

with W1 as (select Q2.WEEK_NUMBER, count(Q3.WEEK_NUM) COUNT_223 from (select WEEK_NUMBER from (select WEEK_NUMBER, row_number() over (partition by WEEK_NUMBER order by '' asc) ROWNUMBER_16 from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_WEEKLY_FORECAST qualify ROWNUMBER_16 = 1) Q1) Q2 left join (select NEW_SEGMENTS_DAILY_FORECAST.WEEK_NUM from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_FORECAST full join (select OSB_SEGMENT, BUS_DATE::timestamp_ltz CAST_65 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_DAILY_DS) Q4 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q4.CAST_65 and NEW_SEGMENTS_DAILY_FORECAST.USER_SEGMENT = Q4.OSB_SEGMENT left join FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_TARGETS Q6 on NEW_SEGMENTS_DAILY_FORECAST."DATE" = Q6.DATE_TARGET left join (select BUS_DATE_FC::timestamp_ltz CAST_121 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_FAIRNESS_DS) Q8 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q8.CAST_121 left join (select BUS_DATE::timestamp_ltz CAST_161 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_MTD_PL_DS) Q10 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q10.CAST_161 left join (select NEW_SEGMENTS_REVENUE_FLOW_THROUGH."DATE" from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_REVENUE_FLOW_THROUGH left join (select EHOLD_BUCKET, BUS_DATE::timestamp_ltz CAST_203 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_REVENUE_FLOW_DS) Q13 on try_to_timestamp_ltz(NEW_SEGMENTS_REVENUE_FLOW_THROUGH."DATE") = Q13.CAST_203 and NEW_SEGMENTS_REVENUE_FLOW_THROUGH.HOLD_BUCKET = Q13.EHOLD_BUCKET) Q12 on NEW_SEGMENTS_DAILY_FORECAST."DATE" = Q12."DATE") Q3 on Q2.WEEK_NUMBER = Q3.WEEK_NUM group by Q2.WEEK_NUMBER) select COUNT_230 "Count of Week Number", SUM_231 "CountIf of Calc", SUM_232 "CountIf of Calc (1)", SUM_233 "CountIf of Calc (2)", WEEK_NUMBER "Week Number", GT_224 "__cond_JOIN_AGGR_MULTI_MATCHED_CF", EQ_225 "__cond_JOIN_AGGR_UNMATCHED_CF" from (select Q20.WEEK_NUMBER, Q20.GT_224, Q20.EQ_225, Q22.COUNT_230, Q22.SUM_231, Q22.SUM_232, Q22.SUM_233 from (select WEEK_NUMBER, COUNT_223 > 1 GT_224, COUNT_223 = 0 EQ_225 from (select * from W1 Q18 order by WEEK_NUMBER asc limit 10001) Q19) Q20 cross join (select count(WEEK_NUMBER) COUNT_230, sum(iff(COUNT_223 = 0, 1, 0)) SUM_231, sum(iff(COUNT_223 = 1, 1, 0)) SUM_232, sum(iff(COUNT_223 > 1, 1, 0)) SUM_233 from W1 Q21) Q22) Q24 order by WEEK_NUMBER asc limit 10001

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-1-34rdU89t8adkDkUiTTTdmE?:displayNodeId=oDretBDM2w","kind":"adhoc","request-id":"g019d73e7aa9d7baea094c0fac5821f1f","user-id":"L3vHZYjsyKujxXKFJJVEoOSTC4m5s","email":"sai.manish@squadrondata.com"}
