-- Query ID: 01c399c7-0212-6e7d-24dd-07031927af43
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Executed: 2026-04-09T20:23:22.350000+00:00
-- Elapsed: 230ms
-- Environment: FBG

SELECT
    CRYPTO.PROCESS_DATE,
    CRYPTO.PAYMENTS AS PAY_CDNA,
    FMX.PAYMENT AS PAY_FMX,
    CRYPTO.WITHDRAWALS AS WD_CDNA,
    FMX.WITHDRAWALS AS WD_FMX
FROM FBG_SOURCE.CRYPTO.TSP_EOD_SUMMARY CRYPTO
JOIN FBG_FINANCE.STAGING.FMX_RECONCILIATION_REPORT_DAILY FMX
  ON CRYPTO.PROCESS_DATE = FMX.TRANS_DATE_EST
WHERE CRYPTO.PAYMENTS <> 0 OR FMX.PAYMENT IS NOT NULL OR CRYPTO.WITHDRAWALS <> 0 OR FMX.WITHDRAWALS IS NOT NULL
ORDER BY PROCESS_DATE
