-- Query ID: 01c39a41-0212-67a9-24dd-070319431f83
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:25:04.025000+00:00
-- Elapsed: 1838ms
-- Environment: FBG

WITH __casino_daily_settled_agg AS (
  SELECT
    acco_id,
    game_id,
    settled_date_alk,
    cash_bet_count,
    cash_bet_stake,
    casino_credit_bet_count,
    casino_credit_bet_stake,
    expected_ggr,
    expected_ngr,
    freespin_bet_count,
    freespin_bet_stake,
    ggr,
    is_test_account,
    ngr,
    total_bet_count,
    total_payout,
    total_stake
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_DAILY_SETTLED_AGG
)
/* Last 7 days activity summary */
SELECT
  SUM(cd.total_stake) AS total_handle,
  SUM(cd.cash_bet_stake) AS cash_handle,
  SUM(cd.freespin_bet_stake) AS freespin_handle,
  SUM(cd.casino_credit_bet_stake) AS credit_handle,
  SUM(cd.total_payout) AS total_payout,
  SUM(cd.ggr) AS ggr,
  SUM(cd.ngr) AS ngr,
  SUM(cd.expected_ggr) AS expected_ggr,
  SUM(cd.expected_ngr) AS expected_ngr,
  SUM(cd.total_bet_count) AS total_bets,
  SUM(cd.cash_bet_count) AS cash_bets,
  SUM(cd.freespin_bet_count) AS freespin_bets,
  SUM(cd.casino_credit_bet_count) AS credit_bets,
  COUNT(DISTINCT cd.settled_date_alk) AS active_days,
  COUNT(DISTINCT cd.game_id) AS unique_games_played,
  MIN(cd.settled_date_alk) AS first_active_date,
  MAX(cd.settled_date_alk) AS last_active_date
FROM __casino_daily_settled_agg AS cd
WHERE
  cd.acco_id = '2144018'
  AND cd.settled_date_alk >= DATEADD(DAY, -7, CURRENT_DATE)
  AND cd.is_test_account = '0' /* Generated by Cortex */;
