-- Query ID: 01c399c4-0212-6e7d-24dd-07031927a03b
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:20:54.566000+00:00
-- Elapsed: 715ms
-- Environment: FBG

select COUNT_207 "row-count" from (select count(1) COUNT_207 from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_FORECAST full join (select OSB_SEGMENT, BUS_DATE::timestamp_ltz CAST_48 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_DAILY_DS) Q2 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q2.CAST_48 and NEW_SEGMENTS_DAILY_FORECAST.USER_SEGMENT = Q2.OSB_SEGMENT left join FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_TARGETS Q4 on NEW_SEGMENTS_DAILY_FORECAST."DATE" = Q4.DATE_TARGET left join (select BUS_DATE_FC::timestamp_ltz CAST_104 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_FAIRNESS_DS) Q6 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q6.CAST_104 left join (select BUS_DATE::timestamp_ltz CAST_144 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_MTD_PL_DS) Q8 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q8.CAST_144 left join (select NEW_SEGMENTS_REVENUE_FLOW_THROUGH."DATE" from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_REVENUE_FLOW_THROUGH left join (select EHOLD_BUCKET, BUS_DATE::timestamp_ltz CAST_186 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_REVENUE_FLOW_DS) Q11 on try_to_timestamp_ltz(NEW_SEGMENTS_REVENUE_FLOW_THROUGH."DATE") = Q11.CAST_186 and NEW_SEGMENTS_REVENUE_FLOW_THROUGH.HOLD_BUCKET = Q11.EHOLD_BUCKET) Q10 on NEW_SEGMENTS_DAILY_FORECAST."DATE" = Q10."DATE") Q1

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-1-34rdU89t8adkDkUiTTTdmE?:displayNodeId=uGCtSCO85T","kind":"adhoc","request-id":"g019d73e7a26879849aca89bd0124fd20","user-id":"L3vHZYjsyKujxXKFJJVEoOSTC4m5s","email":"sai.manish@squadrondata.com"}
