-- Query ID: 01c39a23-0212-6cb9-24dd-0703193c7f5f
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Executed: 2026-04-09T21:55:18.953000+00:00
-- Elapsed: 958ms
-- Environment: FBG

SELECT DISTINCT LEG_MARKET_TYPE AS MARKET_CODE, LEG_MARKET AS MARKET_NAME
FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
WHERE EVENT_SPORT_NAME = 'SOCCER'
  AND WAGER_PLACED_TIME_EST >= DATEADD('day', -7, CURRENT_TIMESTAMP())
  AND (
    LEG_MARKET ILIKE '%2nd half%'
    OR LEG_MARKET ILIKE '%second half%'
    OR LEG_MARKET ILIKE '%half time%'
    OR LEG_MARKET ILIKE '%halftime%'
    OR LEG_MARKET ILIKE '%HT/FT%'
    OR LEG_MARKET ILIKE '%both halves%'
    OR LEG_MARKET ILIKE '%either half%'
    OR LEG_MARKET ILIKE '%half of%'
    OR LEG_MARKET ILIKE '%both half%'
    OR LEG_MARKET ILIKE '%in both%half%'
  )
ORDER BY MARKET_CODE, MARKET_NAME
