-- Query ID: 01c399c6-0212-6dbe-24dd-07031927b473
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:22:08.967000+00:00
-- Elapsed: 500ms
-- Environment: FBG

select CAST_39 "Bus Date", FTU_LIFECYCLE "Ftu Lifecycle", OSB_SEGMENT "Osb Segment", CASH_HANDLE "Cash Handle", TRADING_WIN "Trading Win", X_TRADING_WIN "X Trading Win", BOOST_COST "Boost Cost", CASH_GGR "Cash Ggr", EXPECTED_GGR "Expected Ggr", BOOSTED_HANDLE "Boosted Handle", BOOSTED_TW "Boosted Tw", BOOSTED_ETW "Boosted Etw", BOOSTED_GGR "Boosted Ggr", BOOSTED_EGGR "Boosted Eggr", PROMO_COSTS "Promo Costs", OSB_NGR "Osb Ngr", CASH_BACK "Cash Back", FC_RETENTION_COSTS "Fc Retention Costs", DEPOSIT_RETENTION_COSTS "Deposit Retention Costs", OTHER_RETENTION_COSTS "Other Retention Costs", ACQUISITION_COSTS "Acquisition Costs", MIGRATION_COSTS "Migration Costs", MTD_ACTIVES "Mtd Actives", NEW_UNIQUE_ACTIVES "NEW_UNIQUE_ACTIVES (Custom SQL Query) #1", EXPECTED_PROMO_COSTS_MTD "Expected Promo Costs Mtd", OSB_ENGR_MTD "Osb Engr Mtd", DAY_ACTIVES "Day Actives", PRIOR_MONTH_ACTIVES "Prior Month Actives", RETAINED_MTD "Retained Mtd", BOOSTED_EGGR_41 "Boosted eNGR", BOOSTED_GGR_37 "Boosted NGR", SUB_38 "GGR Minus Cashback", SUB_35 "Non-Boosted eGGR", SUB_30 "Non-Boosted eNGR", SUB_40 "Non-Boosted eTW", SUB_36 "Non-Boosted GGR", SUB_33 "Non-Boosted Handle", SUB_29 "Non-Boosted NGR", SUB_34 "Non-Boosted TW", ADD_32 "Retention Total", V_31 "Summary MTD Flag (P&L)" from (select FTU_LIFECYCLE, OSB_SEGMENT, CASH_HANDLE, TRADING_WIN, X_TRADING_WIN, BOOST_COST, CASH_GGR, EXPECTED_GGR, BOOSTED_HANDLE, BOOSTED_TW, BOOSTED_ETW, BOOSTED_GGR, BOOSTED_EGGR, PROMO_COSTS, OSB_NGR, CASH_BACK, FC_RETENTION_COSTS, DEPOSIT_RETENTION_COSTS, OTHER_RETENTION_COSTS, ACQUISITION_COSTS, MIGRATION_COSTS, MTD_ACTIVES, NEW_UNIQUE_ACTIVES, EXPECTED_PROMO_COSTS_MTD, OSB_ENGR_MTD, DAY_ACTIVES, PRIOR_MONTH_ACTIVES, RETAINED_MTD, OSB_NGR - BOOSTED_GGR SUB_29, OSB_ENGR_MTD - BOOSTED_EGGR SUB_30, 'Argument 2 invalid for function ''DateTrunc''. Expected date; received variant.' V_31, FC_RETENTION_COSTS + CASH_BACK + DEPOSIT_RETENTION_COSTS + OTHER_RETENTION_COSTS ADD_32, CASH_HANDLE - BOOSTED_HANDLE SUB_33, TRADING_WIN - BOOSTED_TW SUB_34, EXPECTED_GGR - BOOSTED_EGGR SUB_35, CASH_GGR - BOOSTED_GGR SUB_36, BOOSTED_GGR BOOSTED_GGR_37, CASH_GGR - CASH_BACK SUB_38, BUS_DATE::timestamp_ltz CAST_39, X_TRADING_WIN - BOOSTED_ETW SUB_40, BOOSTED_EGGR BOOSTED_EGGR_41 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_MTD_PL_DS) Q1 limit 25301

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-1-34rdU89t8adkDkUiTTTdmE?:displayNodeId=p_VxKJ6VTQ","kind":"adhoc","request-id":"g019d73e8c876727abb228ac5c8056eb1","user-id":"L3vHZYjsyKujxXKFJJVEoOSTC4m5s","email":"sai.manish@squadrondata.com"}
