-- Query ID: 01c39a31-0212-6dbe-24dd-0703193fcec3
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:09:20.250000+00:00
-- Elapsed: 7586ms
-- Environment: FBG

WITH __trading_sportsbook_mart AS (
  SELECT
    account_id,
    is_free_bet_wager,
    is_test_wager,
    leg_sport_category,
    market_definition,
    market_grouping,
    wager_channel,
    wager_status,
    wager_settlement_time_alk,
    total_cash_ggr_by_legs,
    total_cash_stake_by_legs,
    total_ggr_by_legs,
    total_stake_by_legs,
    wager_id
  FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
), seasonal_data AS (
  SELECT
    CASE
      WHEN leg_sport_category = 'NBA'
      AND TO_DATE(wager_settlement_time_alk) >= '2024-10-01'
      AND TO_DATE(wager_settlement_time_alk) <= '2025-06-30'
      THEN 'NBA 2024-25'
      WHEN leg_sport_category = 'NFL'
      AND TO_DATE(wager_settlement_time_alk) >= '2024-09-01'
      AND TO_DATE(wager_settlement_time_alk) <= '2025-02-28'
      THEN 'NFL 2024-25'
      WHEN leg_sport_category = 'MLB'
      AND TO_DATE(wager_settlement_time_alk) >= '2024-03-01'
      AND TO_DATE(wager_settlement_time_alk) <= '2024-10-31'
      THEN 'MLB 2024'
      WHEN leg_sport_category = 'NCAA Basketball'
      AND TO_DATE(wager_settlement_time_alk) >= '2024-11-01'
      AND TO_DATE(wager_settlement_time_alk) <= '2025-04-30'
      THEN 'NCAAB 2024-25'
      WHEN leg_sport_category = 'CFB'
      AND TO_DATE(wager_settlement_time_alk) >= '2024-08-01'
      AND TO_DATE(wager_settlement_time_alk) <= '2025-01-31'
      THEN 'CFB 2024-25'
      WHEN leg_sport_category = 'Soccer'
      AND TO_DATE(wager_settlement_time_alk) >= '2024-08-01'
      AND TO_DATE(wager_settlement_time_alk) <= '2025-05-31'
      THEN 'Soccer 2024-25'
    END AS season,
    leg_sport_category,
    market_definition,
    total_cash_stake_by_legs,
    total_cash_ggr_by_legs,
    total_stake_by_legs,
    total_ggr_by_legs,
    wager_id,
    account_id
  FROM __trading_sportsbook_mart
  WHERE
    wager_status IN ('ACCEPTED', 'SETTLED')
    AND wager_channel = 'INTERNET'
    AND is_test_wager = 'FALSE'
    AND is_free_bet_wager = 'FALSE'
    AND market_grouping = 'OTHER - LIGHTNING MARKETS'
)
SELECT
  season,
  leg_sport_category,
  market_definition,
  COUNT(DISTINCT wager_id) AS num_bets,
  COUNT(DISTINCT account_id) AS num_bettors,
  SUM(total_cash_stake_by_legs) AS cash_handle,
  SUM(total_cash_ggr_by_legs) AS cash_ggr,
  SUM(total_cash_ggr_by_legs) / NULLIF(NULLIF(SUM(total_cash_stake_by_legs), 0), 0) AS cash_hold_pct,
  SUM(total_stake_by_legs) AS total_handle,
  SUM(total_ggr_by_legs) AS total_ggr,
  SUM(total_ggr_by_legs) / NULLIF(NULLIF(SUM(total_stake_by_legs), 0), 0) AS total_hold_pct
FROM seasonal_data
WHERE
  NOT season IS NULL
GROUP BY
  1,
  2,
  3
ORDER BY
  CASE leg_sport_category
    WHEN 'NFL'
    THEN 1
    WHEN 'NBA'
    THEN 2
    WHEN 'MLB'
    THEN 3
    WHEN 'CFB'
    THEN 4
    WHEN 'NCAA Basketball'
    THEN 5
    WHEN 'Soccer'
    THEN 6
  END,
  cash_handle DESC /* Generated by Cortex */;
