-- Query ID: 01c39a3a-0212-644a-24dd-07031942645f
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:18:44.052000+00:00
-- Elapsed: 3176ms
-- Environment: FBG

WITH __trading_sportsbook_mart AS (
  SELECT
    is_free_bet_wager,
    is_test_wager,
    leg_sport_category,
    market_grouping,
    wager_channel,
    wager_status,
    wager_settlement_time_alk,
    total_cash_stake_by_legs
  FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
), all_data AS (
  SELECT
    leg_sport_category,
    CASE
      WHEN market_grouping = 'OTHER - LIGHTNING MARKETS'
      THEN 'Lightning'
      ELSE 'Non-Lightning'
    END AS market_type,
    total_cash_stake_by_legs
  FROM __trading_sportsbook_mart
  WHERE
    wager_status IN ('ACCEPTED', 'SETTLED')
    AND wager_channel = 'INTERNET'
    AND is_test_wager = 'FALSE'
    AND is_free_bet_wager = 'FALSE'
    AND TO_DATE(wager_settlement_time_alk) >= DATEADD(YEAR, -1, CURRENT_DATE)
    AND TO_DATE(wager_settlement_time_alk) <= CURRENT_DATE
    AND leg_sport_category IN ('NFL', 'NBA', 'MLB', 'CFB', 'NCAA Basketball', 'Soccer')
)
SELECT
  leg_sport_category,
  SUM(CASE WHEN market_type = 'Lightning' THEN total_cash_stake_by_legs ELSE 0 END) AS lightning_handle,
  SUM(total_cash_stake_by_legs) AS total_handle,
  lightning_handle / NULLIF(NULLIF(total_handle, 0), 0) AS lightning_pct
FROM all_data
GROUP BY
  1
ORDER BY
  total_handle DESC /* Generated by Cortex */;
