-- Query ID: 01c39a26-0212-6e7d-24dd-0703193d64db
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T21:58:04.136000+00:00
-- Elapsed: 3577ms
-- Environment: FBG

WITH __trading_sportsbook_mart AS (
  SELECT
    account_id,
    event_league,
    event_name,
    is_test_wager,
    leg_market,
    leg_selection,
    wager_channel,
    wager_status,
    event_time_alk,
    total_cash_stake_by_legs,
    total_non_cash_stake_by_legs,
    total_stake_by_legs,
    wager_id
  FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
), __customer_mart AS (
  SELECT
    is_test_account,
    acco_id
  FROM FBG_ANALYTICS_ENGINEERING.CUSTOMERS.CUSTOMER_MART
)
SELECT
  t.leg_market AS market,
  t.leg_selection AS selection,
  COUNT(DISTINCT t.wager_id) AS total_bets,
  COUNT(DISTINCT t.account_id) AS unique_users,
  SUM(t.total_stake_by_legs) AS total_handle,
  SUM(t.total_cash_stake_by_legs) AS cash_handle,
  SUM(t.total_non_cash_stake_by_legs) AS bonus_handle
FROM __trading_sportsbook_mart AS t
INNER JOIN __customer_mart AS c
  ON t.account_id = c.acco_id
WHERE
  (
    t.event_name IN ('Masters Tournament', 'US Masters')
    OR (
      t.event_league = 'Masters Tournament'
    )
  )
  AND TO_DATE(t.event_time_alk) >= '2026-04-01'
  AND t.wager_status IN ('ACCEPTED', 'SETTLED')
  AND t.is_test_wager = 'FALSE'
  AND t.wager_channel = 'INTERNET'
  AND c.is_test_account = 'FALSE'
  AND t.leg_market IN ('Winner', 'Top 5', 'Top 10', 'Top 20')
GROUP BY
  1,
  2
ORDER BY
  1,
  cash_handle DESC NULLS LAST /* Generated by Cortex */;
