-- Query ID: 01c399c7-0212-6b00-24dd-07031927e6a3
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T20:23:59.077000+00:00
-- Elapsed: 998ms
-- Environment: FBG

WITH __cs_cases AS (
  SELECT
    case_id,
    case_type,
    chat_full_transcript,
    current_value_band,
    is_ai_agent,
    product_flag,
    case_created_est,
    csat_score,
    is_contained,
    is_escalated
  FROM FBG_ANALYTICS.OPERATIONS.CS_CASES
)
/* Get the CSAT breakdown for impacted cases specifically in the last 3 months */ /* Also look at VIP breakdown */
SELECT
  current_value_band,
  COUNT(DISTINCT case_id) AS total_cases,
  SUM(CASE WHEN is_contained = 1 THEN 1 ELSE 0 END) AS contained,
  ROUND(
    SUM(CASE WHEN is_contained = 1 THEN 1 ELSE 0 END) / NULLIF(NULLIF(COUNT(DISTINCT case_id), 0), 0),
    4
  ) AS containment_rate,
  SUM(CASE WHEN is_escalated = 1 THEN 1 ELSE 0 END) AS escalated,
  ROUND(AVG(csat_score), 2) AS avg_csat,
  COUNT(DISTINCT CASE WHEN NOT csat_score IS NULL THEN case_id END) AS cases_with_csat
FROM __cs_cases
WHERE
  is_ai_agent = 'True'
  AND product_flag = 'Casino'
  AND case_created_est >= DATEADD(MONTH, -3, CURRENT_DATE)
  AND (
    chat_full_transcript ILIKE '%wager history%'
    OR chat_full_transcript ILIKE '%wagering history%'
    OR chat_full_transcript ILIKE '%bet history%'
    OR chat_full_transcript ILIKE '%casino credit%'
    OR chat_full_transcript ILIKE '%casino balance%'
    OR chat_full_transcript ILIKE '%account balance%'
    OR chat_full_transcript ILIKE '%my balance%'
    OR chat_full_transcript ILIKE '%my wager%'
    OR chat_full_transcript ILIKE '%my bet%'
    OR chat_full_transcript ILIKE '%transaction history%'
    OR chat_full_transcript ILIKE '%play history%'
    OR chat_full_transcript ILIKE '%game history%'
    OR chat_full_transcript ILIKE '%recent wager%'
    OR chat_full_transcript ILIKE '%recent bet%'
    OR chat_full_transcript ILIKE '%bonus balance%'
    OR chat_full_transcript ILIKE '%promo balance%'
    OR chat_full_transcript ILIKE '%promotional credit%'
    OR chat_full_transcript ILIKE '%free credit%'
    OR chat_full_transcript ILIKE '%slot history%'
    OR chat_full_transcript ILIKE '%spin history%'
    OR case_type = 'Casino Credit'
  )
GROUP BY
  current_value_band
ORDER BY
  total_cases DESC /* Generated by Cortex */;
