-- Query ID: 01c399cf-0212-67a8-24dd-070319298567
-- Database: unknown
-- Schema: unknown
-- Warehouse: AE_SIGMA_PROD
-- Executed: 2026-04-09T20:31:42.345000+00:00
-- Elapsed: 3107ms
-- Environment: FBG

select COUNT_226 "row-count" from (select count(1) COUNT_226 from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_FORECAST left join FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_DAILY_TARGETS Q2 on NEW_SEGMENTS_DAILY_FORECAST."DATE" = Q2.DATE_TARGET left join (select BUS_DATE_FC::timestamp_ltz CAST_65 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_FAIRNESS_DS) Q4 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q4.CAST_65 left join (select OSB_SEGMENT, BUS_DATE::timestamp_ltz CAST_105 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_MTD_PL_DS) Q6 on try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE") = Q6.CAST_105 and NEW_SEGMENTS_DAILY_FORECAST.USER_SEGMENT = Q6.OSB_SEGMENT left join (select NEW_SEGMENTS_REVENUE_FLOW_THROUGH."DATE" from FBG_SHEETZU."DEFAULT".NEW_SEGMENTS_REVENUE_FLOW_THROUGH left join (select EHOLD_BUCKET, BUS_DATE::timestamp_ltz CAST_147 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_REVENUE_FLOW_DS) Q9 on try_to_timestamp_ltz(NEW_SEGMENTS_REVENUE_FLOW_THROUGH."DATE") = Q9.CAST_147 and NEW_SEGMENTS_REVENUE_FLOW_THROUGH.HOLD_BUCKET = Q9.EHOLD_BUCKET) Q8 on NEW_SEGMENTS_DAILY_FORECAST."DATE" = Q8."DATE" full join (select OSB_SEGMENT, BUS_DATE::timestamp_ltz CAST_183 from FBG_ANALYTICS.PRODUCT_AND_CUSTOMER.SBK_FORECASTING_DAILY_DS) Q12 on date_trunc(day, try_to_timestamp_ltz(NEW_SEGMENTS_DAILY_FORECAST."DATE")) = Q12.CAST_183 and NEW_SEGMENTS_DAILY_FORECAST.USER_SEGMENT = Q12.OSB_SEGMENT) Q1

-- Sigma Σ {"sourceUrl":"https://app.sigmacomputing.com/bet-fanatics/data-model/NEW-Sportsbook-Forecasting-Report_Data-Model-1q0KELPDUp3VLveHb0w7MT?:displayNodeId=OlU1Z1cw1m","kind":"adhoc","request-id":"g019d73f187b87655a333ca688aef91ce","user-id":"L3vHZYjsyKujxXKFJJVEoOSTC4m5s","email":"sai.manish@squadrondata.com"}
