-- Query ID: 01c39a41-0212-67a8-24dd-07031943a043
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_SER_XL_WH
-- Executed: 2026-04-09T22:25:31.924000+00:00
-- Elapsed: 542ms
-- Environment: FBG

WITH __casino_daily_settled_agg AS (
  SELECT
    acco_id,
    state,
    settled_date_alk,
    ggr,
    is_test_account,
    ngr,
    total_bet_count,
    total_stake
  FROM FBG_ANALYTICS_ENGINEERING.CASINO.CASINO_DAILY_SETTLED_AGG
)
/* State activity breakdown last 30 days */
SELECT
  cd.state,
  SUM(cd.total_stake) AS handle,
  SUM(cd.ggr) AS ggr,
  SUM(cd.ngr) AS ngr,
  SUM(cd.total_bet_count) AS total_bets,
  COUNT(DISTINCT cd.settled_date_alk) AS active_days
FROM __casino_daily_settled_agg AS cd
WHERE
  cd.acco_id = '2144018'
  AND cd.settled_date_alk >= DATEADD(DAY, -30, CURRENT_DATE)
  AND cd.is_test_account = '0'
GROUP BY
  cd.state
ORDER BY
  handle DESC NULLS LAST /* Generated by Cortex */;
