-- Query ID: 01c399da-0212-67a9-24dd-0703192c1127
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_L_WH
-- Executed: 2026-04-09T20:42:30.491000+00:00
-- Elapsed: 31747ms
-- Environment: FBG

WITH base AS (
        SELECT
            rt.TRANSACTION_TYPE,
            rt.TRANSACTION_FUND_TYPE,
            rt.TRANSACTION_AMOUNT,
            rt.TRANSACTION_WAGER_ID,
            rt.TRANSACTION_ACCOUNT_ID,
            rt.SPORTSBOOK_WAGER_BET_TYPE,
            bp.event_time::DATE AS event_date,
            bp.live_bet,
            bp.mrkt_type,
            bp.node_id,
            SPLIT_PART(bp.mrkt_type, ':', -1) AS mrkt_suffix,
            CASE
                WHEN SPLIT_PART(bp.mrkt_type, ':', -1) IN ('ML','12', 'NCAABCHAMPEALL') THEN 'Moneyline'
                WHEN SPLIT_PART(bp.mrkt_type, ':', -1) IN ('OU','BTTS', 'DNB') THEN 'Total'
                WHEN SPLIT_PART(bp.mrkt_type, ':', -1) IN ('AH','HC', 'SPRD') THEN 'Spread'
                WHEN SPLIT_PART(bp.mrkt_type, ':', -1) = 'OT' THEN 'Future'
                WHEN SPLIT_PART(bp.mrkt_type, ':', -1) LIKE 'P:%' THEN 'PlayerProps'
                ELSE 'Prop'
            END AS bet_type_consolidated
        FROM FBG_ANALYTICS_ENGINEERING.REGULATORY.REGULATORY_TRANSACTIONS_MART rt
        JOIN FBG_SOURCE.OSB_SOURCE.BET_PARTS bp
            ON bp.bet_id = rt.TRANSACTION_WAGER_ID::NUMBER AND bp.part_no = 1
        WHERE rt.TRANSACTION_LOCATION_INITIALS = 'MA'
          AND rt.TRANSACTION_TYPE IN ('STAKE', 'FREEBET_STAKE', 'SETTLEMENT', 'REFUND')
          AND (bp.COMP_ID = 417222 OR bp.NODE_ID = 2232743)
          AND bp.event_time::DATE BETWEEN '2026-03-17' AND '2026-04-07'
          AND COALESCE(bp.mrkt_type, '') NOT LIKE '%NCAAW%'
    )
    SELECT '01. Total Bets' AS measure, COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') THEN
  TRANSACTION_WAGER_ID END)::VARCHAR AS value FROM base
    UNION ALL SELECT '02. Total Unique Users', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') THEN
  TRANSACTION_ACCOUNT_ID END)::VARCHAR FROM base
    UNION ALL SELECT '03. Opening Weekend Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND
  event_date BETWEEN '2026-03-19' AND '2026-03-22' THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '04. Sweet 16 + Elite 8 Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND
  event_date BETWEEN '2026-03-27' AND '2026-03-30' THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '05. Final Four Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND event_date
  BETWEEN '2026-04-04' AND '2026-04-07' THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '06. Parlay Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND
  SPORTSBOOK_WAGER_BET_TYPE LIKE 'Parlay%' THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '07. Straight Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND
  SPORTSBOOK_WAGER_BET_TYPE = 'Single' THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '08. In-Game Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND live_bet = TRUE
  THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '09. Pre-Game Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND (live_bet =
  FALSE OR live_bet IS NULL) THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '10. Futures Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND node_id = 2232743
   THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '11. Total Prop Bets', COUNT(DISTINCT CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') AND
  bet_type_consolidated IN ('Prop','PlayerProps') THEN TRANSACTION_WAGER_ID END)::VARCHAR FROM base
    UNION ALL SELECT '12. Gross Handle', ROUND(ABS(SUM(CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') THEN
  TRANSACTION_AMOUNT END)), 2)::VARCHAR FROM base
    UNION ALL SELECT '13. Net Handle', ROUND(ABS(SUM(CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') THEN TRANSACTION_AMOUNT
  END)) - SUM(CASE WHEN TRANSACTION_TYPE = 'REFUND' THEN TRANSACTION_AMOUNT ELSE 0 END), 2)::VARCHAR FROM base
    UNION ALL SELECT '14. GGR', ROUND(ABS(SUM(CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE') THEN TRANSACTION_AMOUNT END)) -
   SUM(CASE WHEN TRANSACTION_TYPE = 'REFUND' THEN TRANSACTION_AMOUNT ELSE 0 END) - SUM(CASE WHEN TRANSACTION_TYPE = 'SETTLEMENT' THEN
   TRANSACTION_AMOUNT ELSE 0 END), 2)::VARCHAR FROM base
    UNION ALL SELECT '15. Tax (20% of GGR)', ROUND(GREATEST(0.20 * (ABS(SUM(CASE WHEN TRANSACTION_TYPE IN ('STAKE','FREEBET_STAKE')
  THEN TRANSACTION_AMOUNT END)) - SUM(CASE WHEN TRANSACTION_TYPE = 'REFUND' THEN TRANSACTION_AMOUNT ELSE 0 END) - SUM(CASE WHEN
  TRANSACTION_TYPE = 'SETTLEMENT' THEN TRANSACTION_AMOUNT ELSE 0 END)), 0), 2)::VARCHAR FROM base
    ORDER BY measure;
