-- Query ID: 01c39a0c-0212-67a9-24dd-0703193727f3
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_L_WH
-- Executed: 2026-04-09T21:32:13.790000+00:00
-- Elapsed: 968ms
-- Environment: FBG

WITH __cs_cases AS (
  SELECT
    agent_name,
    case_id,
    case_number,
    case_status,
    case_subtype,
    case_type,
    is_closed,
    product_flag,
    case_created_est,
    last_modified_est,
    pending_start_time_est,
    account_id
  FROM FBG_ANALYTICS.OPERATIONS.CS_CASES
), __cs_cases AS (
  SELECT
    agent_name,
    case_id,
    case_number,
    case_status,
    case_subtype,
    case_type,
    is_closed,
    product_flag,
    case_created_est,
    last_modified_est,
    pending_start_time_est,
    account_id
  FROM FBG_ANALYTICS.OPERATIONS.CS_CASES
)
SELECT
  case_id,
  case_number,
  case_status,
  case_type,
  case_subtype,
  agent_name,
  account_id,
  case_created_est,
  last_modified_est,
  pending_start_time_est,
  CASE
    WHEN case_status = 'On Hold' AND NOT pending_start_time_est IS NULL
    THEN DATEDIFF(HOUR, pending_start_time_est, CURRENT_TIMESTAMP())
    WHEN case_status = 'Open'
    THEN DATEDIFF(HOUR, case_created_est, CURRENT_TIMESTAMP())
    ELSE NULL
  END AS hours_in_status
FROM __cs_cases
WHERE
  product_flag = 'FMX'
  AND is_closed = FALSE
  AND case_status IN ('Open', 'On Hold')
  AND (
    (
      case_status = 'On Hold'
      AND NOT pending_start_time_est IS NULL
      AND DATEDIFF(HOUR, pending_start_time_est, CURRENT_TIMESTAMP()) > 48
    )
    OR (
      case_status = 'Open'
      AND DATEDIFF(HOUR, case_created_est, CURRENT_TIMESTAMP()) > 48
    )
  )
ORDER BY
  hours_in_status DESC NULLS LAST /* Generated by Cortex */;
