-- Query ID: 01c39a26-0212-67a9-24dd-0703193cfbdf
-- Database: unknown
-- Schema: unknown
-- Warehouse: BI_XSM_WH
-- Executed: 2026-04-09T21:58:48.601000+00:00
-- Elapsed: 1696ms
-- Environment: FBG

SELECT 
    LEG_MARKET_TYPE AS MARKET_CODE,
    ANY_VALUE(LEG_MARKET) AS EXAMPLE_MARKET_NAME,
    COUNT(*) AS BET_COUNT
FROM FBG_ANALYTICS_ENGINEERING.TRADING.TRADING_SPORTSBOOK_MART
WHERE EVENT_SPORT_NAME = 'SOCCER'
  AND WAGER_PLACED_TIME_UTC >= DATEADD('day', -7, CURRENT_TIMESTAMP())
  AND DATEDIFF('minute', EVENT_START_TIME_UTC, WAGER_PLACED_TIME_UTC) >= 46
  AND (
    LEG_MARKET ILIKE '%2nd half%'
    OR LEG_MARKET ILIKE '%second half%'
    OR LEG_MARKET ILIKE '%half time%'
    OR LEG_MARKET ILIKE '%halftime%'
    OR LEG_MARKET ILIKE '%HT/FT%'
    OR LEG_MARKET ILIKE '%both halves%'
    OR LEG_MARKET ILIKE '%either half%'
    OR LEG_MARKET ILIKE '%half of%'
  )
GROUP BY LEG_MARKET_TYPE
ORDER BY BET_COUNT DESC;
