-- Query ID: 01c39a1a-0212-67a9-24dd-0703193b1193
-- Database: FBG_REPORTS
-- Schema: unknown
-- Warehouse: BI_XL_WH
-- Executed: 2026-04-09T21:46:13.694000+00:00
-- Elapsed: 28388ms
-- Environment: FBG

SELECT "Custom SQL Query"."ACCOUNT_ID" AS "ACCOUNT_ID",
  "Custom SQL Query"."ACQ_SOURCE" AS "ACQ_SOURCE",
  "Custom SQL Query"."Account Status" AS "Account Status",
  "Custom SQL Query"."Amelco ID" AS "Amelco ID",
  "Custom SQL Query"."BEST_EVER_PB_OC_SEGMENT" AS "BEST_EVER_PB_OC_SEGMENT",
  "Custom SQL Query"."BEST_OC_SEGMENT" AS "BEST_OC_SEGMENT",
  "Custom SQL Query"."BET_COUNT" AS "BET_COUNT",
  "Custom SQL Query"."BONUS_CAMPAIGN_ID" AS "BONUS_CAMPAIGN_ID",
  "Custom SQL Query"."BONUS_NAME" AS "BONUS_NAME",
  "Custom SQL Query"."CASINO_ACQ_PROMO_COST" AS "CASINO_ACQ_PROMO_COST",
  "Custom SQL Query"."CASINO_CLUSTER" AS "CASINO_CLUSTER",
  "Custom SQL Query"."CASINO_FIRST_YEAR_PRED_HANDLE" AS "CASINO_FIRST_YEAR_PRED_HANDLE",
  "Custom SQL Query"."CASINO_FIRST_YEAR_PRED_NGR" AS "CASINO_FIRST_YEAR_PRED_NGR",
  "Custom SQL Query"."CASINO_FIRST_YEAR_PRED_TRADING_WIN" AS "CASINO_FIRST_YEAR_PRED_TRADING_WIN",
  "Custom SQL Query"."CASINO_PROMO_COST_EXC_ACQ" AS "CASINO_PROMO_COST_EXC_ACQ",
  "Custom SQL Query"."CASINO_PROMO_STOPLIGHT_LIVE" AS "CASINO_PROMO_STOPLIGHT_LIVE",
  "Custom SQL Query"."CASINO_SEGMENT" AS "CASINO_SEGMENT",
  "Custom SQL Query"."CASINO_VALUE" AS "CASINO_VALUE",
  "Custom SQL Query"."CASINO_VIP" AS "CASINO_VIP",
  "Custom SQL Query"."EGGR" AS "EGGR",
  "Custom SQL Query"."EHOLD" AS "EHOLD",
  "Custom SQL Query"."ENGR" AS "ENGR",
  "Custom SQL Query"."FIRST_PRODUCT" AS "FIRST_PRODUCT",
  "Custom SQL Query"."FUND_TYPE" AS "FUND_TYPE",
  "Custom SQL Query"."GAME_ID" AS "GAME_ID",
  "Custom SQL Query"."GAMING_DATE" AS "GAMING_DATE",
  "Custom SQL Query"."GGR" AS "GGR",
  "Custom SQL Query"."HIGH_LEVEL_SEGMENT" AS "HIGH_LEVEL_SEGMENT",
  "Custom SQL Query"."HOLD" AS "HOLD",
  "Custom SQL Query"."JACKPOT_CONTRIBUTION" AS "JACKPOT_CONTRIBUTION",
  "Custom SQL Query"."MONTH_CASINO_LIFECYCLE" AS "MONTH_CASINO_LIFECYCLE",
  "Custom SQL Query"."MONTH_FBG_LIFECYCLE" AS "MONTH_FBG_LIFECYCLE",
  "Custom SQL Query"."MONTH_SPORT_LIFECYCLE" AS "MONTH_SPORT_LIFECYCLE",
  "Custom SQL Query"."NGR" AS "NGR",
  "Custom SQL Query"."NGR_HOLD" AS "NGR_HOLD",
  "Custom SQL Query"."PAYOUT" AS "PAYOUT",
  "Custom SQL Query"."PB_CASINO_SEGMENT" AS "PB_CASINO_SEGMENT",
  "Custom SQL Query"."PB_STATE" AS "PB_STATE",
  "Custom SQL Query"."PB_USER" AS "PB_USER",
  "Custom SQL Query"."PLACED_TIME" AS "PLACED_TIME",
  "Custom SQL Query"."PREVIOUS_MONTH_CASINO_LIFECYCLE" AS "PREVIOUS_MONTH_CASINO_LIFECYCLE",
  "Custom SQL Query"."PREVIOUS_MONTH_FBG_LIFECYCLE" AS "PREVIOUS_MONTH_FBG_LIFECYCLE",
  "Custom SQL Query"."PREVIOUS_MONTH_SPORT_LIFECYCLE" AS "PREVIOUS_MONTH_SPORT_LIFECYCLE",
  "Custom SQL Query"."SBK_FTU_DATE" AS "SBK_FTU_DATE",
  "Custom SQL Query"."SESSION_COMPLETED_TIMESTAMP_ALK" AS "SESSION_COMPLETED_TIMESTAMP_ALK",
  "Custom SQL Query"."SESSION_ID" AS "SESSION_ID",
  "Custom SQL Query"."SETTLED_TIME" AS "SETTLED_TIME",
  "Custom SQL Query"."STAKE" AS "STAKE",
  "Custom SQL Query"."STATE" AS "STATE",
  "Custom SQL Query"."TEST" AS "TEST",
  "Custom SQL Query"."VOID" AS "VOID"
FROM (
  select *
  from fbg_reports.regulatory.icasino_self_service
) "Custom SQL Query"
