-- Query ID: 01c399d4-0212-6dbe-24dd-0703192a2e93
-- Database: FBG_REPORTS
-- Schema: unknown
-- Warehouse: BI_XL_WH
-- Executed: 2026-04-09T20:36:22.515000+00:00
-- Elapsed: 3740ms
-- Environment: FBG

SELECT "Custom SQL Query"."BOOM_TOTAL_STAKES_VOIDED" AS "BOOM_TOTAL_STAKES_VOIDED",
  "Custom SQL Query"."BOOM_VARIANCE" AS "BOOM_VARIANCE",
  "Custom SQL Query"."EVOLUTION_TOTAL_PAYOUT_VOIDED" AS "EVOLUTION_TOTAL_PAYOUT_VOIDED",
  "Custom SQL Query"."EVOLUTION_VARIANCE" AS "EVOLUTION_VARIANCE",
  "Custom SQL Query"."Gaming Date" AS "Gaming Date",
  "Custom SQL Query"."IGT_TOTAL_WAGERED_VOIDED" AS "IGT_TOTAL_WAGERED_VOIDED",
  "Custom SQL Query"."IGT_VARIANCE" AS "IGT_VARIANCE",
  "Custom SQL Query"."JURISDICTION_CODE" AS "JURISDICTION_CODE",
  "Custom SQL Query"."JURISDICTION_NAME" AS "JURISDICTION_NAME",
  "Custom SQL Query"."LIGHT_WONDER_TOTAL_VOIDED" AS "LIGHT_WONDER_TOTAL_VOIDED",
  "Custom SQL Query"."LIGHT_WONDER_VARIANCE" AS "LIGHT_WONDER_VARIANCE",
  "Custom SQL Query"."WSR_BOOM_TOTAL_VOIDS" AS "WSR_BOOM_TOTAL_VOIDS",
  "Custom SQL Query"."WSR_EVOLUTION_TOTAL_VOIDS" AS "WSR_EVOLUTION_TOTAL_VOIDS",
  "Custom SQL Query"."WSR_IGT_TOTAL_VOIDS" AS "WSR_IGT_TOTAL_VOIDS",
  "Custom SQL Query"."WSR_LIGHT_WONDER_TOTAL_VOIDS" AS "WSR_LIGHT_WONDER_TOTAL_VOIDS"
FROM (
  select *
  from fbg_reports.regulatory.game_provider_void_reconciliation
) "Custom SQL Query"
