-- Query ID: 01c39a64-0212-6dbe-24dd-0703194a6c4b
-- Database: FBG_REPORTS
-- Schema: unknown
-- Warehouse: BI_XL_WH
-- Last Executed: 2026-04-09T23:00:37.676000+00:00
-- Elapsed: 380ms
-- Run Count: 3
-- Environment: FBG

SELECT "ICASINO_COMBINED_VARIANCE_CLOUD"."AGGREGATE_METHOD" AS "AGGREGATE_METHOD",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."DATA_MISSING" AS "DATA_MISSING",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."FBG_GAMES" AS "FBG_GAMES",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."FBG_NET" AS "FBG_NET",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."FBG_PAYOUT" AS "FBG_PAYOUT",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."FBG_ROUNDS" AS "FBG_ROUNDS",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."FBG_STAKE" AS "FBG_STAKE",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."GAME_OWNER" AS "GAME_OWNER",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."GAMING_DATE" AS "GAMING_DATE",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."JURISDICTION" AS "JURISDICTION",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."PROVIDER_GAMES" AS "PROVIDER_GAMES",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."PROVIDER_NET" AS "PROVIDER_NET",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."PROVIDER_PAYOUT" AS "PROVIDER_PAYOUT",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."PROVIDER_ROUNDS" AS "PROVIDER_ROUNDS",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."PROVIDER_STAKE" AS "PROVIDER_STAKE",
  "ICASINO_COMBINED_VARIANCE_CLOUD"."VARIANCE_AMOUNT" AS "VARIANCE_AMOUNT"
FROM "FBG_REPORTS"."REGULATORY"."ICASINO_COMBINED_VARIANCE_CLOUD" "ICASINO_COMBINED_VARIANCE_CLOUD"
